### ISSUE TITLE
ccl: allow partitioned inverted indexes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10066]
PR: https://github.com/cockroachdb/cockroach/pull/59858

From release notes:
> Partitioned [inverted indexes](../v21.1/inverted-indexes.html) are now supported. [#59858][#59858] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Hi @mgartner !

I looked at the tests you added for inverted indexes on `REGIONAL BY ROW` tables in cockroachdb/cockroach#60018

my assumption is that if I add an inverted index to a JSON column in a RBR table as shown in e.g.

```sql
CREATE TABLE regional_by_row_table (
   pk int,
   a int,
   j JSON,
   INVERTED INDEX (a, j)
 )
 LOCALITY REGIONAL BY ROW
```

then CockroachDB automatically partitions the index for me by region like it does with other indexes on RBR tables (as described in this docs PR: #10280 )

is that correct?

(cc @rytaft since you reviewed #10280 and I may not be formulating the question very well w.r.t. how inverted indexes work)

**Comment by rytaft** [comment]
Yep that's correct! `crdb_region` is automatically added as an implicit partitioning column to all indexes, including inverted indexes (unless `crdb_region` is listed explicitly, in which case the explicit column is used as the partitioning column).
