### ISSUE TITLE
Document querybench workload

### ISSUE THREAD

**Issue by lin-crl** [cockroachdb/docs#10176]
Jessie Lin (lin-crl) commented:

## Title
Add section for workload querybench

## Description
querybench is very handy for customer

## Outline
follow similar structures and examples.

## Expected Audience
Developers and architects

Jira Issue: DOC-1068

**Comment by jseldess** [comment]
@lin-crl, I don't see any such workload or command in the `cockroach` cli. Can you clarify what you mean here?

We recently removed `cockroach systembench` (see https://github.com/cockroachdb/cockroach/pull/62305 for details there). Perhaps you're referring to that?

**Comment by jseldess** [comment]
Based on conversations in a different channel, @lin-crl is referring to `querybench` built into the stand-alone `workload` binary at `wget https://edge-binaries.cockroachdb.com/cockroach/workload.LATEST`, which is used in this benchmarking workshop: https://github.com/cockroachlabs/workshop_benchmark/blob/master/instructor_benchmark_config.md

In general, we have stopped leveraging the stand-alone binary in favor of the `cockroach workload` commands. For example, we recently changed our TPC-C benchmarking docs to use `cockroach workload tpcc` instead of `workload tpcc`. I believe this guidance came from Engineering. @nvanbenschoten, @petermattis, do you have guidance here? Do we want to stop leveraging stand-alone `workload` just in docs or also in field materials? cc @awoods187 as well.

**Comment by lin-crl** [comment]
I didn't know `querybench` wasn't part of `cockroach` binary. It's a very handy tool to simulate a custom workload using an arbitral sql file for workshop or prototyping. But if it's engineering decision that it will not be, then we in field will have to find a workaround. Currently we install the binary manually on vms. It gets a bit tricky in docker/k8.
