### ISSUE TITLE
Improve the installation docs

### ISSUE THREAD

**Issue by emily-horing** [cockroachdb/docs#10174]
## Issue Description
All first time users need to download the CRDB binary to connect to their cluster (whether on CRDB or CC, this is usually a required step), but if you are not an experienced developer our download docs are extremely confusing. [This page](https://www.cockroachlabs.com/docs/v20.2/install-cockroachdb-mac.html) makes it seem like you need to follow every single step listed, but in reality, you would just be downloading the binary a bunch of times in different ways. In addition to running into this problem personally when I first interviewed at CRL, we've recently seen CC interviewees who are Hackathon students get totally tripped up by this page. 

## Suggested Resolution 
Add a sentence at the top of the page "Use one of these methods to install the CockroachDB binary". Label each download method as an option, eg "Option 1: Install with Homebrew", "Option 2: Download the Binary", "Option 3: Use Kuberenets", etc.

Doing this will make it much clearer that all of these steps are not required and are in fact different variations of the same thing.

**Comment by jseldess** [comment]
@emily-horing, we've rarely heard that the install page is "extremely confusing". On the contrary, when I look at "Was this page helpful?" responses since the beginning of February, across all install pages, we received 12 positive submissions and just 3 negative submissions. I'm not against helping users understand that the page contains "options", either through intro text or heading language, but do you have any examples to support that the current approach is very confusing to developers?

**Comment by jseldess** [comment]
In any case, @emily-horing, I just opened a PR with an easy fix, I think. Assigned you as reviewer: https://github.com/cockroachdb/docs/pull/10180

**Comment by emily-horing** [comment]
I can share a video with you from a recent user session -- I think for people who are newer to development (which we are getting more of based on our survey data!) it will help a lot to clarify. "Extremely" may be a bit extreme... probably just channeling the frustration I had when I first went through it ~2 years ago :)
