### ISSUE TITLE
Move nightly htmltest run to Netlify

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10178]
As a following up to [this PR](https://github.com/cockroachdb/docs/pull/10171), where we moved our PR docs testing from TC to Netlify, we should investigate whether we can do our nightly htmltest run on Netlify as well, which would allows us to remove the `ci` assets in our repo.

**Comment by yingzhuchin** [comment]
I can set up nightly htmltest to run on Netlify, but broken links cause the build to fail, and so the PR can't be merged. We have two options: 1) Fix the broken links before we merge. 2) Mark nightly htmltest runs as passing for now even though there are broken links. Which do you prefer, @jseldess?

**Comment by yingzhuchin** [comment]
In order to set up nightly runs, I first need a Netlify deploy that succeeds with external link checks. Because we currently have broken links, deploy builds fail (example: https://app.netlify.com/sites/cockroachdb-docs/deploys/6061ed3dd819900007e49012). We can either 1) fix broken links before working on setting up nightly runs in Netlify, or 2) set up nightly runs that get marked green even though there are broken links, much like vale checks work now. 

Which would you prefer, @jseldess?

**Comment by yingzhuchin** [comment]
I may have found a workaround. Let me update soon.

**Comment by yingzhuchin** [comment]
Update: htmltest checks for external links are now running nightly on Netlify at 10 pm UTC. Example output: https://app.netlify.com/sites/cockroachdb-docs/deploys/60625a8e390f1634e4323500
