### ISSUE TITLE
Add docs test to validate presence and length of summary field in front-matter

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10183]
The `summary` field in a page's front-matter is used to generate a meta description that is important for SEO. We should add a PR check to make sure pages have `summary` and then they are between 50 and 160 characters.

**Comment by jseldess** [comment]
cc @yingzhuchin, another test that we could build into Netlify.

**Comment by yingzhuchin** [comment]
Here are pages in v21.1 without a summary:
-     admin-ui-cluster-overview-page.md
-     admin-ui-statements-page.md
-     cockroachdb-architecture.md

Here are all the pages that have summaries with fewer than 50 characters:
-     bulk-update-data.md
-     cancel-job.md
-     cockroach-import.md
-     cockroach-nodelocal-upload.md
-     cockroach-quit.md
-     cockroach-start-single-node.md
-     cockroach-userfile-delete.md
-     cockroach-userfile-upload.md
-     common-errors.md
-     connection-pooling.md
-     cost-based-optimizer.md                                                                                                                                                                       
-     date.md
-     dbeaver.md
-     debug-and-error-logs.md
-     delete.md
-     deploy-cockroachdb-on-digital-ocean-insecure.md
-     deploy-cockroachdb-on-digital-ocean.md
-     enterprise-licensing.md
-     enum.md
-     file-an-issue.md
-     flyway.md
-     import.md
-     intellij-idea.md
-     known-limitations.md
-     licensing-faqs.md
-     liquibase.md
-     monitor-cockroachdb-with-prometheus.md
-     multilinestring.md
-     multipoint.md
-     multipolygon.md
-     order-by.md
-     polygon.md
-     query-spatial-data.md
-     recommended-production-settings.md
-     release-savepoint.md
-     remove-nodes.md
-     savepoint.md
-     schema-design-database.md
-     schema-design-indexes.md
-     schema-design-table.md
-     schema-design-update.md
-     selection-queries.md
-     sql-grammar.md
-     sql-playground.md
-     sql-statements.md
-     support-resources.md
-     time.md
-     update.md
-     use-cloud-storage-for-bulk-operations.md
- 

And here are pages that have summaries with over 160 characters:
- create-changefeed.md
- orchestrate-cockroachdb-with-kubernetes-multi-cluster.md

I think we should fix the above before merging any new tests to CI. Otherwise we're incurring build minutes on each PR without taking any action. What do you think, @jseldess?

**Comment by jseldess** [comment]
@yingzhuchin, just opened a PR to address the meta description issues: https://github.com/cockroachdb/docs/pull/10251. Please review. Note that the following two pages without meta descriptions will be handled separately by @taroface:

admin-ui-cluster-overview-page.md
admin-ui-statements-page.md
