### ISSUE TITLE
Allow users to search for updated content in the dev version of the docs

### ISSUE THREAD

**Issue by ianjevans** [cockroachdb/docs#10460]
Ian Evans (ianjevans) commented:

We currently index both `stable` and `dev` versions of the docs, but to prioritize the `stable` version we don't display results if the topic exists in both `stable` and `dev`.

This makes it impossible to search for updated content in `dev`. For example if we added an additional keyword to an existing SQL statement in `dev`, users would not be able to find that content using search. Since some searches return `dev` topics, users might reasonably assume that the content doesn't exist in the `dev` version.

There are a couple different options for allowing full search of the `dev` docs:

- Return `stable` and `dev` content, even if that means more duplicate topics for the user to choose from.
- Use a checkbox to allow the user to select `stable` (default) and `dev` versions in their search.

Jira Issue: DOC-1613

**Comment by rmloveland** [comment]
Another option when the workflow begins on a specific docs page: if I am looking at a v21.1 page, and I go to the search box on that page and type in a term, I should only see results for v21.1, since that is the version of CockroachDB I am interested in.  

(and then the N version checkboxes would be great to have on the full search results page so I could change my mind, do another more advanced search across one or more different versions, etc.)
