### ISSUE TITLE
File/External Storage Docs for Bulk Operations Reorg

### ISSUE THREAD

**Issue by katmayb** [cockroachdb/docs#10544]
Here is a list of the issues Lauren put together that might be a start/inform some reorganization of the external storage docs. It would be great to get your input @mwang1026 on scoping this & whether there are any further issues/areas to work on within this project.

#9999 
#10285 
#8603 
#9282 / #8019
#7696
#3724
#4700 (maybe)

**Comment by kathancox** [comment]
I've taken a stab at figuring out scope for this. Looking through the issues, a couple might not be relevant. 

Overall, particularly with #10285, wondering if it would serve users to have pages _per_ cloud storage/file storage, which then show examples for the different operations for AWS, GCS, etc. respectively. Currently, it seems mixed on whether each storage provider is demonstrated or not (see [`IMPORT`](https://www.cockroachlabs.com/docs/v21.1/import.html) vs. [`BACKUP`](https://www.cockroachlabs.com/docs/v21.1/backup.html)), maybe leads to confusion? 

So, for example, on the `IMPORT` page, could reduce the example overload by saying something like "these examples show s3, if you're using blah go here." Then provide a _very clear note_ to the separate cloud storage/file page. The current bulk operation pages could kind of act as hubs, with the content that is currently on there and links to the distinct pages. I would kind of hope this would promote better discoverability for users too.

This reshuffle could resolve some of the issues in this list, which relate to specific examples. 

It'd be good to know if I've missed any possible negatives here for this kind of breakdown. Perhaps, setting a precedent for a whole page devoted to a particular cloud/external storage.

**Comment by mwang1026** [comment]
My question to you -- would it be a crazy burden to update across those docs if there's a change that impacts them all?

That being said, I think your skeleton makes a ton of sense and then we can weave cloud-specific quirks into each of their docs and generally, assessment that we could create a weaved matrix of references could help the problem here. So at a high level.

- Cloud Storage
  - s3
  - gcs
  - azure
  - http
  - nfs / nodelocal
- userfile
- local file server

and each of those is a dedicated page, with the `IMPORT`, `BACKUP`, etc. linking to the other types of storage.

I think this is also an opportunity to talk about how we don't recommend backing up to `nodelocal` (because it's on the same machine as your cluster so if you need to restore from backup and your cluster machines are down...?) or HTTP (because of the file listing limitation). But we can make that a separately scoped project too.

Let me know how else I can help here -- I really like your plan!

**Comment by mwang1026** [comment]
Another one https://github.com/cockroachdb/docs/issues/8461

**Comment by mwang1026** [comment]
And another :) https://github.com/cockroachdb/docs/issues/4398

**Comment by mwang1026** [comment]
URI encoding keys -- Azure especially includes `=` and `+` in keys. Yuck.

**Comment by kathancox** [comment]
@mwang1026 I have changed my mind a bit.... 

Now having tested and planned part of this project I'm going to break down the updates. We mentioned separate cloud storage pages above, but with more time, I think including a toggle at the start of each bulk SQL statement example section (like https://www.cockroachlabs.com/docs/v21.1/backup.html#examples) would make more sense to avoid duplication of examples, and to ensure the user can pick what they're seeing depending on the bulk operation they're working with.

Update plans:

1. Update to Authentication & Encryption section on cloud storage page
2. Add toggled examples to the Backup page for AWS, GCS, Azure
3. Add toggled examples to the Restore page AWS, GCS, Azure
4. Updates to nodelocal documentation
5. Add toggled examples to Import/Export pages
6. Cloud storage related updates for create changefeed
7. [probably] Remove example file URL section from the bulk operations page once all examples are in place 
8. Additional refinements

I think the cloud storage page could expand with quirks... and in the future end up with separate cloud storage pages, but I think for now separate pages could be overkill. 

You'll see me adding these incremental change ^ over the next few weeks. Look forward to your feedback on them!
