### ISSUE TITLE
CC client login - certificate / config directory

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#10579]
Raphael 'kena' Poss (knz) commented:

I was made aware by @aaron-crl of a plan to recommend users to store their TLS certs in a pre-selected directory; I also understand the pre-selected directory would be `$HOME/cockroachcloud/config`

**This particular directory choice is a problem**

- it creates a conspicuous directory in the user's home directory, at a place where most users expect their directory listings to remain simple and unencumbered.
- it's non-standard; on most OS there is a standard location for configuration files, that receive special treatment when users migrate their computer, perform backups etc
- users will *eventually* complain about it. If they complain later in our development cycle, we may already have multiple apps / drivers / recommendations that have "baked in" this recommended location, which will make it overall difficult to change.

Therefore, I recommend ensuring a better choice of directory from the get-go:

- at the very least, use `$HOME/.cockroachcloud`  by default. This will ensure that the directory listing doesn't become polluted on all the unixy targets including macOS
- the better solution is to choose a target directory that works on each OS where users are going to run *client* apps:
  - unix: `$HOME/.cockroachcloud`
  - windows: `%appdata%/CockroachCloud`
  - macOS: `$HOME/Library/CockroachCloud`
  - etc

cc @bdarnell @jseldess

**Comment by jseldess** [comment]
@knz, I'm glad you're offering help here, but I think the main point of contact should be @emily-horing and Rachel S. I've been helping to figure out the commands that users can copy from the CC Console to make downloading the cert and referencing it in connection strings more seamless for novice users, of which we apparently have many on CC free tier. I think my suggestions for the cert location was `${HOME}/cockroachcloud/certs`, but I was just trying to keep it simple and intuitive. You make good counter arguments. 

@emily-horing, you should probably sync with @knz and/or @bdarnell on the right location here.

**Comment by emily-horing** [comment]
Thanks @knz for the input! Like Jesse said, we are in the process of improving the user experience getting connected to CC and frankly need direction from engineering/security to make sure our implementation here is satisfactory. We are currently pulling together the correct syntax for the curl commands for each OS [here](https://docs.google.com/document/d/1ZAc8kgf6MEc-fvKOURN8knBELJsmS3Cut26wDQK9CyI/edit?usp=sharing), it would be extremely helpful if you could add your examples to that!

**Comment by knz** [comment]
Thanks Jesse for explaining that Emily is leading here. I did not know this.
Emily, I'm available whenever if you want to chat.

**Comment by bdarnell** [comment]
Some more considerations: 
- `cockroach sql` already recognizes `~/.cockroach-certs` by default (although rigid naming conventions currently make it awkward to combine a cloud and self-hosted or multiple self-hosted clusters within this directory)
- `psql` (and perhaps other tools? not sure how widespread this is) recognize `~/.postgresql/root.crt` by default
- Is the XDG standard still a thing or have people given up on it? That would argue for `~/.config/cockroachcloud` instead adding a new top-level dotfile.
- Paths that require env var substitution are still awkward to use - you can't necessarily drop them in a config file unless your config format supports this.

Most importantly, in some languages/drivers all of this is optional since the driver can recognize the system trust roots by default. We should be pushing for this as the default, and consider submitting PRs to upstream drivers to enable them to do this as necessary. Providing more literal documentation about how to manage the CA certificate should be a last resort.

**Comment by knz** [comment]
> cockroach sql already recognizes ~/.cockroach-certs by default (although rigid naming conventions currently make it awkward to combine a cloud and self-hosted or multiple self-hosted clusters within this directory)

Aaron thought about this and chose a different directory for this reason -- it's all too likely that a user will experiment with running `cockroach cert` locally and then get confused about why their CC conn string doesn't work.

> psql (and perhaps other tools? not sure how widespread this is) recognize ~/.postgresql/root.crt by default

THAT IS AMAZING and I think neither aaron nor I knew this. If other tools/drivers knew how to use that, we could exploit it as well. Thanks for finding it out.

> Is the XDG standard still a thing or have people given up on it? That would argue for ~/.config/cockroachcloud instead adding a new top-level dotfile.

Good point; the XDG standard is in fact still a thing and I simply forgot about it. Will update Emily's spreadsheet accordingly.

> Paths that require env var substitution are still awkward to use - you can't necessarily drop them in a config file unless your config format supports this

This means we need to teach the user how to substitute the thing in a file, perhaps something with `eval ... >~/.config/cockroachcloud/url`. Unsure.

> Most importantly, in some languages/drivers all of this is optional since the driver can recognize the system trust roots by default. 

Agreed; this should remain the north star. I hope Emily will integrate this into our long-term plans.

**Comment by emily-horing** [comment]
> psql (and perhaps other tools? not sure how widespread this is) recognize ~/.postgresql/root.crt by default
Is this basically that we can take advantage of other tools' knowledge of the same cert to remove the need for the customer to download the cert entirely? I'm definitely interested to learn more about an option like this, it would make for an excellent v2 improvement!

cc @vy-ton re: drivers recognizing the system trust roots by default. 

@bdarnell how closely related is this suggestion to your comment in our recent email thread about certs (copying here for visibility)?
> I want to highlight the root cause here: Certs are relatively standard, but manual management of certs is not. This is largely a limitation of (some) of the existing postgres drivers. If we created our own drivers for major languages, we could greatly simplify this process and get rid of all of the manual cert stuff for CockroachCloud (it may still be necessary for self-hosted deployments, but even then we have other ways to simplify it) if we had our own drivers. Furthermore, for some drivers the CA certificate is *already* optional for CockroachCloud. As a part of figuring out per-driver instructions we should identify whether the CA cert is required or not (and where it is required, we may be able to submit a simple PR upstream to make it optional).

**Comment by bdarnell** [comment]
> > psql (and perhaps other tools? not sure how widespread this is) recognize ~/.postgresql/root.crt by default

> Is this basically that we can take advantage of other tools' knowledge of the same cert to remove the need for the customer to download the cert entirely? I'm definitely interested to learn more about an option like this, it would make for an excellent v2 improvement!

There are two things here:
1. Because CockroachCloud uses letsencrypt certificates (at least for free tier; haven't tested dedicated yet), drivers that use the system root certificates work without downloading anything or customizing the URL at all. For example, the `asyncpg` python driver works this way, supporting a URL like `postgres://ben:passwordredacted@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster=grand-lamb-442` without downloading anything.
2. For drivers that default to `~/.postgresql/root.crt`, you'd still have to download the cert, but if you put it in the right location you don't have to edit the URL (i.e. using the same URL in the previous example after downloading the file). Python's `psycopg2` works this way, and because this is based on the C `libpq`, this bodes well for drivers in other languages. 

> how closely related is this suggestion to your comment in our recent email thread about certs (copying here for visibility)?

It's the same line of reasoning. I'm collecting data about connection string issues (including but not limited to cert stuff) and will have some recommendations soon.

**Comment by bdarnell** [comment]
I've tested all of our supported/documented languages and drivers. Some of them (go, javascript, and java) can use the system root certificates (by default in go and js, but it must be explicitly requested in java. This means we may not be able to use the no-download option for java-based tools like datagrip). The ones that can't (python and ruby) are all based on `libpq` and all recognize `~/.postgresql/root.crt` by default.
