### ISSUE TITLE
Clarify which parts of 21.1 multi-region are enterprise

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10601]
Jesse Seldess (jseldess) commented:

A user on our Community Slack channel asked:

> Have all non-default multi region capabilities been moved to enterprise? That’s what the docs seem to imply, previously only row level geo partitioning required enterprise, right? A specific example – does pinning a whole table to a specific region require enterprise now? It definitely did not in v20.
>
> Ok, looks like this might be a docs issue, this page claims that all the listed features require enterprise which I don’t think is true? https://www.cockroachlabs.com/docs/v21.1/multiregion-overview

Jira Issue: DOC-1583

**Comment by jseldess** [comment]
cc @rmloveland, @awoods187

**Comment by awoods187** [comment]
Everything multi-region has always been enterprise except follow-the-workload. 21.1 did not change that.

**Comment by jseldess** [comment]
@awoods187, in 20.2 and earlier, you could pin an entire table to a region without an enterprise license, whereas you needed a license for partitioning, aspects of duplicate indexes (zone configs for secondary indexes), and follower reads, right?

**Comment by awoods187** [comment]
You could technically pin an entire table to a region without an enterprise license using zone configs but every topology pattern except follow-the-workload required an enterprise license (geo-partitioned replicas, geo-partitioned leaseholders, duplicate indexes, and follower reads). We should be transparent about the new multi-region functionality but we didn't remove any behavior and to meaningfully use CRDB multi-region still requires an enterprise license.

**Comment by mlazowik** [comment]
In particular https://www.cockroachlabs.com/docs/v21.1/multiregion-overview#regional-tables looks as if it required enterprise (because the whole page is marked as such), which I'm not sure if it does? It's the same functionality as mentioned zone config.

On a related note: sql statements docs usually state that something requires enterprise, but https://www.cockroachlabs.com/docs/v21.1/set-locality.html does not. + the same problem – does that apply to all 3 locality options or only by row (and maybe global)?

**Comment by mlazowik** [comment]
Btw I think that if `GLOBAL` was enterprise-only https://github.com/cockroachdb/cockroach/issues/63365 would not make sense?
