### ISSUE TITLE
release-21.1: sql/opt: support implicit SELECT FOR UPDATE locking with nested renders

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#10655]
PR: https://github.com/cockroachdb/cockroach/pull/65363

From release notes:
> [`INSERT INTO ... ON CONFLICT ... DO UPDATE SET`](../v21.1/insert.html) statements without predicates now acquire locks using the `FOR UPDATE` locking mode during their initial row scan, which improves performance for contended workloads. This behavior is configurable using the `enable_implicit_select_for_update` [session variable](../v21.1/set-vars.html) and the `sql.defaults.implicit_select_for_update.enabled` [cluster setting](../v21.1/cluster-settings.html). [#65363][#65363] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
This behavior (and `enable_implicit_select_for_update`) seems to already be documented on https://www.cockroachlabs.com/docs/stable/select-for-update.html.

I could be mistaken, but it appears that cockroachdb/cockroach#65363 doesn't change expected behavior; it fixes a bug.

Closing for now.

@nvanbenschoten please reopen if you disagree.
