### ISSUE TITLE
sql: clarify region survivability ups replication factor to 5

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#10673]
In https://www.cockroachlabs.com/docs/v21.1/multiregion-overview.html#surviving-region-failures we disucss surviving region failures but we don't specify that we up the replication factor to 5. We want to be careful about exposing this in too much detail but its valuable to document it and to explain that this will allow one node failure without moving the leaseholder out of the region to protect read latency.

**Comment by awoods187** [comment]
We probably need to introduce it in the architecture docs too https://www.cockroachlabs.com/docs/v21.1/architecture/replication-layer.html#non-voting-replicas

**Comment by awoods187** [comment]
We don't expect users to directly set RF anymore--they should declare their survival goals to us and we will adjust the replicas accordingly. We don't want them to set it directly because it has complicated interactions with leaseholders, replica placement, and latency goals.

**Comment by rmloveland** [comment]
Andy is this request from a user?  If so do you mind adding more context about what we want to solve by doing this?

Presumably if you are a new user of the multi-region abstractions, you don't necessarily know about `num_replicas=5` and zone configs, nor do you really need to care about it since we now handle that for you (right?)

And if you are a user of the old way of doing things transitioning to the new, you can still look at your zone configs after running the new SQL statements and find out what is happening using `SHOW ZONE CONFIGURATIONS`?  but then basically (AIUI) you should like, not touch it too much because you are likely to run into breaking the various multi-region zone config validations

If this is an internal ask I'd rather we do some internal docs/training and not add this to user-facing docs.

There is a cost here: if 5% of users need this, it's now in the docs adding complexity and tripping up the other 95% who don't.  Once you have to know about `num_replicas`, you have to know about zone configs.  Once you have to know about zone configs, you are down the rabbit hole and this is no longer an "abstraction" if you have to know all about how zone configs work in order to use it

ya know? or am I totes misunderstanding something here?

**Comment by awoods187** [comment]
It's come up several times from internal folks needing to explain things to users (and to prove that certain failure domains work). I agree with the general spirit of your point that we don't want to confuse everyone for a more involved minority. However, I think this information needs to be available as a part of reference documentation. We absolutely do not want the average user to need to understand replication and quorum, but the advanced user should be able to discover this information.
