### ISSUE TITLE
feature request: view all release notes for vXY.Z.* on one big page

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#10963]
Richard Loveland (rmloveland) commented:

We have had folks ask internally.  Would likely be useful for external users as well.

Current workaround is to clone the docs repo and do the following inelegant things:

    $ cd ~/path/to/docs/releases
    $ cat v20.2.*.md > v20.2.all.md # or some version
    $ markdown v20.2.all.md > v20.2.all.html

Of course this does not really help most users.

See also:

- cockroachdb/docs#5368

Jira Issue: DOC-1496

**Comment by rmloveland** [comment]
cc @mikeCRL since I'm not sure how exactly to label/categorize this

**Comment by rafiss** [comment]
We've had external customers ask for this as well. The biggest pain point is that the release notes from alpha/beta versions are on a separate page, and some customers often just skip right over the alpha release notes since they wouldn't expect to find anything important there. But sometimes we do document breaking changes on alpha release notes but nowhere else.

**Comment by shermanCRL** [comment]
Is there any automation that generates the current patch release pages?

**Comment by rmloveland** [comment]
thanks for the additional context @rafiss !

> Is there any automation that generates the current patch release pages?

yes @shermanCRL , it's a script in the CockroachDB repo: https://github.com/cockroachdb/cockroach/blob/master/scripts/release-notes.py 

It takes an arbitrary start and end commit SHA (or tag, I think?), so I think it could be used to generate something like "show me all changes from v20.2.0 through v20.2.13" or similar on one page

**Comment by vy-ton** [comment]
@jseldess do you see this being prioritized for 21.2?
