### ISSUE TITLE
cli: clarify --host and --advertise-host usage in cockroach start

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1174]
We should make sure the `--host` and `--advertise-host` flag descriptions are correct and helpful, and we should add better examples for specific scenarios.

@mberhault, in a thread with a customer:

```
`--host` controls which interface the server listens on. if you want it to tell the other nodes how to reach it (eg: hostname means nothing to the other nodes) you should use `--advertise-host`

[12:15]  
so let's say you have the following VM: hostname: `my-host`, ip: `192.168.1.1` and `my-host` does not resolve on the other hosts

[12:16]  
if you specify `--host=192.168.1.1`, it will only listen on eth1 (or whatever interface) and (I think) advertise `192.168.1.1` to the other nodes

[12:16]  
if you specify `--advertise-host=192.168.1.1`, it will listen on all interfaces but tell other nodes to use `192.168.1.1`
```

**Comment by jseldess** [comment]
@mberhault, @bdarnell, I'd like to improve the docs on `--host` and `--advertise-host` soon. Heard from another user that they're hard to understand. Some questions:

- If you don't set `--advertise-host`, and you don't set `--host` (so the node listens on all interfaces), what address gets advertised to other nodes? Can we say with any certainty? 
- Is it most important to set `--advertise-host` when you need a node to advertise a specific address while listening on a different address (`--host` set to something specific) or on all addresses (`--host` not set)? The scenario that comes to my mind is running across clouds, where nodes on cloud 1 need to tell nodes on cloud 2 to communicate on an external address...

**Comment by bdarnell** [comment]
If you don't set either flag, the node advertises its default hostname (which you can see by running `hostname` at a shell prompt). It's going to be more common to set `--advertise-host` without `--host` than to use both, although they're really independent.

The `--advertise-host` flag is used to fix something that's broken. If your nodes can't talk to each other, you might need to add this flag. The `--host` flag is basically a security feature. Adding `--host` can improve security (which is why I recommend `--host=localhost` for local test clusters), but it's never going to be required to get things working. Using the `--host` flag sometimes complicates things since it means that `localhost` no longer works when you would expect it to.

**Comment by jseldess** [comment]
@bdarnell, @mberhault, I'm still trying to figure out the best practice here. Given nothing unexpected, which makes the most sense as the default approach?

1. Set neither `--host` nor `--advertise-host`. In this case, the node listens on all interfaces, but you could use `hostname` to find the address being advertised and just use that address when, say, proxying from a load balancer or connecting with a client (though using any other valid address would work as well).
2. Set `--advertise-host` to the specific address you want advertised, but don't set `--host`. In this case, the node listens on all interfaces, but a load balancer or clients would generally use the `--advertise-host` address (though using any other valid address would work as well).
3. Set `--host` to the specific address you want the node to advertise and listen on. In this case, the node listens only on that address, and a load balancer or clients would need to use the specific `--host` address.

**Comment by bdarnell** [comment]
The default is to not set either flag; this should work as long as your DNS and hostnames are set up correctly. These are the guidelines I would use:

1. If you are running a local-only test/demo/etc cluster, set `--host=localhost` for security.
2. If the machine has multiple network interfaces:
  a. If you want to guarantee that cockroach will only use one of them (this is mainly a security decision), set `--host` to that interface's address
  b. If you want cockroach nodes to talk to each other over a specific interface (for example, because one interface is cheaper/faster) while still allowing clients on any interface, and the defaults aren't doing what you want, use `--advertise-host` to specify a hostname that resolves to the right address.
3. If your hostnames don't resolve correctly from other machines in the cluster, use `--advertise-host` to tell cockroach what address/hostname to use instead.

These generic instructions require an understanding of your network and how you want cockroach to use it. We're going to want to provide cookbook instructions for specific deployment scenarios. For example, AWS machines have two network interfaces (or at least they used to. our current AWS test cluster doesn't), and in an all-AWS deployment you'd probably want to set `--host`, while if you need a cluster that spans AWS and non-AWS you'd want to not set that and may need `--advertise-host` instead.

**Comment by jseldess** [comment]
@mberhault, yesterday, we discussed a possible Q4 project of adding documentation describing different scenarios with recommendations about how to use `--host` and/or `--advertise-host`. Can you help me list out the scenarios we might want to cover?
