### ISSUE TITLE
Clarify SQL time-series metrics for measuring latency

### ISSUE THREAD

**Issue by kevin-v-ngo** [cockroachdb/docs#11883]
The following metric definitions are not clear from our [documentation](https://www.cockroachlabs.com/docs/v21.1/ui-custom-chart-debug-page.html):

sql.exec.latency - Latency in nanoseconds of SQL statement execution  
sql.distsql.exec.latency - Latency in nanoseconds of DistSQL statement execution

sql.service.latency - Latency in nanoseconds of SQL request execution
sql.distsql.service.latency - Latency in nanoseconds of DistSQL request execution

**Definitions should be updated to reflect the following:**

sql.exec.latency - Latency in nanoseconds of all SQL statement executions. This metric does not include the time to parse and plan the statement. 
sql.distsql.exec.latency - Latency in nanoseconds of SQL statement executions running on the distributed execution engine. This metric does not include the time to parse and plan the statement. 

sql.service.latency - Latency in nanoseconds of SQL request execution including the time to parse + plan the statement.
sql.distsql.service.latency - Latency in nanoseconds of SQL statement executions running on the distributed execution engine including parse + plan time.

**Comment by ianjevans** [comment]
@kevin-v-ngo I can fix the description in the docs as a near term solution, but I got a little more context on this list of metrics and how it was generated.

The metrics were scraped using a script all the way back in v2.1, and have only been updated here and there since. I'm almost certain the list of metrics is out of date.

A better long term solution is to generate the list of metrics from the code, just like we do with [cluster settings](https://github.com/cockroachdb/cockroach/tree/master/docs/generated) etc. Then we could include them in the docs and be sure they're always up to date. This would involve embedding the descriptions in the code.

**Comment by kevin-v-ngo** [comment]
Thanks @ianjevans! I spoke with @thtruo on this. I suspect the long-term solution is dependent on this [issue](https://github.com/cockroachdb/cockroach/issues/67666). Tommy, do you know what the current target is for this issue?

**Comment by thtruo** [comment]
In the 22.1 cycle, we're continuing our initiative to upgrade our metrics framework and https://github.com/cockroachdb/cockroach/issues/67666 will be a part of that theme. So sometime in the 22.1 cycle
