### ISSUE TITLE
Consider de-emphasizing insecure deployments

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1194]
Based on input from @bdarnell in https://github.com/cockroachdb/docs/pull/1184, we should consider de-emphasizing insecure deployments in our docs. 

> Note that our insecure mode is even less secure than most databases', so people who might run mysql or postgres without tls might still not want to use our insecure mode. We should emphasize that insecure mode is only for testing with data your don't care about (and to the extent that we can simplify the certificate management stuff, we should phase out documentation of insecure clusters completely. Maybe we should limit discussion of insecure clusters to the single-node case)

**Comment by jseldess** [comment]
@mberhault, @petermattis, @spencerkimball, opinions on this? I'm personally hesitant to remove all docs on insecure deployment, since it's considerably simpler than running with security and, thus, good for gaining experience with the product. 

@bdarnell, how are we even less secure than most databases? We should probably explain this in the docs somewhere?

**Comment by petermattis** [comment]
Is there a proposal for how to de-emphasize insecure deployments? I'd be fine if the various container orchestration deployment docs only talked about secure deployments and there was only a single description of insecure deployments.

**Comment by bdarnell** [comment]
@petermattis My proposal is that we'd only talk about insecure mode for single-node deployments (`start-a-local-cluster{,in-docker}.html`) and that the multi-node instructions (everything under the "Deploy" heading) would be secure-only. I'd love to use this as a forcing function to provide better tools for certificate management so it's no longer tempting to run in insecure mode, but that's probably a longer-term project.

@jseldess We listen on TCP (even if it's just localhost) instead of unix sockets, and we default to a passwordless root account. Even if you set a password for root and all users, you can't give a password to the `node` user. Our internal networking protocol is based on HTTP which opens you up to the world of web/javascript-based attacks.

**Comment by jseldess** [comment]
In the meantime, virtually all of our deployment tutorials, local and distributed, default to secure and use stronger language to raise alarms about insecure. Closing this.
