### ISSUE TITLE
Remove `CREATE TABLE` statement from sample apps

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1215]
The "Build a <Language> App with CockroachDB" (e.g. [Node.js](https://www.cockroachlabs.com/docs/build-a-nodejs-app-with-cockroachdb.html)) code samples include a `CREATE TABLE IF EXISTS` statement, which isn't a realistic code sample because you wouldn't attempt to create a table in every insert.

I recommend moving the `CREATE TABLE` statement into the "Create a database and grant privileges" step instead.

**Comment by jseldess** [comment]
If we do this, we'll need to rethink the ORM samples as well, e.g., https://www.cockroachlabs.com/docs/build-a-python-app-with-cockroachdb-sqlalchemy.html#step-5-run-the-python-code.

**Comment by sploiselle** [comment]
@cuongdo Would you suggest changing the structure of the ORM code samples (which include creating the table in the code, as opposed to the SQL shell) if we do the work mentioned at the root of this issue on the non-ORM code samples?

**Comment by cuongdo** [comment]
I would not suggest changing the structure of ORM code samples. Developers tend to want to offload responsibilities to the ORM. Part of that is creating tables that match the corresponding model defined through the ORM.

Also, I don't understand the original issue. For very simple apps, it makes sense to `CREATE TABLE IF EXISTS` before using that table.

**Comment by sploiselle** [comment]
The idea behind moving `CREATE TABLE IF EXISTS` out of the code sample is that a typical backend doesn't run the `CREATE TABLE` statement repeatedly, so without it, the code sample becomes a more useful template for developers (without sacrificing its quality as a one-and-done demo).

**Comment by benesch** [comment]
It actually seems reasonable to me to recommend manual database creation but automatic table creation (i.e., the way it is now in the docs). Like @cuongdo said, ORMs will often manage tables for you, and even applications that don't use an ORM often do something like the following

```js
main() {
    settings = ReadSettings("config.yml");
    RunDatabaseMigrations({db: settings.database});
    http.Serve(func (req, res) {
        db.Query(`INSERT INTO posts VALUES($, $)`, req.text, req.authorId)
        // ...
   })
}
```

where `RunDatabaseMigrations` runs a bunch of `CREATE TABLE IF NOT EXISTS` and `ALTER TABLE` commands to ensure the database is in the right state. I guess my point is one-shot scripts like we currently showcase in the docs are strange beasts because run one `INSERT` query and quit. Many real applications *will* run `CREATE TABLE IF NOT EXISTS`... but then run hundreds or thousands of SQL queries in response to user requests. 

I will note, though, that each language's "basic statements" example *includes* the `CREATE TABLE IF NOT EXISTS` but the "transaction (with retry logic)" example does not. There's an implicit required order here that's not called out. I think they should either both run `CREATE TABLE IF NOT EXISTS`, or that should be pulled out into the "create a database and grant privileges" step.

**Comment by jseldess** [comment]
Yeah, these code samples aren't meant to be realistic. They're just overly simplistic demonstrations of drive/ORM usage. Given that, and since it's not uncommon to let the ORM handle table creation, I suggest we leave `CREATE TABLE` where it is for now.

But @benesch has a good point about the implicit sequence of the basic and transaction samples. We haven't gotten complaints about this yet, but we should clarify regardless. @benesch, a third option, which I'd prefer, would be to just make the sequence more explicit. That work for you?

**Comment by benesch** [comment]
Yeah, of course! Totally works for me.
