### ISSUE TITLE
CockroachDB Cloud Production Checklist should link to transaction retry doc

### ISSUE THREAD

**Issue by theodore-hyman** [cockroachdb/docs#12179]
Hello,

This production checklist for CockroachCloud looks fantastic, great updates have been made here. 

https://www.cockroachlabs.com/docs/cockroachcloud/production-checklist.html

I have a request for this section "Keeping connections current" 

Here is what it says today:

> Keeping connections current

> After an application establishes a connection to CockroachDB Cloud, those connections can occasionally become invalid. This could be due to changes in the cluster topography, rolling upgrades and restarts, network disruptions, or cloud infrastructure unavailability.

> Make sure connection validation and retry logic is used by your application. Validating and retrying connections is typically handled by the driver, framework, or the connection pool used by an application. For guidance on connection pool sizing and connection validation, see Use Connection Pools.

Here is my suggestion for modification:

 Transaction Retries [change of title from "Keeping connections current"] 

After an application establishes a connection to CockroachDB Cloud, those connections can occasionally become invalid. This could be due to changes in the cluster topography, rolling upgrades and restarts, network disruptions, or cloud infrastructure unavailability. Another possible cause of a connection retry would be transaction contention. When several transactions are trying to modify the same underlying data concurrently, they may experience contention that leads to transaction retries. 

In order to avoid failures in production, your application should be engineered to handle transaction retries using client-side retry handling. Retrying connections is typically handled by the driver, framework, or application logic. For more information on transaction retries, see here: https://www.cockroachlabs.com/docs/v21.1/transactions#client-side-intervention

**Comment by ianjevans** [comment]
I don't think I understand your assertion that from CRDB's perspective a transaction timeout is equivalent to a network connection timeout.

A transaction retry error doesn't invalidate the network connection, it rolls back the attempted transaction, leaving the cluster in a state where it is guaranteed to be safe to retry.

A network connection error is entirely different. The application client doesn't know if the attempted operation succeeded or not. The underlying transaction could well have succeeded at the same time the client lost its network connection. Retrying the operation on network connection errors may not be what you want. CRDB can't tell if the operation is idempotent.

Which is to say, the application should behave differently when encountering transaction retry errors and network connection errors. If your application uses e.g. a connection pool, the application may not even know if the connection was re-established between the pool and the cluster due to a timeout.

**Comment by theodore-hyman** [comment]
Ian, thank you for the response here. I have hit issues with multiple customers on transaction retries but clearly I have a poor understanding of network connection errors on CRDB. I now see why the docs says "validating". I also see that we reference that in the connection pooling docs.

I was asked to make a github issue for my docs request and I may have gotten a bit carried away. Let me be very straightforward. My request is that we put a link to this page: https://www.cockroachlabs.com/docs/v21.1/transactions#client-side-intervention

In this page somewhere:

https://www.cockroachlabs.com/docs/cockroachcloud/production-checklist.html

You can completely ignore my hastily made draft and arrange the content/wording as you see fit as the docs expert. I just really want that link to be more front and center. If CRDB Dedicated customers have not implemented transaction retries, this can easily become an escalation when they hit the issue in prod, and we on the csm team want to be proactive about giving customers guidance on this topic, so we don't have a fire drill every time this happens. 

Thank you
Theodore

**Comment by ianjevans** [comment]
I completely agree we should link to the transaction retry docs from the Dedicated production checklist.

Editing the issue title.

**Comment by ianjevans** [comment]
Fixed in #12193.
