### ISSUE TITLE
Kubernetes: how to access the SQL client on individual nodes 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1265]
From Gitter:

Hi I am exploring cockroachDB on Kubernetes cluster. I am using the standard yaml published by Cockroach Labs.
I am trying to gain access to the cockroach sql CLI on individual nodes to validate the replication. I have tried the following:

```
kubectl exec -ti cockroachdb-01 bash followed by cockroachdb sql
kubectl port-forward cockroachdb-01 26257
```

both yield an error as follows:

```
E0411 11:37:51.252921    1481 portforward.go:332] an error occurred forwarding 9999 -> 26257: error forwarding port 26257 to pod cockroachdb-1_default, uid : exit status 1: 2017/04/11      03:37:51 socat[7068] E connect(6, AF=2 127.0.0.1:26257, 16): Connection refused
 Error: unable to connect or connection lost.
     Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).
     dial tcp [::1]:26257: getsockopt: connection refused
Failed running "sql"
```

I tried to tail the logs but nothing stands out.
Any help would be appreciated

Cyber Jar @cyberjar09_twitter 00:39
thanks we got the answer. 

```
kubectl run cockroachdb -it --image=cockroachdb/cockroach --rm -- sql --host<pod IP>
```

**Comment by a-robinson** [comment]
Additional context from gitter:

In case you're curious the reason that those don't work is:

1. The cockroach process within the container is listening on fully-qualified hostname, not on localhost, so you have to pass `--host=$(hostname -f)` to the cockroach sql command
2. Again, the process's main serving port is listening on the container's hostname rather than on localhost, and port-forward only works when forwarding a port that's listening on localhost. Port forwarding to the http port (8080) works because we tell the process to listen on all interfaces for its http port (https://github.com/cockroachdb/cockroach/blob/master/cloud/kubernetes/cockroachdb-statefulset.yaml#L159)

The easiest way to get a SQL shell against a specific cockroachdb node running in kubernetes (assuming it's been created using our provided config file) is:

```console
$ kubectl exec -ti cockroachdb-0 bash
$ ./cockroach sql --host=$(hostname -f)
```
