### ISSUE TITLE
security: usability improvements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1276]
RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/certificate_rotation.md
PRs:
- https://github.com/cockroachdb/cockroach/pull/14703

**Comment by mberhault** [comment]
The big one is https://github.com/cockroachdb/cockroach/pull/14703, the previous one introduced the certificate manager but did not use it yet.

This one will introduce quite a few changes:
- `--certs-dir [default=${HOME}/.cockroach-certs]` on all commands that need certs. Contains:
  - CA certificate: `ca.crt`
  - node certificate: `node.crt` (only needed for nodes)
  - node key: `node.key` (only needed for nodes)
  - client certificate: `client.<username>.crt` (needed for clients commands)
  - client key: `client.<key>.key` (needed for client commands)
- `cockroach cert` commands now take `--ca-key` and `--certs-dir` and generate the certs inside `--certs-dir`. The help commands detail what happens when some files already exist (eg: is `ca.crt` already exists, `cockroach cert create-ca` prepends the new CA certificate in the file)

The `--ca-cert`, `--cert`, and `--key` flags will still be supported for the `start` command only, but will print a warning to use `--certs-dir` instead. These will probably be removed entirely for 1.0.

Certificate rotation is not there yet, but will be done by issuing a `SIGHUP` signal to the cockroach nodes. Other methods will come later.

**Comment by jseldess** [comment]
Thanks, @mberhault. Will cert rotation be in place for v1? I think I'll rename this issue.

**Comment by mberhault** [comment]
yup. but the "reload certs" will be the easy part to document. The changes to the certs flags are the big ones.

**Comment by mberhault** [comment]
oh. I forgot to mention, https://github.com/cockroachdb/cockroach/pull/14703 is also making `--insecure` false by default and independent of `--host` or the cert flags. So `cockroach start` without certs in `~/.cockroach-certs` will fail.

**Comment by mberhault** [comment]
The PR is merged. I've posted a forum PSA detailing the major changes: https://forum.cockroachlabs.com/t/psa-insecure-is-now-false-by-default-certs-dir-replaces-old-certificate-flags/568

**Comment by mberhault** [comment]
@jseldess, @sploiselle: I can do a first pass at the docs, but I'll definitely need your help here. Ideally we'd like to get this out for this week's beta.

**Comment by sploiselle** [comment]
If you can lay any kind of groundwork, Marc, that would be wonderful.

**Comment by jseldess** [comment]
Docs are up-to-date. Closing this and opening a separate issue to add docs on cert rotation.
