### ISSUE TITLE
managing clock drift - commonly asked question

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1303]
In response to the quote from Jepsen: Like Spanner, Cockroach's correctness depends on the strength of its clocks. If any node drifts beyond the clock-offset threshold (by default, 250 ms), all guarantees are basically out the window.

Default of clock-offset threshold is set at 500ms. Nodes will spontaneously abort when they detect a drift half of the configured value. The guarantee here is serialized consistency - if you drift beyond that, you can potentially get stale reads and write skews. However, with NTP set up, you should not be experiencing clock drifts beyond 500ms. We are constantly measuring clock offsets and have more than a generous default max offset. You would need to have a node's clock jump suddenly by more than 500ms, and even then, you would be facing 3s window of vulnerability. NTP keeps your clock offsets within tens of ms.

In the worst case if it actually happened, reads could see stale data. Writes are mostly unaffected by clocks, except to the extent that you may write data derived from stale reads.

**Comment by bdarnell** [comment]
#1305 has another version of this answer.

**Comment by knz** [comment]
FIXME: clarify "reads could see stale data"

Also as outline in #1305 highlight that a small amount of clock drift is expected and will be safely handled.

**Comment by a6802739** [comment]
@dianasaur323  @bdarnell  so why this `you can potentially get stale reads and write skews` happen?

**Comment by bdarnell** [comment]
If one node with a slow clock holds the lease for a range, it could expire and a node with a fast clock could acquire it and start making writes while the slow node still thinks its lease is valid and continues to serve reads.

**Comment by a6802739** [comment]
@bdarnell, when a node with a fast clock acquired the lease, why the the slow node still thinks its lease is valid?

And how does `write skews` happen?

**Comment by bdarnell** [comment]
Node A has a slow clock, and it has a lease that expires at 12:00:00. It believes the current time is 11:59:59, so its lease is still valid. Node B has a fast clock, so it believes that the current time is 12:00:01 and node A's lease is expired. Node B will try to acquire a lease (and if node C also has a fast clock, this lease will be granted). Node A will keep serving reads even as nodes B and C are serving new writes. 

Write skew would happen if you had two transactions that each did a read then a write, and their reads saw inconsistent results because of the above issue.

**Comment by a6802739** [comment]
@bdarnell, each node's clock is different, so the situation will always happen, right? So what's the relationship between the `max clock offset` and `stale read`?

**Comment by bdarnell** [comment]
The clocks are always different, but this is why we have `MaxOffset`. The new lease for node B cannot start until `leaseA.Expiration + MaxOffset`, so you cannot have two nodes that both believe they have the lease unless clock offsets exceed `MaxOffset`. 

Any reads served by node A in the example above could be "stale" because they would not know about writes performed by node B.

Node A could *propose* a write request, but it cannot *commit* a write request without getting votes from at least one of node B or C, but they've already voted to give node B the lease.

**Comment by a6802739** [comment]
@bdarnell  why the node A couldn't commit a write request, if the replica in Node A is the raft leader, it   could commit the write request, right?

**Comment by bdarnell** [comment]
Raft leaders can only write if their log is up to date. If their log is out of date, they must have lost their leadership. The only way you can have conflicting leases is if node B has a lease entry in its log that node A does not.

**Comment by a6802739** [comment]
So if Node B have a new lease entry, Node A have no chance to be the raft leader?

**Comment by bdarnell** [comment]
Yeah. Node A may still be in the "leader" state, but it can't successfully propose anything to the raft log.

**Comment by a6802739** [comment]
@bdarnell , Hmm, I could understand that. But when we will update the gateway's leaseholder cache, Because the Node A's lease is still there.

**Comment by bdarnell** [comment]
As long as node A is communicating with nodes B and C, it will find out about node B's lease soon and start returning NotLeaseHolderErrors. In certain partition scenarios it may take a while for this to happen, but then the gateway will timeout (in DistSender) and try B and C anyway.

**Comment by a6802739** [comment]
Hmm, for write request, node A will communicate with nodes B and C when it want to commit the raft log, right? So for this write request, it will return NotLeaseHolderErrors. And for subsequent request, they will come to the new leaseholder(B or C).

**Comment by bdarnell** [comment]
NotLeaseHolderError is used in the KV API, not raft messages. Node A will send MsgApp raft messages to B and C to try and commit the raft log. Nodes B and C will drop these messages (because they will be from an old term), and node B will send its own MsgApp messages to node A. NotLeaseHolderError is not a factor at this level.

**Comment by a6802739** [comment]
So when the `NotLeaseHolderErrors` return?

**Comment by bdarnell** [comment]
They are returned when a KV command is sent to a node that doesn't have the lease, or for pending commands when a node that formerly had the lease learns that it no longer has it.

**Comment by bdarnell** [comment]
This question was asked again on IRC. We need to get a good canonical reference for this in the FAQ and/or other places where we talk about clock offsets. 

```
14:11:21]  <smw>	bdarnell, anyways, I recommend expanding a bit on that page I linked to https://www.cockroachlabs.com/docs/recommended-production-settings.html
[14:12:06]  <smw>	bdarnell, saying something inconsistent can happen is scary. Especially when you don't go into detail of the exact things that need to happen and the exact inconsistencies possible
```
