### ISSUE TITLE
Publish sha256sum for all cockroachdb binaries

### ISSUE THREAD

**Issue by data-matt** [cockroachdb/docs#13404]
Matthew Gardner (data-matt) commented:

Along side our binaries, we should publish a checksum for the binary

e.g 
On this page: https://www.cockroachlabs.com/docs/releases/v21.1.html#v21-1-16

Not only provide the binary:
https://binaries.cockroachdb.com/cockroach-v21.1.16.linux-amd64.tgz
But also link to the sha:
https://binaries.cockroachdb.com/cockroach-v21.1.16.linux-amd64.tgz.sha256

gz#11879

Jira Issue: DOC-3061

**Comment by jseldess** [comment]
Ideally, this would be part of the release note generation script. 

@data-matt, can you give me an example of what this would look like for a sample release and where the information is available?

**Comment by data-matt** [comment]
@jseldess , I think we are considering starting with a page that literally contains only the sha256sum for all binaries

We need to go through multiple stages I think.

Stage 1: Page with all sha256sum against binaries link and version in a table

e.g:

Table:
crdb version : download link : sha256sum
21.1.16,https://binaries.cockroachdb.com/cockroach-v21.1.16.linux-amd64.tgz,83e8a211d677f2f6a1547973cceb2a40604a0a89e2450e8e0f1fc05a31fa065f

Stage 2: Page with all sha256sum with the binaries at the same endpoint https://binaries.cockroachdb.com/

Stage 3: Sign the binaries 

@rail will need to chime in here.

**Comment by rail** [comment]
We should probably generate the checksums as a part of https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/publish-provisional-artifacts/main.go to simplify this process.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [DOC-3061](https://cockroachlabs.atlassian.net/browse/DOC-3061) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/docs-13404`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
