### ISSUE TITLE
Restarting a local cluster

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1403]
Our Start a Local Cluster tutorial shows how to stop a three-node local cluster but not how to restart it. Users tend to like to do that, but when they following the initial start steps, they can get tripped up by the fact that the cluster doesn't respond until 2 of the 3 nodes are back online (a quorum). 

See https://github.com/cockroachdb/cockroach/issues/15889.

**Comment by a-robinson** [comment]
Actually, worse than that, our page on securing a cluster tells you to stop your locally-started 3 node cluster, then secure, then bring it back up. The instructions it gives for bringing it back up won't work since it has you do it one node at a time in a single terminal using the `--background` flag:

https://www.cockroachlabs.com/docs/secure-a-cluster.html

**Comment by jseldess** [comment]
Yikes, you're right. After my talk today, I'll do a quick fix on the secure page to use distinct terminals per node. Then we can revisit the overall approach.
