### ISSUE TITLE
Feedback: CockroachDB in Comparison

### ISSUE THREAD

**Issue by guyklages** [cockroachdb/docs#15115]
Exalate commented:

Page: https://cockroachlabs.com/docs/v22.1/cockroachdb-in-comparison.html

## What is the reason for your feedback?

[x] Missing the information I need

[ ] Too complicated

[ ] Out of date

[ ] Something is broken

[ ] Other

## Additional details
The comparison is great! I thought Couchbase is better than MongoDB, no? 

Jira Issue: DOC-5676

**Comment by mikeCRL** [comment]
Hi @guyklages! We're glad you like it, and appreciate the thoughtful suggestion. We do plan to add Couchbase in the future, though it's not slated to happen anytime soon. Our current priority is to ensure we stay up-to-date on the improvements made to each of the already listed database products so that this resource remains accurate.
