### ISSUE TITLE
Enhance CockroachDB Dedicated shutdown docs with terminationGracePeriodSeconds and connection pool recommendations

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/docs#15191]
We've recently added docs on [node shutdown](https://www.cockroachlabs.com/docs/stable/node-shutdown.html), which are extremely helpful.

There are a few additional and very important considerations that we should communicate for CockroachDB Dedicated. They are related to the `terminationGracePeriodSeconds` setting in Kubernetes. There are [external docs](https://cloud.google.com/blog/products/containers-kubernetes/kubernetes-best-practices-terminating-with-grace) for this, but the TLDR is that if a k8s pod takes longer than `terminationGracePeriodSeconds` to shutdown after receiving SIGTERM, then it will be forcefully killed with SIGKILL. Here are some specific things users should know:

1. We currently set `terminationGracePeriodSeconds` to `300` (5 minutes) according to @1lann. It's hardcoded right now.
2. The **sum** of all the `server.shutdown.*` cluster settings should not exceed `terminationGracePeriodSeconds`. Otherwise, non-graceful termination is very likely.
3. As a corollary, this means that users should set their **client-side connection pool max lifetime** to something less than `server.shutdown.connection_wait`. (Refer to [this part](https://www.cockroachlabs.com/docs/stable/node-shutdown.html#server-shutdown-connection_wait) of our existing docs.) They also could design their app to be resilient to unexpected connection loss, but we can't really give them specific advice on how to achieve that.

Refer to this [internal slack thread](https://cockroachlabs.slack.com/archives/CJX8V9SJ2/p1663958591466899) if more context is needed for the docs.

Longer term, it seems like it would be good if we increased our `terminationGracePeriodSeconds` setting, but @1lann says that is a non-trivial change to make.

ccing @taroface as the original author of https://www.cockroachlabs.com/docs/stable/node-shutdown.html and @mdlinville since the Cloud-specific docs might be your area.

**Comment by vroldanbet** [comment]
Excuse the drive-by 👋👋Im cognizant this may not be the right repo to share this, but captures nicely a fundamental problematic with dedicated clusters lack of user-triggered node drain. Happy to move the conversation elsewhere!

The documentation in the OpenSource CRDB states the default drain timeout is 10 minutes, see https://www.cockroachlabs.com/docs/stable/node-shutdown.html

>When draining manually, if the above steps have not completed after 10 minutes by default, node draining will stop and must be restarted to continue.

This value is in contrast with the 5 minutes from the dedicated clusters. This turned out to be a source of incidents for us.

Getting applications to gracefully handle node drain require some careful tunning. Unfortunately dedicated does not offer a "push this button to drain a node", and so developers have no means to test this process other than resourcing to OpenSource CRDB. That was the recommendation we received.

Using OpenSource to simulate a dedicated cluster  is insufficient because of little details like the node drain timeout:
- CRDB OpenSource default is 10 minutes
- Dedicated is 5m (which I discovered recently, the hard way)
- 💥

So while more exhaustive docs around node draining is necessary, improper handling this procedure will continue to happen for as long as the defaults across offerings differ. And that is expected to stay that way (each execution environment needs its own tunning!) and thus a means to execute node drain simulation is needed to give the confidence to devs on their app configuration.

Thoughts?

**Comment by rafiss** [comment]
https://github.com/cockroachdb/docs/pull/15301 was merged last month, so this is now documented better at https://www.cockroachlabs.com/docs/v22.2/node-shutdown.html#termination-grace-period-on-kubernetes

Specifically:
> CockroachDB dedicated clusters have a termination grace period of 300 seconds (5 minutes). This setting is not configurable.

Those docs will soon become the new "stable" docs. It's also a bit more clear about how the default for the CockroachDB Public Operator is also 5 minutes.
