### ISSUE TITLE
Move /generate to cockroach repo

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1546]
If we move all the sql railroad generation files into cockroach, we'll be able to version the generation file alongside the sql grammer. This isn't a huge problem now but will probably become more of a problem. 

cc: @mjibson and @dt

**Comment by jseldess** [comment]
@benesch, @dt, @mjibson, any updates on when we might be able to get to this?

**Comment by benesch** [comment]
It's halfway done! https://github.com/cockroachdb/cockroach/pull/17024

Are the diagrams/functions/operations out of date?

**Comment by dt** [comment]
@mjibson you think you'll move the diagram generator? I'm happy take a stab at it, but I'm less familiar with it (I don't have the jar, for example)

**Comment by mjibson** [comment]
I won't be able to work on this until after the feature freeze. There's no need for the jar: it'll use the web service if the jar isn't present. I'm happy to do the work later. If it's important for it to be done sooner, it shouldn't be too hard. The only thing to note is that we have a copy of the yacc parser already in pkg/internal/yacc, but otherwise everything just gets copied, and the relative directory for the output needs fixing.

**Comment by jseldess** [comment]
@benesch, the 1.0 sql diagrams and functions docs should be correct, but it's of course possible that somethings are behind.

**Comment by jseldess** [comment]
Related to https://github.com/cockroachdb/cockroach/issues/18644

**Comment by jseldess** [comment]
Closed by https://github.com/cockroachdb/docs/pull/2355.
