### ISSUE TITLE
Incorporate details from blog post into SQLAlchemy Build a Python tutorial

### ISSUE THREAD

**Issue by keiranmraine** [cockroachdb/docs#1608]
Re: [Build a Python App with CockroachDB](https://cockroachlabs.com/docs//build-a-python-app-with-cockroachdb-sqlalchemy.html)

## Issue Description

The docs here for SQLAlchemy conflict with those in the blog post [Building an Application With CockroachDB and SQLAlchemy](https://www.cockroachlabs.com/blog/building-application-cockroachdb-sqlalchemy-2/)

## Suggested Resolution 

Clarify or resolve discrepancy between docs.  Also could do with some information as to the interaction with flask_sqlalchemy as this indicates that all db writes should be through the `session` model.  How does this interact with `run_transaction`?

**Comment by jseldess** [comment]
Thanks for filing this, @keiranmraine. Would you mind added some detail about the discrepancies you see?

Also, looping in @bdarnell, who might be able to speak the your question about `run_transaction`.

**Comment by bdarnell** [comment]
`cockroachdb.sqlalchemy.run_transaction` can work with either a SQLAlchemy `Engine`, `Connection` (low-level APIs) or `sessionmaker` (high-level API). The usage of this function with a `session` can be seen in the blog post (which is currently more complete in this respect than the page in the docs). Note that you only have a `session` object inside the `run_transaction` callback.

**Comment by rmloveland** [comment]
I believe the discrepancies between the [blog post](https://www.cockroachlabs.com/blog/building-application-cockroachdb-sqlalchemy-2/) and the [SQLAlchemy docs](https://www.cockroachlabs.com/docs/dev/build-a-python-app-with-cockroachdb-sqlalchemy.html) have been largely handled in [this recent PR](https://github.com/cockroachdb/docs/pull/4142), which updates the SQLAlchemy example to use transaction retries properly using the `cockroachdb.sqlalchemy.run_transaction` API Ben described here and in the blog post.

@keiranmraine , I'm closing this issue because I think it's addressed, but please comment or re-open if you disagree
