### ISSUE TITLE
Orchestrate CockroachDB with Docker Swarm can't run SQL client

### ISSUE THREAD

**Issue by drnybble** [cockroachdb/docs#1640]
Re: [Orchestrate CockroachDB with Docker Swarm](https://cockroachlabs.com/docs//orchestrate-cockroachdb-with-docker-swarm.html)

## Issue Description
I have followed the steps and appear to have a functioning cluster. I did have some trouble until I time synced my three nodes, you might want to add that to your steps.

I try to start the SQL client:

root@csx20064:~/cockroachdb# docker exec -it f0b341479625 ./cockroach sql --certs-dir=/run/secrets
Error: pq: user root must use certificate authentication instead of password authentication
Failed running "sql"

Suggestions on what I am doing wrong?

**Comment by jseldess** [comment]
Thanks for the report, @drnybble. I'll be sure to add instructions about clock synchronization. As for why you're getting that error, I'm not sure. Going to loop in a dev who might be able to help.

@a-robinson, any ideas?

**Comment by a-robinson** [comment]
Hmm, I'm not sure why you'd be getting this error assuming you followed the certs/secrets instructions from the docs.

cc @mberhault @asubiotto since they know more about this code than me. Shouldn't the `cockroach sql` command either send along the certs with its initial pgwire connection or error out if certs-dir was provided but didn't have valid certs to send?

**Comment by mberhault** [comment]
ah. oops. It seems the sql command doesn't return errors if certificates for the requested user are not present. This is because we take that as a hint that we should prompt for a password.
However, the password prompt is skipped if the requested user is `root`. This means that we don't fail is client certificates for `root` are not present.

The docs mention to create client certificates, but it's not very obvious. #1617 suggests making client certificates its own step.

We should fix the CLI as well. The simple fix is to propagate whether we prompted for the password. If not, we should throw an error if now client certificates are found.

**Comment by a-robinson** [comment]
Thanks for explaining. Could we fall back to using node certs if the client is trying to connect as root?

**Comment by mberhault** [comment]
Nope, not certs are explicitly disallowed on non-internal endpoints.

**Comment by mberhault** [comment]
uh. wait, I guess it's not. Still, we should never revert to `node` for user operations.

**Comment by a-robinson** [comment]
Is there a security reason why not? If the user has access to the node cert, it's not as if they couldn't already access (or modify) any of the data in the cluster.

**Comment by a-robinson** [comment]
s/node cert/node key/

**Comment by mberhault** [comment]
`node` is a bit special, it's allowed to impersonate anyone, skips some checks, is a blacklisted username, etc... I honestly haven't tried, but I expect trouble using the node cert when trying to come in as root. We really should disable it on non-internal calls (we just have to be careful about sql call issued by nodes themselves).

Beyond that, it's just a bad habit. If someone took the time to setup certs and distribute them, proper client certs is the way to go.

**Comment by drnybble** [comment]
The docs state: 

Because we are starting the SQL client in the same container as a node, we can use the node certificate and key to execute the cockroach sql command securely.

**Comment by jseldess** [comment]
@mberhault, @a-robinson, I'm trying to update these docs now. But I haven't run through these steps in a while, and now I'm having issues. On GCE, I have 3 instances. Installed Docker manually on each following [these instructions](https://docs.docker.com/engine/installation/linux/docker-ce/debian/). No problems starting the swarm. But when I get to generating certs, I'm not able to associate certs to secrets locally for some reason:

```
~$ mkdir certs
~$ mkdir my-safe-directory
~$ cockroach cert create-ca \
> --certs-dir=certs \
> --ca-key=my-safe-directory/ca.key
~$ ls certs
ca.crt
~$ docker secret create ca-crt certs/ca.crt
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
```

I suspect that, when these instructions were initially written, I didn't manually start the swarm on each server but rather somehow initialized the cloud swarm from my local computer and so didn't get this problem. So some questions:

1. Without my local machine being a part of the swarm, can I still generate secrets locally and get them to the swarm? 
2. If yes, how?
3. If no, are there alternatives, e.g., creating the secrets on the manager node (moving the ca.key elsewhere in the end)?
   - Or should we instead revise the instructions to make sure users manage the swarm from a local machine?

**Comment by a-robinson** [comment]
I actually think that when the instructions were written you were doing everything while SSH'ed to one of the swarm nodes in GCE.

To talk to the swarm remotely, you'd have to [set up Docker certs of your own](https://stackoverflow.com/questions/44056501/how-can-i-remotely-connect-to-docker-swarm) in order to make exposing Docker to the internet even remotely safe. The easier version of this that I think would still work would be to talk to the Docker daemon's insecure port (2375) via SSH port forwarding.

**Comment by jseldess** [comment]
Thanks, @a-robinson. It's way early there, but when you're back online and have time, would appreciate further help. I'm not sure which approach we want to recommend, and in either case, I'll need a bit of help figuring it out.

**Comment by a-robinson** [comment]
Opening up SSH tunnels is easy to do on GCE, but I'm not sure we want to have to instruct people how to do so on whatever infrastructure they're using.

As for setting up certs for Docker Swarm itself, we could link to [Docker's docs](https://docs.docker.com/engine/security/https/), but definitely shouldn't take responsibility for documenting/troubleshooting it.

I think that for simplicity we should stick to managing the swarm from the swarm manager node (i.e. the VM where you run `docker swarm init`. Folks who've set up their own cluster differently can run the commands from wherever they normally manage their cluster.
