### ISSUE TITLE
Alternative to cockroach dump and EXPORT CSV

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1674]
Exalate commented:

Re: [SQL Dump (Export)](https://cockroachlabs.com/docs//v1.0/sql-dump.html)

## Issue Description

Cockroach dump is a good way to get a dump of the schema.  For a dump of data, there are other performant methods such as below;

psql -t -F $'\t' --no-align -c "select * from tablename" > file.csv

cockroach sql --insecure --format tsv -e "select * from tablename" > file.csv

The CVS file can be loaded using the "copy tablename from stdin" commands.

## Suggested Resolution 

Does it make sense to document the other methods?

**Comment by sploiselle** [comment]
@robert-s-lee What are the advantages of these other approaches?

**Comment by robert-s-lee** [comment]
About 5x faster than the dump command.  They are also portable to that CSV can be used to hydrate other databases.

**Comment by petermattis** [comment]
Using a `select * from table` should not be noticeably faster than using `dump`. Internally, `dump` is essentially doing `select * from table as of system time x`. Seems like there is a (performance) bug here.

Cc @mjibson

**Comment by petermattis** [comment]
Also, note that `select * from table` will currently not work on very large tables because we buffer the entire result on the server. The `dump` command does not have this limitation.

**Comment by mjibson** [comment]
I'll try to track down the performance differences.

**Comment by mjibson** [comment]
I tested changing the dump implementation to use a single `select *` and its performance didn't change. But I was able to reproduce the performance increase when running `cockroach sql --insecure --format tsv -e "select * from tablename"`, and it is all from the work to format strings as SQL-safe entities. That is, the extra work is properly escaping datums so they are valid SQL, instead of just valid CSV.

I have no objection to documenting the other options and injesting them with psql via the copy protocol. Until `cockroach sql` supports copy, it doesn't make sense to have dump produce a copy file since dump is designed to be able to re-import what it creates.

**Comment by jseldess** [comment]
These docs will be needed as a "core" alternative to the enterprise `EXPORT` csv feature.

**Comment by gajen0981** [comment]
hey all -- I am using cockroach dump for enterprise DB with large data volume and does this `stream` the backup data to the file system or `buffer`. I believe its stream but I wanted to make sure. Thanks so much!!

**Comment by mjibson** [comment]
Dump streams the data to its output, yes.
