### ISSUE TITLE
Create Security Certificates workflow adjustments

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1678]
Re: [Create Security Certificates](https://cockroachlabs.com/docs//v1.0/create-security-certificates.html)

## Issue Description

overwriting a node certificate then uploading them to another nodes is somewhat confusing in terms of workflow. 

## Suggested Resolution 

in the CREATE THE CA CERTIFICATE AND KEY PAIR:
create and then copy the following to all of the nodes first
safe-directory/ca.key 
certs/client.root.crt
certs/client.root.key
certs/ca.crt

in CREATE THE CERTIFICATE AND KEY PAIRS FOR NODES:
replace 5 steps with the single step below

cockroach cert create-node \
node2.example.com \
node2.another-example.com \
--certs-dir=certs \
--ca-key=my-safe-directory/ca.key \

**Comment by mberhault** [comment]
The ca key shouldn't be copied to the nodes, hence the `safe-directory`.
Rather than overwriting the certificates for each node, we could delete the `certs` directory after copying it.

**Comment by jseldess** [comment]
@robert-s-lee, @mberhault, I just opened a PR and assigned you both as reviewers. It didn't make sense to remove the entire `certs` directory after uploading to each node, since that would require regenerating the ca cert and client certs and keys, all of which are in the `certs` directory. Instead, I just removed the specific `node.crt` and `node.key` files before generating certs for a new node. 

I do still mention the `--overwrite` flag in a note. Even though custom to us, it is a convenient option that some users may want to use.
