### ISSUE TITLE
Troubleshooting docs for finding cockroach and admin UI port

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#1692]
If you forget the `cockroach` or Admin UI port, you can use something like the following:

- `ps auxw`
- `netstat -p`
- `lsof`

This should be integrated into [General Troubleshooting](https://www.cockroachlabs.com/docs/stable/general-troubleshooting.html) in lieu of the guidance to restart your nodes.

**Comment by bdarnell** [comment]
In practice, the admin UI port is more likely to be changed than the cockroach port (because 26257 is our unique reserved port, while 8080 is just a port that we (and many others) squat on), so it would also be useful to add a command like `cockroach config admin-url` that would take the same client flags as `cockroach sql` and print the corresponding admin UI url.

Similarly, we could have `cockroach config jdbc-url` to print the connection url in JDBC format, and similar commands for the other stuff printed out by `cockroach start`.

**Comment by rmloveland** [comment]
For anyone else stumbling across this, see also: https://github.com/cockroachdb/cockroach/pull/39483

**Comment by jseldess** [comment]
I *think* one of the easier ways to get this info is with 

```
grep 'node starting' node1/logs/cockroach.log -A 11
```

```
CockroachDB node starting at 2019-09-17 20:04:36.651544 +0000 UTC (took 35.5s)
build:               CCL v19.2.0-alpha.20190805 @ 2019/08/05 11:00:26 (go1.12.5) (go1.12.6)
webui:               http://localhost:8080
sql:                 postgresql://root@localhost:26257?sslmode=disable
RPC client flags:    cockroach <client cmd> --host=localhost:26257 --insecure
logs:                /Users/<username>/node1/logs
temp dir:            /Users/<username>/node1/cockroach-temp242232154
external I/O path:   /Users/<username>/node1/extern
store[0]:            path=/Users/<username>/node1
status:              initialized new cluster
clusterID:           8a681a16-9623-4fc1-a537-77e9255daafd
nodeID:              1
```

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
