### ISSUE TITLE
Running CockroachDB in Docker across multiple hosts (Docker Swarm)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#185]
Our [Start a Cluster]() works fine within a single container. We need to figure out best practices for running a cluster across containers, though. 

Riak provides a script: https://hub.docker.com/r/hectcastro/riak/

@mberhault 

Also, @uptimedba, suspecting you might have some thoughts/ideas here.

**Comment by uptimeDBA** [comment]
I have plans to look at this although I'm not a Docker expert by any means and it's 3rd on my list after VirtualBox and AWS using EC2 and ELB. 
I saw this today which might provide some ideas. [HA MariaDB and Docker Swarm in under 15 minutes](http://18pct.com/zero-to-mariadb-cluster-in-docker-swarm-in-15-minutes-part-1/)

**Comment by jseldess** [comment]
Almost done updating `start-a-local-cluster.md` to cover running cockroach across multiple Docker containers on a **single** host. This issue, then, will focus on running cockroach in Docker across **multiple** host, similar to our `manual-deployment.md` process. It'll likely involve Docker Swarm.

**Comment by joeblew99** [comment]
@jseidess

This is exactly the 2 things I need.
I am using docker 1.12 rc4, with the new docker service scaling.
 I am using x86 and arm too just to be a masochistic 


Can we discuss / test together

**Comment by jseldess** [comment]
@joeblew99, sorry for the delay. We're definitely planning start on this soon, but we were thinking of focusing on Docker Swarm. Would that be helpful as well?

**Comment by a-robinson** [comment]
I have some rough steps that get the job done in a matter of 4 commands (with a few more commands if you want non-local disk). I'd be very open to feedback, though, as I may have missed something along the way that makes it fragile or that could be done better. Handing off to @jseldess to take a look and see what needs polishing:

First, follow Docker's instructions for creating a Swarm based on your desired environment: https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/

Once you have your swarm:

```console
root@a1:/home/alex# docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
0bdkxk0ft6enrqcr9e8xhcy48 *  a1        Ready   Active        Leader
2kpk8h0cucfqls3dymed9zwkn    a2        Ready   Active
drmw35re1hm2nh2r3kjbj78kd    a3        Ready   Active
```

Create an overlay network so that your containers can talk to each other (or use your own existing overlay network):

```console
root@a1:/home/alex# docker network create --driver overlay cockroachdb
bhzwp6hf3d36otj487528t00d
root@a1:/home/alex# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
dbbbb9163bce        bridge              bridge              local
bhzwp6hf3d36        cockroachdb         overlay             swarm
12930e17e39e        docker_gwbridge     bridge              local
5d8453ffa53c        host                host                local
0a7y6mo0uonw        ingress             overlay             swarm
b32d2b20853a        none                null                local
```

Because Swarm doesn't have a construct that allows you to create a number of replicas that each maintain their own network identity and disk over time, we have to create a separate `service` for each CockroachDB node. The service will allow each node to maintain a stable identity across recreations on different nodes.

As for storage, you can choose to just use local disk and rely on CockroachDB's built-in replication to handle failures, or you can use network-mounted volumes to ensure that no storage is lost even when a node fails. If you don't plan on removing the machines from your cluster in quick succession (or you're just not trusting your cluster with any production data), it'd be reasonable to run using local disk. If you frequently replace your machines such that they're recreated with a new disk, however, it's recommended that you use remote storage to ensure persistence. The method using local disk is shown here, with tips about using remote disk in the appendix.

Create the first service that all others will join to:

```console
root@a1:/home/alex# docker service create --replicas 1 --name cockroachdb-0 --network cockroachdb --label app=cockroachdb --mount type=volume,source=cockroachdb-0,target=/cockroach/cockroach-data,volume-driver=local --stop-grace-period 60s cockroachdb/cockroach:latest start --logtostderr --insecure
b5fz6lw477h2rt4unpzzc1h1r
```

There are a few interesting components to the command above:
* We're joining the container to the overlay network we created
* We're mounting a local volume called cockroachdb-0. If it doesn't exist on a given node, it'll be created. If it does exist already, it'll be used. This allows for a container to be restarted on the same node without losing its data.
* We're setting a stop grace period to give CockroachDB enough time to shut down gracefully when possible.

Create the other two services, joining to the first one:

```console
root@a1:/home/alex# docker service create --replicas 1 --name cockroachdb-1 --network cockroachdb --label app=cockroachdb --mount type=volume,source=cockroachdb-1,target=/cockroach/cockroach-data,volume-driver=local --stop-grace-period 60s cockroachdb/cockroach:latest start --logtostderr --insecure --join cockroachdb-0:26257
ezetokd97yoxp3tntqjquywov
root@a1:/home/alex# docker service create --replicas 1 --name cockroachdb-2 --network cockroachdb --label app=cockroachdb --mount type=volume,source=cockroachdb-2,target=/cockroach/cockroach-data,volume-driver=local --stop-grace-period 60s cockroachdb/cockroach:latest start --logtostderr --insecure --join cockroachdb-0:26257
```

Update the first node's arguments so that if it gets restarted for any reason, it'll join the second node rather than trying to create a new cluster, which could lead to data loss:

```console
root@a1:/home/alex# docker service update cockroachdb-0 --args "start --logtostderr --insecure --join cockroachdb-1:26257"
cockroachdb-0
```

On any of the machines that has a running container:

```console
root@a3:/home/alex# docker ps | grep cockroachdb
5abcdec4fb57        cockroachdb/cockroach:latest   "/cockroach/cockroach"   5 minutes ago       Up 5 minutes        8080/tcp, 26257/tcp   cockroachdb-1.1.02x5uftdylgu0fmnq8dtlyss4
root@a3:/home/alex# docker exec -it 5abcdec4fb57 ./cockroach sql
root@:26257> create database foo;
CREATE DATABASE
root@:26257> show databases;
+--------------------+
|      Database      |
+--------------------+
| information_schema |
| foo                |
| system             |
+--------------------+
(3 rows)
root@:26257> create table foo.bar(k string, v string);
CREATE TABLE
root@:26257> insert into foo.bar values ('key', 'val');
INSERT 1
root@:26257> select * from foo.bar;
+-----+-----+
|  k  |  v  |
+-----+-----+
| key | val |
+-----+-----+
(1 row)
```

To verify that the cluster is communicating, you can then try one of the other machines and verify the data is there.

```console
root@a1:/home/alex# docker ps | grep cockroachdb
7a5feedc6c7d        cockroachdb/cockroach:latest   "/cockroach/cockroach"   About a minute ago   Up 47 seconds       8080/tcp, 26257/tcp   cockroachdb-0.1.eznwfm1ypd29cic542pe71xy1
root@a1:/home/alex# docker exec -it 7a5feedc6c7d ./cockroach sql
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257> show databases;
+--------------------+
|      Database      |
+--------------------+
| information_schema |
| foo                |
| system             |
+--------------------+
(3 rows)
root@:26257> select * from foo.bar;
+-----+-----+
|  k  |  v  |
+-----+-----+
| key | val |
+-----+-----+
(1 row)
```

You could take the example further with machine and/or container killing if you'd like.


Appendix:
If you want to use persistent storage rather than local disk, you can instead create one remote volume for each CockroachDB instance using the volume driver of your choice (https://docs.docker.com/engine/reference/commandline/volume_create/), and then specify that volume driver instead of the `volume-driver=local` part of the commands above (e.g. `volume-driver=gce`) if you're using the GCE volume driver).

**Comment by a-robinson** [comment]
And here's an example of using the GCE volume driver that I just verified to work:

Install the gce volume plugin on each node using the instructions at https://github.com/mcuadros/gce-docker

Create the volumes:

```console
root@a1:/home/alex# docker volume create --driver gce -o SizeGb=10 --name cockroachdb-0
cockroachdb-0
root@a1:/home/alex# docker volume create --driver gce -o SizeGb=10 --name cockroachdb-1
cockroachdb-1
root@a1:/home/alex# docker volume create --driver gce -o SizeGb=10 --name cockroachdb-2
cockroachdb-2
```

Create the cockroachdb instances as before, only changing the volume driver from `local` to `gce`:

```console
root@a1:/home/alex# docker service create --replicas 1 --name cockroachdb-0 --network cockroachdb --label app=cockroachdb --mount type=volume,source=cockroachdb-0,target=/cockroach/cockroach-data,volume-driver=gce --stop-grace-period 60s cockroachdb/cockroach:latest start --logtostderr --insecure
9r334fvv4e20iu16glk043w4t
root@a1:/home/alex# docker service create --replicas 1 --name cockroachdb-1 --network cockroachdb --label app=cockroachdb --mount type=volume,source=cockroachdb-1,target=/cockroach/cockroach-data,volume-driver=gce --stop-grace-period 60s cockroachdb/cockroach:latest start --logtostderr --insecure --join cockroachdb-0:26257
0wbtiyqf0ldbtkgz8wkk4qryr
root@a1:/home/alex# docker service create --replicas 1 --name cockroachdb-2 --network cockroachdb --label app=cockroachdb --mount type=volume,source=cockroachdb-2,target=/cockroach/cockroach-data,volume-driver=gce --stop-grace-period 60s cockroachdb/cockroach:latest start --logtostderr --insecure --join cockroachdb-0:26257
5setgfw1057y1vzt6dihodxif
```
