### ISSUE TITLE
Start a Node Doc Update 

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#1855]
Re: [Start a Node](https://cockroachlabs.com/docs//v1.0/start-a-node.html)

## Issue Description

I had an issue recently where I restarted a node without advertise host, and it was able to join the cluster, but none of the other nodes could talk to it an queries could not run.

## Suggested Resolution 

For restarting a node in a cluster in the cloud, we should make it clear that users need to advertise host.

**Comment by jseldess** [comment]
Thanks for reporting this, @dianasaur323, but I'm wondering if this is a product issue to be looked at first? Seems very strange to me that, if the node was initially started with `--advertise-host` (or `--host`), after rejoining without those flags, other nodes would be able to talk to it. @bdarnell, have you come across this type of situation before?

**Comment by bdarnell** [comment]
In general, we don't remember command-line flags across restarts (the `--join` flag is a special case; we remember potential join targets across restarts because they can change dynamically). If you need a flag, you need to pass it every time. The solution to this is that you should never be typing `cockroach start` by hand except to put it in a script that will start it up the same way every time. This script takes the place of a config file that you might create for other databases.

**Comment by dianasaur323** [comment]
In this case, I think it would be helpful to be very specific on which flags we remember and which ones we don't. I always operated under the assumption that I only needed the --join flag once, and then afterwards, I could just cockroach start, but that isn't really the case. Not sure where the best place to surface this information is.

**Comment by bdarnell** [comment]
The simple answer is that *all* flags should be set every time. We don't want to encourage people to remove the `--join` flag on subsequent restarts because it can lead to cluster id mismatches if  the data directory is wiped. cockroachdb/docs#1813.

**Comment by sploiselle** [comment]
@jseldess Think we should start a troubleshooting flag to start collecting these kind of issues?

**Comment by jseldess** [comment]
Yes, excellent idea, @sploiselle!
