### ISSUE TITLE
Manual Deployment Doc Update 

### ISSUE THREAD

**Issue by EamonZhang** [cockroachdb/docs#1860]
Re: [Manual Deployment](https://cockroachlabs.com/docs//v1.0/manual-deployment.html)

## Issue Description

Create the certificate and key for the second node, issued to all common names you might use to refer to the node as well as to the HAProxy instances:

```
$ cockroach cert create-node \
<node2 internal IP address> \
<node2 external IP address> \
<node2 hostname>  \
<other common names for node1> \
localhost \
127.0.0.1 \
<haproxy internal IP addresses> \
<haproxy external IP addresses> \
<haproxy hostnames>  \
<other common names for haproxy instances> \
--certs-dir=certs \
--ca-key=my-safe-directory/ca.key
```

## Suggested Resolution 

Are you sure it is useful for add haproxy IP when create node cert.

if it is must, when I want to add a new node to use as haproxy ,.how to do? Recreate cert for the whole cockroach cluster? or ...

**Comment by bdarnell** [comment]
This should probably only recommend either IP addresses or hostnames for the haproxy, not both. As long as you have a working DNS name for the haproxy machines and that's what you use to access them, there's no reason to also include the IP addresses.

**Comment by jseldess** [comment]
@EamonZhang, I'm wondering if you're asking why node certs require the HAProxy address at all. If so, it's because a client verifies that the server's certificate is valid for the address it's talking to. In this case, the client is talking to HAProxy, so if the HAProxy address isn't in the server's certificate, the client will reject it.

Here's the basic sequence (@bdarnell, please correct me if I've gotten anything wrong):

1. Client connects to HAproxy.
2. HAproxy forward the connection to a node.
3. The node returns its cert to HAproxy.
4. HAproxy forwards the node's cert to the client.
5. The client inspects the node's cert to determine whether to trust it.

As for your second question, before adding a node to a secure cluster, you generate its cert. When you do that, you include the HAProxy address. If you're dealing with an existing node that needs an updated cert including the HAProxy address, CockroachDB let's you rotate a new cert into place without taking the node offline. Unfortunately, we don't yet have polished docs on the process of "cert rotation". That's coming soon. In the meantime, feel free to take a look at the draft material in this PR: https://github.com/cockroachdb/docs/pull/1331.

**Comment by bdarnell** [comment]
You can also configure haproxy to terminate the SSL connection itself. This is a little more complicated to set up but lets you give haproxy its own certificate and the nodes don't need to know anything about it.

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3549
