### ISSUE TITLE
Use the Built-in SQL Client Doc Update 

### ISSUE THREAD

**Issue by sesam** [cockroachdb/docs#1878]
Re: [Use the Built-in SQL Client](https://cockroachlabs.com/docs//v1.0/use-the-built-in-sql-client.html)

## Issue Description
`\   (grave accent followed by a backslash "escape")

## Suggested Resolution 
\`   (backslash "escape" followed by grave accent)

Tests:
```
root@:26257/> \! echo `\date`\
Sun Sep 3 ... 2017
root@:26257/> \! echo \`date\`
`date`
```

**Comment by jseldess** [comment]
Thanks for reporting this, @sesam. We'll update the page soon.

**Comment by jseldess** [comment]
@benesch, need your help here, I think. In a markdown table, I have:

```
`\|` | Run the output of an external command as SQL statements. See the [example](#run-external-commands-from-the-sql-shell) below.
```

That's rendering as:

<img width="819" alt="screen shot 2017-09-08 at 9 34 52 am" src="https://user-images.githubusercontent.com/15893490/30214063-10e9611c-9479-11e7-9e48-27d5294c97bf.png">
 
Elsewhere on the page, `\|` isn't a problem. The problem seems to come from the fact that it's in a table, and the character immediately following is a pipe `|` indicating a column border. I've tried changing some and all of
> `\|` |
to html codes, but I can't get anything to work. Any ideas?

**Comment by benesch** [comment]
Yeah, it's a known bug in redcarpet. https://github.com/vmg/redcarpet/issues/477

Afraid the only solution I have is to replace the entire table with an HTML `<table>`.

**Comment by benesch** [comment]
Well, that or switch the page rst. :) Hoping there might be some time to evaluate that transition this cycle.

**Comment by sesam** [comment]
I added a space and made a pull request :)
https://github.com/cockroachdb/docs/pull/1895

Before finding that, I also tried
I tried

gem install redcarpet
irb
require 'redcarpet'
> renderer = Redcarpet::Render::HTML.new
> markdown = Redcarpet::Markdown.new(renderer, extensions = {}
> markdown.render("`\|` | Run the output of an external command as SQL statements. See the [example](#run-external-commands-from-the-sql-shell) below.")

 => "<p><code>|</code> | Run the output of an external command as SQL statements. See the <a href=\"#run-external-commands-from-the-sql-shell\">example</a> below.</p>\n"

>  Redcarpet::VERSION
 => "3.4.0"

and pondered on the options of doing some unicode tricks to prevent the | from being rendered as a table separator, but in the end all that was needed was a space between | and ` it appears.

**Comment by jseldess** [comment]
Unfortunately, the referenced PR doesn't solve this, so I'm reopening this issue.
