### ISSUE TITLE
Update the --background flag description

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#1951]
https://www.cockroachlabs.com/docs/dev/start-a-node.html#general

If you `start` a bunch of nodes with `--background` and then want to issue the `init` command from one of those nodes, you can't because `--background` doesn't return control to the shell until the node is ready to accept requests. `&` is better in such a case.

**Comment by bdarnell** [comment]
Note that this behavior may change in 1.2 (cockroachdb/cockroach#18938). Unless and until it does, though, we probably want to recommend `&` instead of `--background` for all multi-node clusters. (or even better, run everything in the foreground under a reasonable process manager. Explicit backgrounding is only for toy deployments)

**Comment by jseldess** [comment]
Related comment: https://github.com/cockroachdb/cockroach/issues/15889#issuecomment-301337898

**Comment by jseldess** [comment]
Resolved by https://github.com/cockroachdb/cockroach/pull/21682.
