### ISSUE TITLE
SERIAL Doc Update 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#1993]
Re: [SERIAL](https://cockroachlabs.com/docs//v1.1/serial.html)

## Issue Description

This combination is likely to be globally unique except in extreme cases (see this example for more details).  The SERIAL values are likely to be globally unique except in cases where a very large number of IDs (100,000+) are generated per node per second.

## Suggested Resolution 

Is there a more tight description on 100,000+.  It is not uncommon to see a system being able to process more than 1 million inserts a sec on today's multi socket / multi core databases.

**Comment by petermattis** [comment]
I'm not sure where that text comes from, but the rate of generation does not affect the uniqueness of SERIAL values. Internally, SERIAL uses a monotonic clock. The only way SERIAL values can collide is when a node restarts exactly during a backward time jump. There is a TODO in the code to address that.

**Comment by robert-s-lee** [comment]
the text is from https://www.cockroachlabs.com/docs/stable/create-table.html#create-a-table-with-auto-generated-unique-row-ids which is the link from the example below.  

<img width="648" alt="screen shot 2017-10-12 at 2 03 55 pm" src="https://user-images.githubusercontent.com/6315124/31513942-e78d8ee2-af5d-11e7-9f78-f49f98c2ceba.png">

**Comment by petermattis** [comment]
Got it. This is a docs issue.

**Comment by bdarnell** [comment]
Won't a sustained rate of over 100k/sec push that node's monotonic counter ahead of real time, and then this will be lost on restart? 

There's also some chance of duplicate IDs in clusters that have node IDs over 32k (including all nodes, current and removed).

**Comment by jseldess** [comment]
@petermattis, @bdarnell, I'm not clear on how to update the docs. Are we saying that `SERIAL`, `UUID DEFAULT uuid_v4()::UUID`, and `BYTES DEFAULT uuid_v4()` are all equally good for generating unique row IDs? And if so, should we just say use any of them?

Is distribution of IDs at the key-value level the primary difference?

> The distribution of IDs at the key-value level may also be a consideration. When using BYTES or UUID with uuid_v4() as the default value, consecutively generated IDs will be spread across different key-value ranges (and therefore likely across different nodes), whereas when using INT with unique_rowid() as the default value, consecutively generated IDs may end up in the same key-value range.

**Comment by bdarnell** [comment]
I think the docs are accurate on this point and no changes are necessary. SERIAL and UUID keys are very different because of the key distribution; we shouldn't treat them as interchangeable. My recommendation is that unless you have reason to believe that SERIAL is better for your application, UUIDs are the better default.

**Comment by sploiselle** [comment]
@bdarnell Would you recommend converting the examples of single-column PRIMARY KEYs to UUID (instead of SERIAL)? I think that change would give users a clearer hint of this recommendation.

**Comment by robert-s-lee** [comment]
Original intent of this issue was to more tightly qualify 100k per sec for the serial method.  Should that caution be removed? Regarding 32K hosts, if there are 64k nodes in the cluster then chances of dup is higher with serial?  If so can more technical description be provided on the composition of serial?  How does number of hosts and time factor into unique number? That could help technical audience decide if this method is sufficient.  Is there an issue to handle the edge condition regarding the restart?

**Comment by petermattis** [comment]
I don't think we need to be worrying (at this time) about 32k nodes or 100k serial IDs generated per second. We can certainly change the recommendation to use UUID, though.

**Comment by bdarnell** [comment]
@sploiselle i would generally encourage the use of UUID over serial, although it doesn't seem that we have many examples currently in the docs that use `SERIAL` (i do see one in the IMPORT docs, and this one is worth changing - moving SERIAL columns between databases is often more complicated than other types (although that's less true for us since our serial columns are more globally unique).

@robert-s-lee No, the 100k/sec limit still stands as far as I can tell. Above 32k node IDs, we start to see some chance of collision below 100k/sec, although this is generally a minor issue since as long as the SERIAL column is used in a unique index it'll just get a constraint failure that can be retried. We reserve the right to change the implementation so we don't want to document it in too much detail

The implementation is at https://github.com/cockroachdb/cockroach/blob/32224c9be402d40754c7537321efd511e6e2366f/pkg/sql/parser/builtins.go#L2965-L3000 but we reserve the right to change it so we don't want to document it in too much detail. There's a TODO there about persisting the time, although it refers to NTP adjustments instead of exceeding the 100k limit.

**Comment by robert-s-lee** [comment]
@bdarnell's response on https://forum.cockroachlabs.com/t/serial-and-javascript/556/7 was useful 

> UUIDs and unique_rowid() have different ordering properties - the UUID version will scatter records randomly throughout the table, while the unique_rowid() version will group records created about the same time onto the same range. Which one is better depends on your query pattern (UUIDs ensure that every node shares in the load, but unique_rowid() may be able to group "related" data together so it can be queried without a distributed transaction). My bias is to prefer the scattering of a UUID primary key unless I have reason to believe that my query pattern will benefit from time-ordered storage (and this benefit is large enough to overcome the less balanced load).

**Comment by jseldess** [comment]
https://github.com/cockroachdb/docs/pull/2128 revises our docs to emphasize `UUID` over `SERIAL`. Therefore closing this, but if there are important points I've missed, happy to reopen.
