### ISSUE TITLE
Increase bare minimum hardware requirements

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2181]
We currently say `1 CPU and 2 GB of RAM per node` is the bare minimum. 

Since some potential customers have started off with 1 CPU and been disappointed, @robert-s-lee suggests we increase to 2 CPUs. 

@bdarnell, @nstewart, @mberhault, thoughts?

**Comment by bdarnell** [comment]
I'm OK with this, although we would also like to reduce the minimum requirements over time (for example, now that we've reduced the default cache sizes, maybe we can run in 1GB). What specific issues have we seen with 1 cpu, and are they alleviated by going to 2?

**Comment by jseldess** [comment]
@robert-s-lee, can you provide details from your POC update?

**Comment by jseldess** [comment]
Ping @robert-s-lee. Can you add details in response to @bdarnell's question?

**Comment by robert-s-lee** [comment]
Some prospective are running with bare minimum for performance testing and get frustrated at not getting the the results expdcted.   While it should be not be a big deal  to get a bigger box in the cloud and try again, there is loss of momentum and takes efforts to recover from the setback.  More guideline on what could be expected.  

on a single CPU cloud server ( talking about one thread on AWS ) Is what customers are picking based in this recommendation.  Some database vendor flat out recommend 8 cores even if technically the system will run fine at 1 vCPU for testing purposes so that self server PoC customers get started in the right footing.  Just checked mongodb which recommends a 1 physical core + additional https://docs.mongodb.com/manual/administration/production-notes/#prod-notes-ram

**Comment by bdarnell** [comment]
> on a single CPU cloud server ( talking about one thread on AWS )

Has this come up on platforms other than AWS? In talking about this with @jseldess yesterday I thought that changing the recommendation to 2 cpus would help because it would avoid the fractional-cpu instances like `t2.micro`. However, after looking at [amazon's docs](https://aws.amazon.com/ec2/instance-types/), I don't think that's actually true. The `t2.medium` instance type is listed as 2 cpus, but it also uses the "cpu credits" limiter so you can only sustain a load of 40% of one core. Conversely, the `m3.medium` instance is a single vCPU, but I believe you get the whole core and I would expect CRDB to perform fine on it. 

So maybe the recommendation needs to be 2GB of ram and one *entire* core, with additional per-provider docs. For AWS, that means not using the "burstable" (`t2`) instance family, no matter the listed CPU count (the "T2 Unlimited" option might make this workable, although it would need to be tested). For GCE, avoid "shared-core" machines (`f1` and `g1`). On Azure, you want to avoid the "burstable" B-series, but we've already established that *only* the L-series is reliable on that platform.

**Comment by robert-s-lee** [comment]
One thread came up on AWS so far.  @bdarnell guideline per cloud provider is very appealing as it provides more prescriptive guidance.

**Comment by jseldess** [comment]
OK, I can work the per-cloud guidance into the open PR. Might as well also include non-minimum recommendations, based on what we've be using for our production clusters, described [here](https://github.com/cockroachdb/docs/issues/1132#issuecomment-349659906).

**Comment by nstewart** [comment]
I'm going to bake these into our cloudformation templates. One more question on specs: in the production docs we write `Adding more CPU is usually more beneficial than adding more RAM.` Is it fair to say, then, that we would never recommend someone use a memory-optimized r- instance in AWS and stick to either m- (general purpose) or c- (compute optimized) instances?

**Comment by robert-s-lee** [comment]
With traditional single instance DB, performance tuning had been workload dependent.  Regarding to RAM, a system should have enough to maintain close to 100% buffer cache ratio without going in to diminishing return in terms of cost / performance ratio.  The chief reason is faster reading performance from RAM than reading from disk.  If CRDB is different on tuning guidance, an explanation on the reason(s) would be important.

**Comment by bdarnell** [comment]
> Is it fair to say, then, that we would never recommend someone use a memory-optimized r- instance in AWS and stick to either m- (general purpose) or c- (compute optimized) instances?

I wouldn't say "never", but I don't think we've seen a case yet where I'd recommend a "memory-optimized" configuration. For AWS, the `m`, `c`, and `i` (ssd storage-optimized) classes look like the best fits.

**Comment by nstewart** [comment]
@jseldess FYI for documentation purposes the cheapest m instance (m3.medium) isn't available in all regions. https://github.com/kubernetes/kops/issues/1455
