### ISSUE TITLE
sql: redefine NaN = NaN -> true

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2183]
PR: https://github.com/cockroachdb/cockroach/pull/19144

From release notes:
> Backwards-incompatible change: Redefined `NaN` comparisons to be compatible with PostgreSQL. `NaN` is now equal to itself and sorts before all other non-NULL values.

**Comment by jseldess** [comment]
@nvanbenschoten, we don't seem to talk about `NaN` anywhere in our docs. Postgres has this note for `NUMERIC` and floating-point types: 

> IEEE754 specifies that NaN should not compare equal to any other floating-point value (including NaN). In order to allow floating-point values to be sorted and used in tree-based indexes, PostgreSQL treats NaN values as equal, and greater than all non-NaN values.

Is that what we should do as well, call this out on [`DECIMAL`](https://www.cockroachlabs.com/docs/dev/decimal.html) and [`FLOAT`](https://www.cockroachlabs.com/docs/dev/float.html)?

**Comment by couchand** [comment]
@jseldess Looking into this, I noticed that it seems like there's an error in the current docs for the only current reference NaN.  On the table of Supported Casting & Conversion for the FLOAT data type, we claim this:

"DECIMAL | Causes an error to be reported if the value is NaN or +/- Inf."

But it seems like such casts actually work without error.  Should we update this as well?

**Comment by nvanbenschoten** [comment]
@jseldess sorry I missed this. Yes, the PR you referenced above changes our NaN behavior so that NaN values are treated as equal, and we should document this in a similar way to Postgres. The only difference from PG is that in Cockroach NaN is treated as less than all non-NaN values, not greater than. See [this query](https://github.com/cockroachdb/cockroach/pull/19144/files#diff-04f3da459264df28358d3da6100f73ccR202) for an example.

**Comment by jseldess** [comment]
@Amruta-Ranade, one final 2.0 issue for you.

**Comment by jseldess** [comment]
Closing as this is for a very old, now-unsupported version of crdb.
