### ISSUE TITLE
Specifying replica location via zone configs

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2296]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwINAgXA5on9pr2T/recii49ucInqSSnmM

PRs:

**Comment by a-robinson** [comment]
This has been moved back into 2.0. Discussion happened in https://github.com/cockroachdb/cockroach/issues/19985, with the main PRs being https://github.com/cockroachdb/cockroach/pull/22412 and https://github.com/cockroachdb/cockroach/pull/22819. I'm happy to talk things through, since we didn't go through an RFC process for this.

**Comment by jseldess** [comment]
Thanks, @a-robinson. I'll take you up on the offer once I'm back.
