### ISSUE TITLE
HTTPS endpoint for backup/restore

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2301]
From @dianasaur323:
> Currently, if the HTTP end point is HTTPS, then backup / restore will be secure. However, it will be insecure if the endpoint is HTTP. Clarify this in the docs.

The `HTTP` row in this [table in the `restore` docs](http://www.cockroachlabs.com/docs/stable/restore.html#backup-file-urls), as well as the corresponding spot in the `backup` docs, need to be updated. We might want to list `HTTPS` instead of `HTTP`. 

Those docs should also link to http://www.cockroachlabs.com/docs/stable/create-a-file-server.html. That page also needs to mention secure HTTPS.

**Comment by bdarnell** [comment]
If the endpoint is HTTPS, the backup/restore will be secure *in transit*. It's up to the operator of that HTTPS endpoint to control the security of the backup once it's stored. The instructions at `create-a-file-server.html` are not secure at all if I'm understanding them correctly. 

We need to test that when backing up to an HTTPS URL, we fail if the site presents a bogus TLS certificate.

How does RESTORE authenticate to the HTTPS server? There's no room to pass parameters, so are we relying solely on the unguessability of the URL? If so, that needs to be spelled out clearly (and we need to support something better; maybe a basic-auth or client cert variable similar to the s3/azure ones).

**Comment by dianasaur323** [comment]
pulling in @mjibson to provide some color here. if this is something we need to fix, we'll have to add it to the roadmap.

**Comment by mjibson** [comment]
Yes, we should specify "secure in transit". The same problems exist for whatever s3 or gcs bucket a user is writing to, though: if they are configured with public read access then they won't be "secure". 

We are in planning stages to remove the `temp` requirement from IMPORT, which was the entire reason we made the create-a-file-server page. (Although, clearly, it would be useful to people wanting to backup who didn't have access to any cloud storage.) Documenting how to implement HTTPS there is going to be tricky because of certificate names, and I think we should, at most, link so some other site.

Overall I'd:

1) Add an HTTPS line in the storage docs.
2) Change the HTTP line to document that it will no transit data securely. That will make HTTP the only storage with that note, which should imply the others do transit securely.

**Comment by bdarnell** [comment]
@mjibson What about my questions about how RESTORE authenticates to the HTTPS server?

If the create-a-file-server page is going away once IMPORT is updated, it probably needs a note to discourage people from using it for anything else. (and even using it for IMPORT has security implications that need to be documented)

**Comment by mjibson** [comment]
I had edited my comment above to add a note about adding support for username:password in HTTP/S URLs. I think that's good enough? I'm not sure if there are better ways.

**Comment by bdarnell** [comment]
Yeah, I don't know of a better way (that would be at all widely supported).

**Comment by jseldess** [comment]
We have closed this issue because it is more than 3 years
old. If this issue is still relevant, please add a comment and reopen
the issue. Thank you for your contribution to CockroachDB docs!
