### ISSUE TITLE
Document how to prevent re-ordering causally-related transactions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2327]
Jesse Seldess (jseldess) commented:

2 possible methods:
- Use our "causality token" (see image below)
- Use `--linearizable` flag or env variable

@nstewart, @tschottdorf, do we want to document both methods?

![pasted image at 2018_01_02 12_23 pm](https://user-images.githubusercontent.com/15893490/34521898-21c939b2-f05e-11e7-9b67-6ac8fd7596ce.png)

**Comment by tschottdorf** [comment]
I would not document `--linearizable` and I'd double-check with @bdarnell that what I'm suggesting is the way we want to go about it for now.

**Comment by bdarnell** [comment]
I'd rather not document the "retry until you get the cluster_logical_timestamp you want" option either. It's probably the best option we have for now but I'd rather build in something that does this than intrude on the clients like this (we should be able to do it with a variant of `crdb_internal.force_retry`)

**Comment by jseldess** [comment]
Looping in @nstewart, who asked for this to be documented. Nate, thoughts? Is this something for the roadmap?

**Comment by nstewart** [comment]
I generally agree with @bdarnell point; the current implementation isn't up to our make-data-easy standards. However, my main concern is we now have multiple (and growing, with the new Google + AWS time products) public mentions of our linearizable and linearizable-like capabilities and while we have solutions (in different states of usefulness) it's nearly impossible to actually evaluate any of them at the moment; even as a technical hobbyist/early adopter. 

I agree we should add an improvement to the actual UX for these tokens before doing a big push -- cc @awoods187 to track; he's already tracking the `linearizable` flag updates -- but can we just add some sort of non-blog explanation with a disclaimer that this is a proof of concept and we plan to make it better in the future? Maybe even if we bring it up in the architecture docs rather than an actual how-to? 

I just think that in meetups we should either be able to point people to something explaining how to use these features or stop saying we support them when the question comes up. 

What do you all think?

**Comment by bdarnell** [comment]
For `--linearizable`, it's not a UX thing, it's a "does it work at all?" thing. We haven't tested this since it was first introduced and never with any sort of rigor. We shouldn't be telling anyone that this flag exists (the `experimental-clockless` mode is currently giving us a lesson in the dangers of overcommitting to an experiment). If we must talk about linearizability, we should just talk about sleep-after-write as something that we *could* do given strong clock synchronization. 

If we think causality tokens are important we should try to get functions for this purpose added to 2.0 instead of documenting this weird hack. This should be pretty easy.

**Comment by nstewart** [comment]
I'm on board with everything you said. From the PM perspective, I'm handing off to @awoods187 at this point.

**Comment by jseldess** [comment]
@awoods187, is this still something we want to document?
