### ISSUE TITLE
Query tuning and monitoring (preliminary)

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#2330]
Re: [Cluster Settings](https://cockroachlabs.com/docs//v1.1/cluster-settings.html)

## Issue Description

select * from crdb_internal.node_statement_statistics provides per query statistics for tuning and monitoring.   

For example, the first row of the below shows 5ms service_lat_avg from database returning 35 rows_avg.  This query was executed 61 times (count) during the sample period.

node_id | application_name | flags | key | anonymized | count | first_attempt_count | max_retries | last_error | rows_avg | rows_var | parse_lat_avg | parse_lat_var | plan_lat_avg | plan_lat_var | run_lat_avg | run_lat_var | service_lat_avg | service_lat_var | overhead_lat_avg | overhead_lat_var
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 |   | + | SELECT "timestamp", "eventType", "targetID", "reportingID", info, "uniqueID" FROM system.eventlog WHERE _ ORDER BY "timestamp" DESC LIMIT $1 | SELECT _, _, _, _, _, _ FROM _ WHERE _ ORDER BY _ DESC LIMIT $1 | 61 | 61 | 0 | NULL | 35 | 0 | 0.00023385942623 | 9.64093242348634E-10 | 0.002977502655738 | 6.64031209619496E-07 | 0.002638377770492 | 1.11025540398613E-07 | 0.005882487983607 | 8.42002469584183E-07 | 3.27481311475411E-05 | 7.37665614491812E-11 | 0.160941044
1 |   |   | SELECT config FROM system.zones WHERE id = $1 | SELECT _ FROM _ WHERE _ = $1 | 62 | 62 | 0 | NULL | 0.354838709677419 | 0.232681121099947 | 2.45511451612903E-05 | 1.609766606055E-11 | 0.002519464129032 | 5.73671138791962E-08 | 0.000506544919355 | 6.07910932263273E-09 | 0.003074214274194 | 8.50568774461695E-08 | 2.36540806451613E-05 | 2.27112823376522E-11 | 0.031405785
1 |   |   | SELECT _ | SELECT _ | 4153 | 4153 | 0 | NULL | 1 | 0 | 0 | 0 | 1.61939277630629E-05 | 2.46444350415051E-11 | 6.02685913797254E-06 | 4.33744083203173E-12 | 4.65140717553577E-05 | 1.45531400654774E-10 | 2.42932848543222E-05 | 4.79693056117576E-11 | 0.025029546
1 |   |   | SELECT id FROM system.namespace WHERE ("parentID" = $1) AND ("name" = $2) | SELECT _ FROM _ WHERE (_ = $1) AND (_ = $2) | 40 | 40 | 0 | NULL | 1 | 0 | 3.1585E-05 | 3.61451478461539E-11 | 0.002569022625 | 5.60174232951634E-08 | 0.00053039315 | 4.7887212529E-09 | 0.00315668975 | 7.7928242556859E-08 | 2.5688975E-05 | 5.73279991532063E-11 | 0.021215726
1 |   |   | SELECT key, value, "lastUpdated" FROM system.ui WHERE key IN ($1) | SELECT _, _, _ FROM _ WHERE _ IN ($1) | 1 | 1 | 0 | NULL | 0 | NaN | 0.000220514 | NaN | 0.003058928 | NaN | 0.000266423 | NaN | 0.003584567 | NaN | 3.87020000000003E-05 | NaN | 0.000266423

## Suggested Resolution 

Document column definition and availability of the information.

**Comment by knz** [comment]
So query execution encompasses the following phases:
- parse  (measured `parse_lat`)
- plan (measured as `plan_lat`)
- run (measured as `run_lat`)

The total execution latency server-side, from the point the query is received to the point the last result is sent is measured as `service_lat` (you probably knew this already).

**So we expect something like service = parse + plan + run.**

However, there is some additional server-side work done before parse, between parse and plan, between plan and run, and after run, which is not measured by the 3 variables mentioned above. We want this amount of "unaccounted time" to be minimal, of course, but engineering being what it is there is always some imperfection. We measure this imperfection as `overhead_lat`. 

In practice, if we do the engineering work properly, the `overhead_lat` should remain negligible compared to the others (because we'll want to account time accurately in the phase where it is spent). The example you pasted above illustrates this. If you ever see `overhead_lat` become large compared to the others, that is likely a measurement bug, which needs to be filed and fixed.

Next to all this, for each of the variables we measure separately the mean value (`avg`) and the variance (`var`). A small variance indicates that all occurrences of the statement in the `key` / `anonymized` columns have a similar timing behavior. A large variance indicates that the statement exists in different forms with large differences in timing behavior. Large variances are not good, because they imply that a user cannot easily predict the behavior of this type of statement ahead of time. We probably want to investigate large variances.

**Comment by knz** [comment]
Also: The unit of time for the various time measurements is seconds.

**Comment by knz** [comment]
If there is anything else you need to know I'll be happy to help!

**Comment by robert-s-lee** [comment]
@knz  can the cumulative numbers be exposed or made available the instead of computed average.

The cumulative stats can be used to compute per period performance that could be used in calculating trends.  

For example, a typical scenario (similar to how the current time series data) 

- an external job is run to save the data once every minute with something like "insert into nss_history select now(),* from crdb_internal.node_statement_statistics"
- when a user report performance issue, DBA can look at the nss_history table, filter on the two time period, take the difference from the cumulative stats of two time periods to calculate the average for the time period.
- This can also help CRDB and customers answer questions such as what queries were run, how often did they run, what was the performance at the time of interest, is the performance the same all the time, if not same identify changes that could have caused the issue at the time of interest

A potential workaround could be to take the cumulative could be to take 
- avg * count of the latest time period, 
- doing the same of the previous time period, 
- then taking the difference 
- re-compute the average for the time period

**Comment by knz** [comment]
The sums can indeed be obtained by multiplying the average by the count. Having a separate field would be effectively storing redundant information. However, we can readily provide additional computed columns in the `node_statement_statistics` that reveal this count. Would this be sufficient?

**Comment by robert-s-lee** [comment]
Not sure how other parts of the system is using this table, so reluctant to ask for the change in the node_statement_statistics table.  The cumulative stats are not available from some other view?

**Comment by knz** [comment]
Adding columns to this table will not break anything as far as I know. (Would be different if we were to change the columns). You can also write a view that computes the cumulative sums, if that matters: `create view ... as select xxx_avg*count from crdb_internal.node_statement_statistics` etc.

**Comment by jseldess** [comment]
This work is "preliminary" because it will be affected by this [2.1 roadmap work](https://github.com/cockroachdb/docs/issues/2039).

**Comment by jseldess** [comment]
@piyush-singh, @robert-s-lee, given that 2.1 has the statements page, is there still a need to document this internal table? Are there important gaps not covered by the UI?

**Comment by jseldess** [comment]
Closing in favor of the work we did on the [statements page](https://www.cockroachlabs.com/docs/v2.1/admin-ui-statements-page.html) and [performance tuning](https://www.cockroachlabs.com/docs/v2.1/performance-tuning.html) tutorial.
