### ISSUE TITLE
Document case sensitivity rules for collations

### ISSUE THREAD

**Issue by justinj** [cockroachdb/docs#2430]
I actually have no idea how this stuff works, but there's some magical collations that just seem to exist, like `en_u_ks_level1`, which is English text ignoring case. I can't find anything in our docs on this sub-language of how to specify additional rules for collations, but it seems WAY too useful to not have documented on the [collations page](https://www.cockroachlabs.com/docs/stable/collate.html) (even just for the special case of only case-insensitivity).

[This page](http://cldr.unicode.org/development/development-process/design-proposals/bcp47-mapping) seems to have some info on it.

cc @mjibson
cc @knz because it seems you reviewed some of the PRs for collations.

**Comment by jseldess** [comment]
@justinj, is this related to https://github.com/cockroachdb/docs/issues/2430?

**Comment by justinj** [comment]
Didn't know about that at all! Yes, seems like the same issue. Sorry for the duplication.

**Comment by jseldess** [comment]
From @justinj, copied over from https://github.com/cockroachdb/docs/issues/2430:

I actually have no idea how this stuff works, but there's some magical collations that just seem to exist, like `en_u_ks_level1`, which is English text ignoring case. I can't find anything in our docs on this sub-language of how to specify additional rules for collations, but it seems WAY too useful to not have documented on the [collations page](https://www.cockroachlabs.com/docs/stable/collate.html) (even just for the special case of only case-insensitivity).

[This page](http://cldr.unicode.org/development/development-process/design-proposals/bcp47-mapping) seems to have some info on it.

cc @mjibson
cc @knz because it seems you reviewed some of the PRs for collations.
