### ISSUE TITLE
Document Known Limitations in 2.0

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#2446]

**Comment by mjibson** [comment]
IMPORT can sometimes fail with a "context canceled" error, or can restart itself many times without ever finishing. If this is happening it is likely due to a high amount of disk contention. This can be mitigated by setting the `kv.bulk_io_write.max_rate` setting to a value below your max disk write speed. For example, to set it to 10MB/s, execute: `set cluster setting kv.bulk_io_write.max_rate = '10MB'`.

**Comment by jseldess** [comment]
https://github.com/cockroachdb/cockroach/issues/24379#issuecomment-377717175

**Comment by jseldess** [comment]
@mjibson, do we have an issue tracking the import limitation you mention above?

**Comment by jseldess** [comment]
https://github.com/cockroachdb/cockroach/issues/23699

**Comment by jseldess** [comment]
https://github.com/cockroachdb/cockroach/issues/22418

**Comment by jseldess** [comment]
https://github.com/cockroachdb/cockroach/issues/20653

**Comment by jseldess** [comment]
https://github.com/cockroachdb/cockroach/issues/22508

**Comment by mjibson** [comment]
It is already documented at https://www.cockroachlabs.com/docs/dev/import.html#known-limitation. Or we could ignore my issue because it is getting fixed in 2.0.1.

**Comment by jseldess** [comment]
@mjibson, right, and I'm adding it to the "master" known limitations list. I just want to know what the tracking issue is so that I'm sure to know when it's resolved. Can you point me to it?
