### ISSUE TITLE
Make detailed SQL support page filterable

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2448]
The new [Detailed SQL Standard Comparison](https://www.cockroachlabs.com/docs/dev/detailed-sql-support.html) table is very large. It'd be nice to give users the ability to filter the table based on the third column, `CockroachDB Support`. Ideally, the page would show all rows by default and then let users filter for just `Yes`, `No`, and `Partial` rows.

@j-low, how difficult would it be to reuse the filtering functionality on https://www.cockroachlabs.com/docs/dev/cockroachdb-in-comparison.html?

cc: @awoods187, @Amruta-Ranade

**Comment by luciaaaaaaa** [comment]
hey @jseldess for this issue (https://www.cockroachlabs.com/docs/v20.1/sql-feature-support.html) I'm seeing a lot of small tables, has this changed recently?

The original sort/filter solution outlined won't help us address this.

**Comment by luciaaaaaaa** [comment]
Link to designs in Figma: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2228%3A11640

**Comment by yingzhuchin** [comment]
The original solution doesn't work out-of-the-box here because the designs are different. https://www.cockroachlabs.com/docs/dev/cockroachdb-in-comparison.html has no column header, whereas https://www.cockroachlabs.com/docs/dev/detailed-sql-support.html has a column header ("CockroachDB Support"). Since https://www.cockroachlabs.com/docs/dev/cockroachdb-in-comparison.html has a custom JS script tailored specifically for that table, we can't just reuse the same JS for https://www.cockroachlabs.com/docs/dev/detailed-sql-support.html.

**Comment by yingzhuchin** [comment]
Looks like the relevant page has been archived: https://github.com/cockroachdb/docs/blob/master/archived/detailed-sql-support.md

Should we close this?

**Comment by awoods187** [comment]
SGTM
