### ISSUE TITLE
Explain Snapshots graph on Replication dashboard

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2603]
https://www.cockroachlabs.com/docs/dev/admin-ui-replication-dashboard.html#other-graphs

If/when we want to document the **Snapshots** graph on the **Replication** dashboard, here's a good summary from @dt:

> Usually the nodes in a raft group stay synchronized by following along the log message by message — e.g. `1) a=3 2) b=4 3) a=1 4) c=5, …` — , however if a node is far enough behind (e.g. if it fell behind or is a new node getting up to speed), rather than send the individual messages that changed the range, we can send it a snapshot of range, e.g. `at time 4) a=1, b=4, c=5` and then it can start following along from there instead. (edited)
>
> `generated` is when a node makes one of these, applied is when a node got one and used it. `preemptive` means we anticipated a node was _going_ to want such a snapshot (e.g. about to be added to a raft group) and sent it ahead of time. (edited)

**Comment by bdarnell** [comment]
We may want to change the labels because "normal" snapshots should in fact be rare. The vast majority of snapshots should be preemptive. Internally we refer to non-preemptive snapshots as "raft-initiated". Seeing a lot of "normal" snapshots actually indicates a problem: some replicas are struggling to keep up with write traffic.
