### ISSUE TITLE
How to backup/restore systems.users

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/docs#2701]
Re: [RESTORE](https://cockroachlabs.com/docs//v2.0/restore.html)

## Issue Description

The system.users documentation here doesn't work as expected -> I believe you have to separately backup the system table, and then restore it into and existing DB and table

**Comment by jseldess** [comment]
@dianasaur323, the docs say that every backup includes the `systems.users` table. Is that not correct? Can you please provide more details about this not working as expected?

**Comment by dianasaur323** [comment]
@jseldess yes, happy to provide more detail. So this PR https://github.com/cockroachdb/cockroach/pull/19975 removed systems.users and systems.descriptors from backups. This means that if you want to backup systems.users, you have to back it up intentionally. Also, when I tried restoring the users table into an existing DB, I ended up with a primary key violation. So, I think the correct path here is 1) backup system.users, 2) create DB you want to restore into, 3) create new table, 4) restore into new table, 5) delete all the existing rows from the old system.users table, 6) copy rows from new table into old table, 7) drop new table. cc @dt also note that I haven't had time to manually test this myself yet.

**Comment by bdarnell** [comment]
The docs still say that every backup contains `system.users`, but this doesn't appear to be true (since cockroachdb/cockroach#19975, as @dianasaur323 said). We need to document that `system.users` must be backed up explicitly if this is desired.

Are there other system tables that should be backed up? It looks like `role_members`, `settings`, and `zones` are likely candidates. Other system tables (including `namespace` and `descriptor`) will be updated as needed by restoring other tables from backups, and these *must not* be backed up explicitly. 

I got a request at an operations training last week for more guidance about backing up the system database.

**Comment by rolandcrosby** [comment]
@bdarnell As of [July 2017](https://github.com/cockroachdb/cockroach/pull/17235/files#diff-34b60d24cdfbf2ee759f96cb819709e3R386), the system tables identified as suitable for backup were locations, role_members, users, and zones. Settings may also be a good candidate, though some of the settings (e.g. version, cluster.secret) may be problematic to restore.

According to @dt, backups originally silently included all system tables, but this was changed in the 2.0 timeframe.

When @lhirata is back next week I'll ask her to prioritize a doc fix to remove the incorrect information about system.users being backed up by default, as well as new guidance on how to back up and restore users, grants, and roles.

**Comment by jseldess** [comment]
Dup of https://github.com/cockroachdb/docs/issues/5002.
