### ISSUE TITLE
The text "new in v2" pollutes the link anchors

### ISSUE THREAD

**Issue by knz** [cockroachdb/docs#2749]
Adding the text "new in v2.0" in a (sub-)section title causes the link anchor to also contain this text.

For example, 

```
# Foreign Key Actions <span>New in v2.0</span>
```

Causes the anchor to become `#foreign-key-actions-new-in-v2.0`

This is a problem because the section links are part of the public doc API and the text "new in v2.0" is inherently temporary. The moment we bump the version and remove this annotation, the links will break.

There are two ways forward:

1. either add the text "new in v2.0" _just below_ the section title (in a paragraph of its own) so that the anchor generation doesn't see it
2. modify either the md-to-html converter, or add a post-processor, to remove this text from the anchors.

(I can help with either.)

**Comment by jseldess** [comment]
@knz, I agree that this is a problem, but I don't think it's as bad as you say. If someone is linking to an anchor on a page and the anchor text changes, the link doesn't break; it takes the user to the top of the page rather than to the specific anchor. 

We add the callout to headers in cases where we want it to show up in the on-page TOC. Do you think there's a way for us to add the callout to a header but not actually change the anchor text?

cc @bdarnell for his opinions on this particular usage of the callout (in headers).

**Comment by bdarnell** [comment]
Yeah, it's unfortunate that this text appears in the anchor. But it doesn't bother me too much. I wouldn't go so far as to say that the section links are "part of the public doc API"; it's OK if we break them occasionally in major releases since the page is still there.

**Comment by jseldess** [comment]
@j-low, is this something you might be able to help with in the 2.1 timeframe?

**Comment by jseldess** [comment]
Closing for now, as we have been tending to use callouts at the start of paragraphs more than in headers.
