### ISSUE TITLE
ARRAY can now be used with the PostgreSQL binary format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2796]
PR: https://github.com/cockroachdb/cockroach/pull/23467

**Comment by lhirata** [comment]
Doesn't seem like an update is needed for the docs, unless you think I should add a note to the `ARRAY` doc that says something like "New in 2.0: ARRAYs can now be used with the PostgreSQL binary format."

It seems like we might not need this since we have a blanket statement that says, "The `ARRAY` data type is useful for ensuring compatibility with ORMs and other tools."

Thoughts?

**Comment by jseldess** [comment]
I'm not clear not on this. @justinj, do you think we need any explicit updates to https://www.cockroachlabs.com/docs/stable/array.html#syntax here?

**Comment by justinj** [comment]
No, this is a protocol-level change, it only affects the interaction with certain drivers.

**Comment by jseldess** [comment]
Nothing to do then, @lhirata :).
