### ISSUE TITLE
Environment variables should be listed on "Cockroach commands"

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#2894]
As a user, I would like to see at a glance exactly which environment variables correspond to which [cockroach command](https://www.cockroachlabs.com/docs/stable/cockroach-commands.html) (when applicable).

Currently we say to

> see the documentation for each command

However, opening a new tab and searching for "environment" or in some cases "env " and hoping to find what I need is too hard (I am a very lazy user! :-) ).

This issue may actually want to grow into something more comprehensive like 'List all CRDB env vars in one place'.

**Comment by bdarnell** [comment]
Note that in general, we use environment variables for things we intend to keep undocumented (because they're experimental or only for internal use). That's one of the reasons for using env vars instead of flags (which would show up in `--help`). There are only a few env vars that we want to document for public use (mainly the client-side ones), and `COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING`.

**Comment by jseldess** [comment]
Closing, based on Ben's feedback.
