### ISSUE TITLE
Rethink the releases sidebar

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#2918]
1.1 and 1.0 are listed in the releases sidebar. I think we should remove those and only list the point releases. The full list is still available elsewhere. But we should not be making it so easy to get versions with known bugs.

**Comment by jseldess** [comment]
@bdarnell, do you have thoughts here? I believe you were involved in changing the sidenav to show just all full releases.

**Comment by bdarnell** [comment]
I think we want that information more accessible than just the full version list; that's why we list the first release of each major/minor version in addition to the latest. Maybe it would be enough to link to the notes for x.y from each x.y.z patch release page. We could also make the download links less prominent in non-latest releases.

**Comment by jseldess** [comment]
I don't know if this change is worth the effort right now, but I'll leave as something to revisit in the future.

**Comment by jseldess** [comment]
Removed 1.0 to make room for 2.1. Closing this for now.
