### ISSUE TITLE
Email signup missing on install page

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2926]
Missing on Mac and Linux download binary and build from source tabs.

Reported by @kannanlakshmi.

**Comment by j-low** [comment]
@jseldess FYI I'm digging into this right now.  It's a strange one but it seems likely that there is a syntax error in the markdown templates that got copy-pasted multiple times causing the missing email input to be absent in multiple instances across multiple pages.  I will update soon with a fix or a status update.

**Comment by j-low** [comment]
I'm a bit confused by this one.  

What's happening is that the email input is different instances of the same Hubspot form which gets populated by a script that calls out to Hubspot's API. What's weird is that _some_ (not all) of those scripts throw errors because the quotes in them get converted into their ASCII code in the browser but _not in the HTML generated from the markdown templates_ (I verified this by checking the generated HTML and it looks valid).  See below:

![ascii_code_single_guotes](https://user-images.githubusercontent.com/6320333/39148527-86f60718-470a-11e8-9c09-cd8d01458629.png)

I've looked over the markdown, the HTML, and the source in devtools each several times and nothing is making itself obvious to me as to why some of the scripts have converted ASCII codes in them while others do not.  @benesch @mjibson do either of you have any thoughts as to what I might be missing here?

**Comment by mjibson** [comment]
I took a look for a few minutes and didn't see anything obvious stand out. I'd start with fixing all of the errors from the w3c validator (https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.cockroachlabs.com%2Fdocs%2Fstable%2Finstall-cockroachdb.html). Maybe that cleanup will fix this or give some clues? Not sure.

**Comment by benesch** [comment]
I'm definitely seeing b0rked HTML being generated in my local _site directory. Pretty sure the problem is with redcarpet's markdown parsing. It's really stupid: https://github.com/vmg/redcarpet/issues/414

**Comment by benesch** [comment]
Here's my proposed fix: https://github.com/cockroachdb/docs/pull/3015
