### ISSUE TITLE
Read from follower with timestamp bound

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2962]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/rec9oRlKSoHf0yPHv
PM: @awoods187 
Eng Partner: @spencerkimball

**Comment by jseldess** [comment]
Follower reads allow non-leaseholder replicas to serve reads under certain conditions that maintain consistency guarantees and stuff.

Estimated scope of docs work:

- Add a bit to the transaction layer docs where reads from the leaseholder are mentioned
- Maybe a separate page with some diagrams to assist with understanding
- ???

See also:

- [Cockroach RFC][rfc]

- [Cockroach PR][pr]


[rfc]: https://github.com/cockroachdb/cockroach/pull/26362
[pr]: https://github.com/cockroachdb/cockroach/pull/21056

**Comment by nstewart** [comment]
This may be going out in today's alpha but the scope and how to use it are not clear from the airtable record or docs @awoods187

**Comment by jseldess** [comment]
Based on comments in airtable, the basic framework is in place, but the feature will not be usable in 2.1. Moving the milestone to 2.2. @awoods187, @tschottdorf, please let me know if I'm wrong and we do, in fact, need docs of some sort for 2.1.

**Comment by tschottdorf** [comment]
You're right, nothing to doc right now.

**Comment by Kiarahmani** [comment]
Hello Team Cockroach!
Sorry to jump in but I am a Ph.D. student at Purdue University avidly waiting for the release of "read-from-follower-replicas" feature*. Following your discussions, my understanding is that it has already been implemented, but you are not planning to make it public yet. If that's the case, can I have a glance at it and maybe get some help on how to use it in a simple setting? Just the syntax and some explanation of what's happening under the hood would suffice. 

Really appreciate your time and considerations in advance!

 *I am basically developing a program analysis framework which allows database applications to **safely** avoid long RTTs on a geo-distributed/replicated databases if possible (you can think about it as _safe injection of stale reads_)

**Comment by tschottdorf** [comment]
Hi @Kiarahmani, we're a bit heads down polishing the next release right now so I don't have too much time to elaborate, but the bulk of the code lives in `pkg/closedts`.

To see what's there to use, look at https://github.com/cockroachdb/cockroach/blob/f3ef41665ac5ef35d20faf534e3db5a826801cda/pkg/storage/closed_timestamp_test.go#L36.

But there's no way to use this as a SQL client yet. You would have to hack around in [this part of the code](https://github.com/cockroachdb/cockroach/blob/f3ef41665ac5ef35d20faf534e3db5a826801cda/pkg/kv/dist_sender.go#L419-L427) to make it such that transactions with timestamps suitably in the past (`ba.Txn.Timestamp`) are routed to the most desirable replica (instead of the leader). In doing so, you'll be in unchartered, untested, and unsupported territory. Sorry!

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3970.
