### ISSUE TITLE
Support ALTER TABLE ... SET TYPE (change column type)

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#2992]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw8IfZMg9Up8SP33/recogtNUGtTUPczhc
PM: @nstewart 
Eng Partners: @mjibson, @dt, @bobvawter

**Comment by jseldess** [comment]
Initial work: https://github.com/cockroachdb/cockroach/pull/25777

**Comment by jseldess** [comment]
@Amruta-Ranade, you can write docs on this. There's a workaround to document in some cases (see the Airtable comments for details).

**Comment by lhirata** [comment]
I'm updating the SQL diagram for ALTER COLUMN and documenting DROP STORED (computed columns, see #3220). Additional updates will need to be made for the other added parameters.

**Comment by Amruta-Ranade** [comment]
Discussion with @mjibson: 
- On-disk representation/format shouldn't change (eg: can't go from STRING to an INT, even if the string is just a number)
- Any validation has to be successful (you can go from STRING[10] to STRING[20], but not to STRING [5])

Eg: TIMESTAMP <> TIMESTAPMTZ because it meets both criteria.

Tests for examples: https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/schemachange/alter_column_type_test.go
Look for things marked "ColumnConversionTrivial"

**Comment by Amruta-Ranade** [comment]
Syntax:

`ALTER TABLE <table_name> ALTER <column_name> TYPE <new_type>;`

**Comment by Amruta-Ranade** [comment]
@andreimatei gave an excellent example: For our TPCC schema, we have a column with decimal (10,2). He changed it to (15,2) when he had more records. But he couldn't have changed it to less than 10 (say, (8,2)) because that invalidates the earlier representation.

**Comment by Amruta-Ranade** [comment]
Doc impact:
- Need a new doc (ALTER TYPE)
- Update the `ALTER TABLE` doc with reference to the new doc.

**Comment by Amruta-Ranade** [comment]
@mjibson Will running `SHOW JOBS` show the change in data type?

**Comment by mjibson** [comment]
No, this doesn't create a job.

**Comment by Amruta-Ranade** [comment]
Closed via https://github.com/cockroachdb/docs/pull/3707
