### ISSUE TITLE
sql: use a reusable name resolution algo for star expansions

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3074]
PR: https://github.com/cockroachdb/cockroach/pull/24811

From release notes:
> It is once again possible to use a simply qualified table name in qualified stars (e.g., `SELECT mydb.kv.* FROM kv`) for compatibility with CockroachDB v1.x. [#24811][#24811] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@knz My initial impression is that there is not any documentation work needed for this bugfix since it has already appeared in the [Release notes](https://www.cockroachlabs.com/docs/releases/v2.0.2.html#bug-fixes).

Do you agree?

FWIW I searched the 2.1 docs for mentions of queries following a similar pattern as the example in the release notes and did not find mention of this bug in known limitations or elsewhere - here is my search:
```
ack -i '\.\* [A-Z]+'
cancel-job.md
40:| 27536791415282 | RESTORE | RESTORE db.* FROM 'azure://backup/db/tbl' |...

grant.md
104:> GRANT SELECT ON TABLE db2.* TO henryroach;

pause-job.md
44:| 27536791415282 | RESTORE | RESTORE db.* FROM 'azure://backup/db/tbl' |...

resume-job.md
42:| 27536791415282 | RESTORE | RESTORE db.* FROM 'azure://backup/db/tbl' |...

revoke.md
144:> REVOKE DELETE ON db2.* FROM betsyroach;

roles.md
219:    > REVOKE ALL ON TABLE test_roles.* FROM system_ops;

show-grants.md
178:> SHOW GRANTS ON TABLE test.* FOR maxroach;

show-jobs.md
59:| 27536791415282 | RESTORE    | RESTORE db.* FROM 'azure://backup/db/tbl' |...
76:| 27536791415282 | RESTORE    | RESTORE db.* FROM 'azure://backup/db/tbl' |...

training/backup-and-restore.md
297:    --execute="RESTORE startrek.* FROM 's3://cockroach-training/[initials]-training?AWS_ACCESS_KEY_ID={{site.training.aws_access_key}}&AWS_SECRET_ACCESS_KEY={{site.training.aws_secret_access_key}}';"

training/security.md
182:    --execute="GRANT SELECT ON startrek.* TO kirk;"

training/users-and-privileges.md
111:    --execute="GRANT SELECT ON TABLE startrek.* TO spock;"
```

**Comment by knz** [comment]
yes indeed no doc change needed here! Thanks for checking.
