### ISSUE TITLE
Document multi-file CSV IMPORT

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#3101]
Re: [IMPORT](https://cockroachlabs.com/docs//v2.0/import.html)

## Issue Description
All docs examples only show single file IMPORT. we need to show multi file import examples since that's the only way to get fast distributed imports.

This loop is really easy to miss: 
![image](https://user-images.githubusercontent.com/894257/39632573-742006bc-4f83-11e8-865f-c5c252a38aaa.png)

**Comment by jseldess** [comment]
Good point, @nstewart. @Amruta-Ranade, this should be a quick fix.

**Comment by Amruta-Ranade** [comment]
With @rmloveland 's migrating PR landing, this issue got more complicated than I expected.
The new synopsis is complicated (and unreadable).
Not all imports support multiple imports. Matt J. suggested breaking up the synopsis based on whether multiple imports are supported.
The scope of the issue is bigger than the Docs FixIt week, so punting it till next week and focusing on clearing smaller issues right now.

**Comment by jseldess** [comment]
From https://github.com/cockroachdb/docs/issues/3911:

> I ran into this with @drewdeally and a customer the other day -- when you run IMPORT TABLE ... CSV DATA (...), you can list multiple import files separated by commas, but the documentation currently doesn't make this obvious. We should specify in the IMPORT statement documentation and the Migrate from CSV guide that you can specify multiple files. (Drive-by nit: we should also fix the railroad diagram for the IMPORT statement so it fits on the page correctly.)

**Comment by jseldess** [comment]
@lhirata, @rolandcrosby, we wanted to get this done for 2.1 but couldn't. This is an important feature to call out, so please consider prioritizing it for 2.2 ops docs work.

**Comment by jseldess** [comment]
@lhirata, this is an easy one for me to take while I update the diagrams.
