### ISSUE TITLE
Duplicate items in search results

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3432]
Algolia seems to be treating the same page (with and without `.html`) as distinct:

![screen shot 2018-07-30 at 11 28 45 am](https://user-images.githubusercontent.com/15893490/43407100-bf6b8f18-93eb-11e8-9603-2cb1623dd038.png)

**Comment by j-low** [comment]
@jseldess I looked over our DocSearch config again but nothing jumped out at me as a likely culprit for this behavior.  I've [filed an issue](https://github.com/algolia/docsearch-configs/issues/510) in the repository.  They're pretty responsive so I should have an update sooner than later.

**Comment by jseldess** [comment]
In addition to duplicate results, links on doc pages (excluding the sidenav) are missing `.html`. 

@mjibson, Joe and I suspect this might have something to do with https://github.com/cockroachdb/docs/pull/3428, which is tied to Perhaps somehow tied to https://www.netlify.com/docs/redirects/#trailing-slash. I think we'll need your help to figure this one out.

**Comment by mjibson** [comment]
@jseldess thanks for finding that. That's exactly what I was looking for when I did #3428. I've disabled the pretty URLs feature in netlify and it *should* fix this.

**Comment by j-low** [comment]
@mjibson I'm seeing something weird.  Last night it looked like this issue was fixed (i.e. I didn't get any dupes in any search I tested) but now I'm getting almost totally empty results for all test searches (e.g. 'data import', 'shard', etc.).

When originally investigating this I filed [this issue](https://github.com/algolia/docsearch-configs/issues/510) with Algolia.  The final comment mentions updating our sitemap without `.html` appended to the paths.  Is it possible the empty results are related to our sitemap still using the appended `.html` strings?

**Comment by j-low** [comment]
Alright, so there was an update that needed to be made to the Algolia config to further accommodate the `.html`-less URL scheme.  Everything [appears to be working](https://www.cockroachlabs.com/docs/search.html?q=data+import) at this point.

**Comment by j-low** [comment]
@mjibson when I navigate to a page without `.html` appended it still opens/highlights the correct link in the sidenav so I think we're okay here.
