### ISSUE TITLE
ts: Enable Rollups

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3443]
PR: https://github.com/cockroachdb/cockroach/pull/27121

From release notes:
> The time series system used by CockroachDB to store internal monitoring data now utilizes pre-computed rollups to significantly increase the duration for which monitoring data is available while using less storage. Monitoring data will be available for up to a year by default; however, data older than seven days will be stored at a reduced resolution, and thus will only be able to give details about 30 minute intervals. [#27121][#27121] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
Also from https://github.com/cockroachdb/docs/issues/3130:

Related:

- cockroach issue to implement ts rollup: [#21601](https://github.com/cockroachdb/cockroach/issues/21601)
- [time series culling RFC](https://github.com/cockroachdb/cockroach/blob/096f61414d2821d629935f5fd5cafe54b4c1ed24/docs/RFCS/20160901_time_series_culling.md)

This may affect (at least?) the following docs:

- [FAQ re: how CRDB stores time series data](https://www.cockroachlabs.com/docs/stable/operational-faqs.html#can-i-reduce-or-disable-the-storage-of-timeseries-data-new-in-v2-0)

I didn't find much else that talked about time series storage requirements via [this search](https://www.cockroachlabs.com/docs/search.html?q=time%20series).

Tobias says we may add a new cluster setting.  Will coordinate with @mrtracy who is implementing this.

**Comment by rmloveland** [comment]
@tbg - triaging some old docs issues and wanted your input on this one.

This issue is about documenting time series rollups.

The [cluster settings page](https://www.cockroachlabs.com/docs/stable/cluster-settings.html) documents that rollups exist when it says re: `timeseries.storage.resolution_10s.ttl` that

> the maximum age of time series data stored at the 10 second resolution. Data older than this is subject to rollup and deletion.

I tend to view the rollup algorithm as an internal space-saving optimization used by the time series machinery (?) and as such I'd rather not document it in more detail than we already have on the cluster setting.  

Also, we already document answers to timeseries-related disk usage questions in our [Operational FAQs](https://www.cockroachlabs.com/docs/stable/operational-faqs.html#why-is-disk-usage-increasing-despite-lack-of-writes) and mention how to change the intervals, turn off TS, etc.

Given the above, I'd like to close this issue.  Any objections?

**Comment by tbg** [comment]
Sounds good, thanks Rich!
