### ISSUE TITLE
Add known limitation for 2.2 (and all versions before) about queue-like workloads

### ISSUE THREAD

**Issue by tbg** [cockroachdb/docs#3551]
Basically https://github.com/facebook/rocksdb/wiki/Implement-Queue-Service-Using-RocksDB applies verbatim to CockroachDB.

If consumers implement a naive queue (as a table), they will see reduced performance over time (due to having to traverse the deleted keyspace over and over again when querying). The suggested workaround is for each client to keep a lower and upper bound as they query the table, though this isn't generally possible.

As an example in which it works: assume the client uses a table like `(timestamp int primary key, payload bytes)` and they know that new items are always inserted with a "current timestamp".

Instead of getting the oldest item via `SELECT timestamp, payload FROM queue ORDER BY timestamp ASC LIMIT 1` all the time, they would do that only once (resulting in `past_oldest_timestamp`), then would add a `WHERE timestamp >= min(past_oldest_timestamp, NOW() - INTERVAL '1 HOUR') AND timestamp < NOW() + INTERVAL '1 HOUR'`.

(the `timestamp < ....` condition serves to avoid running into the tombstones of an adjacent table and may not be necessary, not sure right now).

**Comment by rmloveland** [comment]
@tbg does this limitation still apply to versions of CockroachDB > 2.2 ?

In particular, does it apply to versions 19.1, 19.2, and 20.1?

**Comment by jseldess** [comment]
@rmloveland, I actually added this related error description guidance at some point: https://www.cockroachlabs.com/docs/stable/common-errors.html#split-failed-while-applying-backpressure-are-rows-updated-in-a-tight-loop. Maybe sufficient?

**Comment by rmloveland** [comment]
Jesse Seldess <notifications@github.com> writes:

> @rmloveland, I actually added this related error description guidance
> at some point:
> https://www.cockroachlabs.com/docs/stable/common-errors.html#split-failed-while-applying-backpressure-are-rows-updated-in-a-tight-loop.
> Maybe sufficient?

Hey that's great!  It provides a great base on which to build, since it
looks like you did the actual hard part, explaining the core of the
issue.

In particular everything from "to resolve this issue ..." on seems like
it could be broken into an include and added to several other areas of
the docs.

In that case it seems like the bulk of the work needed here is making
this more discoverable in several places where we talk about
performance.  We probably want to make sure the phrases "queue" and
"queue-like workloads" get into the docs and are (a bit more)
searchable.

Does that sound about right?

**Comment by ericharmeling** [comment]
Closing this issue, as it appears that it was addressed in https://www.cockroachlabs.com/docs/stable/common-errors.html#split-failed-while-applying-backpressure-are-rows-updated-in-a-tight-loop.
