### ISSUE TITLE
Explaining IDENT

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#358]
IDENT shows up in the SQL grammar a number of times but its value and function isn't clearly defined anywhere. Having a doc targeted to devs looking up IDENT that works as reference material should cover that.

**Comment by sploiselle** [comment]
@jseldess Drafted this doc, but wasn't aware of identifiers doc, nor the ability to also turn something into `IDENT` using double quotes. Will add that to next iteration of the docs:

https://github.com/sploiselle/docs/blob/whatIsIdent/ident.md

**Comment by jseldess** [comment]
Thanks, @sploiselle. Since there's already a page about identifiers, though, I'd prefer that you think about how to adjust/expand that page rather than create a new one. You up for that? Also, since one of our main style guidelines is "concision" (don't want users to have to read much to get what they need), I'd appreciate you carefully choosing what additional info is important for users to have. We can go back and forth here on that, if you like. 

One other point: If `IDENT` is redundant in the `DELETE` synopsis, we can exclude it from the diagram. I think that may have been the outcome of your gitter change, but I'm not sure. If so, feel free to open another issue to have that done. 

Thanks!

**Comment by sploiselle** [comment]
@jseldess Up for integrating the info into the identifiers doc! The typical convention from other SQL folks is to title this around "keywords" instead of "identifiers." Would you be open to changing the title?

It also turns out the `IDENT` isn't redundant; it's actually a really fussy complication of the syntax allowing someone to use `AS` optionally.

**Comment by sploiselle** [comment]
💡 – disregard the questions. Have an idea for simplifying a bunch of this.

Change 'Identifiers' article into 'Identifiers (IDENT)' – yard out info about parser
Change 'SQL Keywords' article to rely on the 'Identifiers (IDENT)' article for simplification

**Comment by jseldess** [comment]
Yeah, I like that direction. Let's just rename "Identifiers" to "Identifiers and Keywords" and cover both concepts on the page. We don't need `IDENT` in the title if we reference it on page; that should do for search results. 

This is a similar approach to [Postgres](https://www.postgresql.org/docs/9.5/static/sql-syntax-lexical.html) (see 4.1.1).

**Comment by bdarnell** [comment]
We should really be hiding `IDENT` from the grammar diagrams, or at least styling it differently (lowercase, instead of looking like a verbatim keyword). In most cases I think we should treat things like "name" as terminal elements in the grammar instead of expanding "name" into "IDENT or unreserved_keyword or col_name_keyword".

**Comment by sploiselle** [comment]
@bdarnell – If `IDENT` was expressed as `identifier` the grammar (and the resulting grammar diagrams), I think that would be the gold star.

_In the weeds a little bit_:
The grammar diagrams currently do a great job of hiding `IDENT` – making things like `name` the terminal element like you're suggesting. The place (the only one) it shows up as a statement is in [`DELETE`'s diagram](https://www.cockroachlabs.com/docs/delete.html) (where it's surfacing the syntax of [`target_elem`](https://www.cockroachlabs.com/docs/sql-grammar.html#target_elem)).

`IDENT` could be totally obfuscated, though, with a new element of the grammar (`change_col_label`?) but that feels a little like an over-engineered solution (which would still benefit from the other proposal, converting `IDENT` to `identifier`).

**Comment by jseldess** [comment]
@bdarnell, @sploiselle, opened a separate issue to change `IDENT` to `identifier` throughout grammar.
