### ISSUE TITLE
CDC: Document recommended monitoring/alerting setup in production 

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/docs#3791]
When using CDC in production, operators will need to pay close attention to their changefeeds' health metrics to ensure that changefeeds don't get cancelled or experience high latency. I'm not sure where this should be in the docs -- maybe a new page in the Deploy section, or something referenced from the production checklist page -- but we should document all the important metrics and perhaps even provide recommended alerting rules.

This doesn't need to be done in time for the 2.1.0 release; we can revisit during the 2.1.x timeframe, as we will be doing more work on the CDC implementation during that period.

cc @danhhz

**Comment by jseldess** [comment]
@rolandcrosby, are these metrics available via our prometheus endpoint? If so, we could expand the "Events to alert on" section of https://www.cockroachlabs.com/docs/dev/monitoring-and-alerting.html.

**Comment by danhhz** [comment]
The metric of interest is `changefeed.min_high_water`, which is the current high-water timestamp in nanos of the _most behind_ changefeed if there are any, or a very large number otherwise. It works in the custom graph debug page. I don't know if there's anything else we have to do to make it show up in prometheus.

A user alert for this would be on something like `now() - changefeed.min_high_water > [some threshold]` where the threshold depends on the gc ttls they have set in their cluster. (This is admittedly quite awkward, but it was the best we could do for 2.1)

**Comment by jseldess** [comment]
Thanks. I don't think this jnfo would be too hard to add. @lhirata, your call whether we do that now or as a 2.2 follow-up. @danhhz, @rolandcrosby, on the dev side, it might be nice to add actual rules to our default Alert Manager config. That could be a small roadmap item even (Out-of-the-box monitoring of CDC or something like that).

**Comment by rolandcrosby** [comment]
@lhirata I think this issue accounts for the "operators need to track when their changefeeds' high water marks are at risk of falling behind the cluster's GC window" issue that I called out in this week's meeting notes. Let me know if you need any further clarification.

**Comment by lhirata** [comment]
This is now `changefeed.max_behind_nanos`, per #4457.
