### ISSUE TITLE
Running `make test` locally kills my mac

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3833]
I ran `make test` to check links locally. I got a panic and pretty much all applications on my machine froze. I force quit everything, but still have to force reboot. 

@mjibson thinks it may be because `hmtltest` opens up too many files at once.

**Comment by benesch** [comment]
Huh. Does this reproduce reliably?

**Comment by jseldess** [comment]
I'll try again in a few. Want to finish some work first, in case my computer dies again.

**Comment by benesch** [comment]
Yeah, totally understandable.

**Comment by mjibson** [comment]
I ran this on a linux machine and it panic'd also. Didn't hose the machine but definitely broke.

**Comment by mjibson** [comment]
Also I'm planning on looking into this once I finish the website stuff.

**Comment by rmloveland** [comment]
@jseldess not a fix, but i am able to run `make test` to (failed) completion on my MBP because I bumped the default # of per-process open files (it's absurdly low by default, something like 256 IIRC).

These instructions worked for me:
https://gist.github.com/tombigel/d503800a282fcadbee14b537735d202c

**Comment by otan** [comment]
we could also change the concurrency factor to be friendlier on local computers -- `DocumentConcurrencyLimit` defaults to 128, we could make this 16 except on CI.
