### ISSUE TITLE
Refactor install-cockroachdb.md

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#385]
The page is entirely HTML. Instead, we should use the `markdown="1"` attribute to enable Markdown within HTML, wherever possible. Example:

```
<div id="blah" markdown="1">
Now I can type Markdown within this div!

## Header 2

- bullet
- bullet
</div>
```

**Comment by jess-edwards** [comment]
@jseldess 
I've asked DivisionOf for advice on optimizing the docs site for search. I'm going to ask that they do some research into markdown vs html for SEO because there is an explicit "SEO point" you earn with regards to the text in an H1 tag. I want to be sure that search crawlers are evolved enough to give markdown equal credit.

**Comment by jess-edwards** [comment]
This is HubSpot's SEO review of the install page: 
![screen shot 2016-06-15 at 12 35 29 pm](https://cloud.githubusercontent.com/assets/6042450/16088568/bb90e1bc-32f5-11e6-80c5-dbad7b6ec698.png)

**Comment by jseldess** [comment]
Thanks, Jess. I can definitely look into adding meta and alt text for
images. As we discussed over lunch, markdown isn't a problem, since the
docs pages on our site are transformed into html.

**Comment by jseldess** [comment]
This turns out to be harder than I thought. For now, it's not worth the effort. I'll just leave the page in html. But I'll open separate issues to address the page meta and alt text for images.
