### ISSUE TITLE
Don't run more than one clock sync service

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3856]
Customers have experienced problems when running more than one clock sync service on VMs running `cockroach` nodes. We should add a clear warning not to do this.

For example, our [AWS deployment tutorial](https://www.cockroachlabs.com/docs/stable/deploy-cockroachdb-on-aws.html#step-3-synchronize-clocks) suggests to use [Amazon's Time Sync Service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/set-time.html#configure-amazon-time-service-amazon-linux), and their docs suggest using `chrony`. If NTP is also running on those machines, you have problems.

**Comment by bdarnell** [comment]
Our docs recommend `ntpd` because it's available on all linux distributions, but it's not the default any more in most cases (nor is it the best choice - my understanding is that `chrony` is the best when it's available because it supports both client- and server-side leap smearing). 

Instead of telling people to uninstall their other time sync service and install ntpd instead, we should provide instructions for configuring the three (I think) main options: `ntpd`, `chrony`, and `systemd-timesyncd`. 

Additionally, we should probably be telling people that if they are using a time source that doesn't do server-side leap smearing, they should either switch to one that does (i.e. google or amazon) or use `chrony` and enable client-side leap smearing. It's also important that if they're using `chrony` and switch from some other time source to google or amazon that they ensure client-side leap smearing is disabled.

**Comment by jseldess** [comment]
Update:

- We should make it clear that you only want one time sync program running on VMs where cockroach is running. 
- We should still recommend using google or amazon clock service but with whatever time sync program they are already using. So if they're already using ntp, configure ntp to point to the google or amazon time server. Likewise for chrony.
- As an advanced option, users who'd rather not use google or amazon can use chrony and enable client side leap smearing (unless they're using a clock source that does server-side smearing).

**Comment by bdarnell** [comment]
And for the choice between google and amazon's time servers: Amazon's time server is only available within EC2, so hybrid environments should use google's instead.

For reference, redhat has some docs on options for handling leap seconds: https://access.redhat.com/articles/15145

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/3936.
