### ISSUE TITLE
release-2.1: mysql import polish fixes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3899]
PR: https://github.com/cockroachdb/cockroach/pull/31305

From release notes:
> Handle binary fields dumped by `mysqldump v5.7.23` with `_binary` prefix. [#31305][#31305] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@rmloveland, not sure if this requires a docs update?

**Comment by rmloveland** [comment]
@dt it doesn't seem like this warrants a doc update, since AFAICT we don't get into this level of detail about the dump format in either the [`IMPORT`](https://www.cockroachlabs.com/docs/v2.1/import.html) or [Migrate from MySQL](https://www.cockroachlabs.com/docs/v2.1/migrate-from-mysql.html) docs.

Do you agree?

**Comment by rmloveland** [comment]
Closing as I believe this does not require a doc update.

@dt if you disagree please shout!  Thanks.
