### ISSUE TITLE
[MH] Support remaining read only features for cost-based optimizer

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#3997]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recP23Xb7EdhOymAm
PM: @awoods187 
Eng: @andy-kimball

**Comment by awoods187** [comment]
I believe that Window Functions are the only read-only query type not supported by the CBO. Is that correct @andy-kimball ?

**Comment by rmloveland** [comment]
Since our [19.1 CBO docs](https://www.cockroachlabs.com/docs/v19.1/cost-based-optimizer.html#types-of-statements-supported-by-the-cost-based-optimizer) currently say the following stmts are supported

> All SELECT statements that do not include window functions
> All UNION statements that do not include window functions
> All VALUES statements that do not include window functions

I don't think there is additional docs work needed here.

@awoods187 or @andy-kimball , please re-open if you disagree.
