### ISSUE TITLE
Use jobs infrastructure for schema changes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4015]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viw5Jsp2TrY3it9Yr/recoIfwx7vj4qsshU
PM: @awoods187 
Eng: @vivekmenezes

**Comment by rmloveland** [comment]
@vivekmenezes I have looked at the code to try to determine which schema change statements run as jobs, and came up with the following list (checked = runs as a job).  Can you confirm if this is correct?

- [ ] ALTER DATABASE
- [X] ALTER INDEX
- [ ] ALTER RANGE
- [ ] ALTER SEQUENCE
- [X] ALTER TABLE
- [ ] ALTER VIEW
- [ ] CREATE DATABASE
- [X] CREATE INDEX
- [ ] CREATE SEQUENCE
- [ ] CREATE TABLE
- [ ] CREATE VIEW
- [X] DROP DATABASE
- [X] DROP INDEX
- [ ] DROP SEQUENCE
- [X] DROP TABLE
- [ ] DROP VIEW
- [X] TRUNCATE

It seems like the docs work here will be (roughly):

- Update docs for some statements to say they run as jobs, can be managed using the jobs infrastructure (SHOW JOBS, etc.)
- Noting if there are any special cases in the above (e.g., "don't pause and resume an ALTER INDEX job under conditions ABC because XYZ will happen")
- ??? (other things I can't think of)

**Comment by awoods187** [comment]
These should all be jobs--I'll file an issue https://github.com/cockroachdb/cockroach/issues/35514

Awesome work @rmloveland

**Comment by rmloveland** [comment]
Thanks Andy!  In light of our discussion, I'll move this issue to the 19.2 milestone since I can't really work on it yet.  (As always, shout if you disagree.)

**Comment by jseldess** [comment]
@rmloveland, seems like we've updated the docs as far as possible for 19.1, is that right? If so, would you mind closing this and opening a follow-up issue for the remaining work. In principle, that remaining work should be on the 19.2 roadmap anyway, if it's prioritized.

**Comment by rmloveland** [comment]
> @rmloveland, seems like we've updated the docs as far as possible for 19.1, is that right?

Not yet - I prematurely bumped this issue to 19.2.

The remaining work is to ensure the statements listed above with checkmarks are tagged as visible using `SHOW JOBS`.

I'll do that and PR it ASAP, then make the follow-up issue for 19.2.
