### ISSUE TITLE
Some SQL diagrams don't wrap or scroll

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/docs#4026]
For some larger SQL diagrams that overflow the main text box, the diagram doesn't wrap and the page doesn't horizontally scroll. The end of the diagrams are cut off.

Example: https://www.cockroachlabs.com/docs/v2.1/import.html

**Comment by mjibson** [comment]
This isn't a bug so much as it is a reality. A diagram can only wrap when all forks have been joined. The example diagram above has a bunch of forks, one of which is very wide, and so it won't wrap. Possible fixes are:

1. Change the diagrams to inline fewer things to make them less wide.
2. Split up the diagrams so that there are fewer forks, hopefully allowing it to wrap at more points.

**Comment by jseldess** [comment]
Thanks, @mjibson. In the meantime, I wonder if it's an easy fix to allow horizontal scrolling? I remember this being allowed in the past. Perhaps the toc in the right margin changed things.

**Comment by mjibson** [comment]
Yes, that sounds doable. There should be some CSS we can add to an SVG to enable horiz scrolling if it's too wide.

**Comment by jseldess** [comment]
This same inability to scroll the main body right is affecting other pages, like https://www.cockroachlabs.com/docs/stable/cluster-settings.html#settings. 

@j-low, can you take a quick look at this? Is there a quick css fix to allow scrolling the main body to the right in cases where the right margin (with toc) is overlapping content?
