### ISSUE TITLE
importccl: fix the UX of the IMPORT statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4065]
PR: https://github.com/cockroachdb/cockroach/pull/31263

From release notes:
> The [`IMPORT format (file)`](../v2.2/import.html) syntax is deprecated in favor of `IMPORT format file`. Similarly, `IMPORT TABLE ... FROM format (file)` is deprecated in favor of `IMPORT TABLE ... FROM format file`. [#31263][#31263] {% comment %}doc{% endcomment %}

**Comment by Amruta-Ranade** [comment]
AFAICT, the docs already document this: https://www.cockroachlabs.com/docs/dev/import.html
Verified with @rolandcrosby 
@knz Please correct me if I am wrong.

**Comment by knz** [comment]
IMHO the syntax diagram is confusing.

There are really two separate syntaxes for IMPORT which should be presented side-by-side, not in a single syntax diagram:

```
root@127.238.0.39:34985/defaultdb> \h import
Command:     IMPORT
Description: load data from file in a distributed manner
Category:    enterprise features
Syntax:
-- Import both schema and table data:
IMPORT [ TABLE <tablename> FROM ]
       <format> <datafile>
       [ WITH <option> [= <value>] [, ...] ]

-- Import using specific schema, use only table data from external file:
IMPORT TABLE <tablename>
       { ( <elements> ) | CREATE USING <schemafile> }
       <format>
       DATA ( <datafile> [, ...] )
       [ WITH <option> [= <value>] [, ...] ]

Formats:
   CSV
   MYSQLOUTFILE
   MYSQLDUMP (mysqldump's SQL output)
   PGCOPY
   PGDUMP

Options:
   distributed = '...'
   sstsize = '...'
   temp = '...'
   delimiter = '...'      [CSV, PGCOPY-specific]
   nullif = '...'         [CSV, PGCOPY-specific]
   comment = '...'        [CSV-specific]

See also:
  SHOW TABLES
  CREATE TABLE
```

The doc page does not sufficiently explain that there are two "families" / "kinds" of IMPORT statements. This should be clarified.

**Comment by Amruta-Ranade** [comment]
I agree that the diagram is confusing, but I can trace the use-cases through it. I am not sure if we can have multiple diagrams for the same statement ( -- Haven't worked on SQL docs in a while). 

@rmloveland @jseldess I need help figuring this out.

**Comment by rmloveland** [comment]
I think we are really discussing two separate issues / work items:

1. Update current page's examples to not use the parens anymore / note they are deprecated (this issue)

2. Update the IMPORT syntax diagram to improve the UX to address Raphael's comments -- which I agree with -- in a separate issue.  This may require rethinking how we generate these diagrams, since (AFAICT) nobody on the docs team yet knows how to create multiple diagrams for one statement, and in fact most team members find dealing with the diagrams difficult in general.

Meta: FWIW I don't think a syntax deprecation of this type (i.e. "remove the parens") should be a P-1 issue that must be updated by the 19.1 release.  Deprecation is not the same as removal, and all of the existing examples should work as they are.  IMO this sort of small syntax change should be a P-2 that is updated on an as-soon-as-possible basis; it's not as important as some other work items in flight for the release.

**Comment by Amruta-Ranade** [comment]
Thanks @rmloveland ! This is very helpful.
1. I think the docs already address this (AFAICT, the examples correctly use /don't use the parens). Please let me know if I am wrong.
2. Yes! I have no idea how to generate multiple diagrams for the same statement. 

I completely agree that syntax deprecation issues should not be P-1.

**Comment by jseldess** [comment]
I agree with the above but also feel like it should be possible to spend a few hours to improve the diagram. Creating two distinct diagrams is simply a matter of defining two distinct objects in [`diagrams.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/docgen/diagrams.go#L323). It's totally possible for more than one object to use the same `stmt`, e.g.:

```
 	{
		name: "import_schema_data_from_file",
		stmt: "import_stmt",
                ...
        },
 	{
		name: "import_data_from_file",
		stmt: "import_stmt",
                ...
        }
```

**Comment by jseldess** [comment]
Also, @lhirata has a bunch of other `IMPORT`-related issues, so it probably makes more sense to assign to her, and I can work with her to figure this out. I'm happy to take on the diagram regeneration.

**Comment by Amruta-Ranade** [comment]
SGTM. FWIW, I think we should have a SQL diagram generation refresher session post-19.1.
