### ISSUE TITLE
Update Detailed SQL Support doc with latest information as of v19.2

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4090]
Relates to #1340 .

Estimated scope of work:

1. Update [Detailed SQL standard comparison](https://www.cockroachlabs.com/docs/stable/detailed-sql-support.html) to match the current reality
2. See what other work (if any) falls out of the above, and either do it or file issues/plan it for later

**Comment by rmloveland** [comment]
@awoods187 now that we're in 19.2 world, do you think we should either:

1. Close / drop this?

2. Edit it to say "latest information as of 19.2"?

3. Something else?

If you prefer # 2, I don't think @ericharmeling or I could work on this until after the 19.2 release at this point.

**Comment by awoods187** [comment]
Let's talk about this in our next meeting. Its a huge effort and I wonder if we could automate it or otherwise make it easier to complete. Pull something from SQL.Y? maybe @knz has ideas on something we could do here. I do think it would be valuable to show up to date information.

**Comment by knz** [comment]
Do you still have the spreadsheet?

I remember from last time, filling in the feature sheet from top to bottom would only take a dozen minutes for a seasoned engineer with horizontal familiarity with our SQL codebase. I'm a bit rusty but I'm willing to have a look, otherwise I'm sure mattj jordan or radu could help too.

Once you have the new information, your work will be reduced to analyzing the differences in the new and old sheet (perhaps we can organize using different columns so you can use a formula to highlight) and structuring that to be palatable to readers.

That said I can already predict that we won't have too many changes actually. I think it will be restricted mostly to correlated subqueries and window functions. But I agree it's important to update the support table nonetheless.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by knz** [comment]
I have updated the spreadsheet with a separate column for 19.2 compared to 19.1. For a few items you'll need to ask other team members, for each of them I listed the name(s) you need to reach out to.

**Comment by awoods187** [comment]
Thanks @knz this was a lot of work and we appreciate it. I've added comments for all of the other engineers to check and we can have this updated soon.

**Comment by rafiss** [comment]
@rmloveland I was curious if there are still plans to publish the new information. I'm asking because we are working with some external developers who are adding CockroachDB support to their ORM, and they found this page on their own and ended up with some incorrect conclusions about what we support now. Perhaps if we don't have the time to update the page, it would be better to unpublish it from the site for now?

**Comment by rmloveland** [comment]
@rafiss good question, I haven't thought about this issue in a while.  Right now my main focus for the rest of Q4 is #5865 (Developer Guide) but I agree this is important.  In fact our current doc is "broken" so this is really a doc bug at this point.

Assigning myself and I'll work on this for Q4 (by end of January).

**Comment by awoods187** [comment]
@rmloveland let us know if we can help.

**Comment by rmloveland** [comment]
I never got to this and have to admit that I'm probably not going to work on it soon.  Unassigning so we can reprioritize / reassign if this is still important for 20.1

**Comment by rafiss** [comment]
I don't think it's important to update everything. But since the information is inaccurate, could we simply remove the page from the docs (at least for versions >= 19.1)? Would that be quicker and more feasible?

**Comment by rmloveland** [comment]
> But since the information is inaccurate, could we simply remove the page from the docs (at least for versions >= 19.1)?

That would be my vote at this point.  I agree that it's better not to have wrong/outdated info.

@jseldess what do you think of this idea?

**Comment by knz** [comment]
FWIW I can do the update of the spreadsheet like I did in September. It's not too much effort for me.

**Comment by jseldess** [comment]
Sorry for my delay. Just look at some docs analytics. Since 1/1/20, this detailed SQL support page has gotten 572 unique views, whereas the SQL feature support overview page has gotten 2534. 

My opinion is that it's ok to remove this page and put in a redirect to the SQL feature support page, and dedicate ourselves to expanding and updating that page going forward. @awoods187, are you ok with that? I'll want to check with the field teams and make sure they're not relying on this page as well.

**Comment by jseldess** [comment]
After further discussion on Slack, we'll stop building this page but leave the file around for updating at a later time, if we decide to. Sounds like it's especially useful for third-party tool developers.
