### ISSUE TITLE
Training updates for next classroom session

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4128]
For an upcoming classroom training (spread over 2 days, 2 3-hour sessions per day), we need to fill some gaps in our "CockroachDB 101" training content:

- [x] Add Geo-partitioning training after [Locality and Replication Zones](https://www.cockroachlabs.com/docs/stable/training/locality-and-replication-zones.html). Can leverage https://www.cockroachlabs.com/docs/stable/performance-tuning.html and https://www.cockroachlabs.com/docs/stable/partitioning.html.
- [x] Update deck for [Locality and Replication Zones](https://www.cockroachlabs.com/docs/stable/training/locality-and-replication-zones.html) training show two-level locality, country/continent as level 2, region as level 2.
- [x] Create k8s training module. Probably repurpose https://www.cockroachlabs.com/docs/stable/orchestrate-a-local-cluster-with-kubernetes-insecure.html. Probably focus on helm.
- [x] Update data import lab and slides to cover IMPORT postgres/mysql.
- [x] Stress testing: Maybe create a module on TPC-C benchmarking, based on https://www.cockroachlabs.com/docs/stable/performance-benchmarking-with-tpc-c.html. 
- [x] Do a run-through of entire process on Windows.
    - What tools to install to do this successfully?
    - Install VirtualBox on Spencer's windows machine and test this out. 
    (Deemed not necessary, since they will have access to linux ec2 vms).
- [x] Break down schedule for 2 days.

We may need some content in terms of "client tools" as well. TBD.

@bdarnell, if you have other thoughts, please add them.

**Comment by jseldess** [comment]
VirtualBox install guidance:

[Installing Cockroachdb in VirtualBox.docx.pdf](https://github.com/cockroachdb/docs/files/2668733/Installing.Cockroachdb.in.VirtualBox.docx.pdf)

**Comment by bdarnell** [comment]
A few more things I noticed as I went through the training:
- The cluster upgrade page should be updated to discuss preserve_downgrade_option. The slides (but not the text) still have some references to upgrading from 1.1 to 2.0, which is no longer relevant.
- The backup/restore page has embedded a trial license, which I assume has expired. We may want a different way of handling this. 
- The order of locality, data import, and sql basics is weird. I think I'd prefer them in the reverse order (or data import, sql basics, then locality, if sql basics refers to data that was loaded in the import step)
- In the planned maintenance section, we should discuss the pros and cons of changing time_until_store_dead (setting this too high creates some risk of unavailability since we don't respond to down nodes as quickly, but setting it too low causes increased network and disk I/O costs as we rebalance data around temporary outages). The last step can use the `RESET CLUSTER SETTING` command instead of repeating the default. 
- The decommissioning page uses `quit --decommission` instead of the `decommission` command. That's only useful for toy deployments; in real usage you'd use `cockroach decommission` and then instruct your process manager to kill the process. We should at least refer to this possibility here. 
- The data corruption troubleshooting page can just delete one of the sst files instead of opening it in a text editor and making garbage changes, i think. 
- The network partition troubleshooting page uses docker-compose; it would be nice if that one could be rewritten to use minikube.

**Comment by jseldess** [comment]
@bdarnell, I've integrated most of your requests into the main list above. The following 2 I think are less important, though nice to have. For network partitioning, Alex or Peter just demoed that module; users didn't complete it themselves.

- The order of locality, data import, and sql basics is weird. I think I'd prefer them in the reverse order (or data import, sql basics, then locality, if sql basics refers to data that was loaded in the import step)
- The network partition troubleshooting page uses docker-compose; it would be nice if that one could be rewritten to use minikube.

**Comment by bdarnell** [comment]
In https://www.cockroachlabs.com/docs/stable/training/fault-tolerance-and-automated-repair.html#step-7-prepare-for-two-simultaneous-node-failures

> At this point, the cluster is in a vulnerable state. With a replication factor of 3, if any of the 4 remaining nodes die, the cluster will lose access to at least some of its ranges.

We just watched the replica count on node 5 drop to zero in the previous step, so at this point the cluster is safe. It can lose another node without any nodes becoming unavailable. The window of vulnerability was the ~90 seconds during which node 5 was down but its data had not been rebalanced. 

Suggested edit:

At this point, the cluster has recovered and is ready to handle another failure. However, the cluster cannot handle two *near-simultaneous* failures in this configuration. Failures are near-simultaneous if they are closer together than the `server.time_until_store_dead` setting plus the time taken for the number of replicas on the dead node to drop to zero. If two failures occurred in this configuration, some ranges would become unavailable until one of the nodes recovers.

**Comment by bdarnell** [comment]
"Secure Your Cluster" page:

Due to https://github.com/cockroachdb/cockroach/issues/32254, you can't perform any grants within 5 minutes of a node experiencing an unclean shutdown (the grant command will just hang; this will be fixed in 2.1.4). We do an unclean shutdown to convert the insecure cluster to secure. We may want to reconsider this - converting from insecure to secure isn't a realistic scenario (or at least it shouldn't be something we encourage. it's important to be secure from the beginning). I think it would be better to do a wipe and restart at this point instead of restarting the existing cluster.

I also think it would be better to introduce security *before* users and grants (so we never bother with non-root users in insecure clusters), but that's a larger refactoring of these two pages.

**Comment by bdarnell** [comment]
https://www.cockroachlabs.com/docs/stable/training/data-unavailability-troubleshooting.html

We can run `cockroach init` after we started the first node; then the node IDs will be assigned in order for the remaining nodes which will avoid a little confusion.

Step 2.2 should have an equals sign instead of a colon after `constraints`, and it's missing a `./` at the beginning of the command.

Step 2.3 has trailing whitespace after the backslash again.

**Comment by bdarnell** [comment]
The docker-compose file used in the Network Partition Troubleshooting page defaults to version 2.0.0. Either the docker-compose.yaml file should be updated to specify 2.1.3 or the `docker-compose up` step should be `COCKROACH_VERSION=v2.1.3 docker-compose up` (the latter could be I think be parameterized to automatically pick up the latest stable version)

The Cluster Upgrade page starts with 2.0.5, and it looks like that binary crashes on recent versions of macOS. This should be updated to start with 2.0.7. 

Backup and Restore:

- Step 2.3 should have `>` instead of `$` on the last line (before `startrek_backup.sql`)
-Step 3.1 has whitespace after backslash
- Step 4.2 refers to "initials"; it should probably just say "name" since not all languages have a concept of initials. 

This page has a license in it that you can just copy/paste; the new geo-partitioning page says you should apply for a trial license. We should handle this the same way on both pages (I'd prefer something to copy/paste instead of sending everyone to request trial licenses)

**Comment by lhirata** [comment]
Addressed Ben's feedback on this issue (other than the reordering pages and rewriting the network partition page with minikube) with [this commit](https://github.com/cockroachdb/docs/pull/4214/commits/45aa1db45e03a2e6df0402230c0aaf45d4c3242d). Will update the outstanding suggestions if I have time.

**Comment by lhirata** [comment]
Working on adding a TPC-C module today / tomorrow.

**Comment by lhirata** [comment]
@jseldess - following up on TPC-C: Started thinking about what the training module would look like and I'm unsure of how to proceed. If we do benchmarking on a 1000 warehouse dataset, just the data loading takes about 40 minutes. This probably isn't ideal for a training scenario. Should we do a smaller dataset (although, I'm not sure that really demonstrates stress-testing)? Is there a faster way to load data?

**Comment by bdarnell** [comment]
The data loading gets even worse when everyone in the class is trying to download it at once. I think for the class we'd demonstrate something very small (probably 10 warehouses) and point out that larger datasets are available for further testing (outside of the training session).

**Comment by lhirata** [comment]
@bdarnell ok sounds good. The training should be with local clusters, right (not GCE)?
