### ISSUE TITLE
sql: fix FK validation join implementation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4361]
PR: https://github.com/cockroachdb/cockroach/pull/34365

From release notes:
> [`VALIDATE CONSTRAINT`](../v2.2/validate-constraint.html) is now compatible with the new `MATCH FULL` and `MATCH SIMPLE` foreign key semantics and is more performant. [#34365][#34365] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@rmloveland, not sure if/how this affects docs.

**Comment by rmloveland** [comment]
@lucy-zhang ,

Based on my reading of the release note, this appears to be a bugfix/perf thing that does not affect the existing [`VALIDATE CONSTRAINT`](https://www.cockroachlabs.com/docs/dev/validate-constraint.html) docs, since (1) the docs don't mention this specific case (nor its performance), and (2) AFAICT your PR changes the behavior to what a user would expect.  Do you agree with that assessment?

**Comment by lucy-zhang** [comment]
@rmloveland yes, I agree

**Comment by rmloveland** [comment]
Thanks! Closing...
