### ISSUE TITLE
opt: add support for aggregate FILTER

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4365]
PR: https://github.com/cockroachdb/cockroach/pull/34077

From release notes:
> `FILTER` expressions are now supported by the cost-based optimizer. [#34077][#34077] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@rmloveland, does the `unsupported statement` error here need to be changed given the above? https://www.cockroachlabs.com/docs/v2.2/cost-based-optimizer.html#view-query-plan

**Comment by rmloveland** [comment]
> @rmloveland, does the unsupported statement error here need to be changed given the above? https://www.cockroachlabs.com/docs/v2.2/cost-based-optimizer.html#view-query-plan

Yes.  I considered doing a small PR right now, but I have issues #4366 and friends which mean that section will need a full rewrite anyway due to all of the various `EXPLAIN` changes.  The smaller PR now would be wasted work (and may also lead to merge conflicts since this page is beginning to have many things on it ^_^ )

The docs that state we support the feature from this issue were added in commit 7fbce7b2 so I'll close this one and let the erroneous text be washed away by those other impending work items.
