### ISSUE TITLE
sql: JSON-ify timestamps using RFC3339 format

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4371]
PR: https://github.com/cockroachdb/cockroach/pull/34412

From release notes:
> Formatting of timestamps as JSON strings has been changed to always use the RFC3339 format instead of Cockroach's customary format. Users can now expect to see a `T` separator instead of a space between the date and time components. [#34412][#34412] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Hi @bobvawter 

Our current [functions docs](https://www.cockroachlabs.com/docs/dev/functions-and-operators.html) for `to_json` state that it

> Returns the value as JSON or JSONB.

Based on your PR (https://github.com/cockroachdb/cockroach/pull/34412) I don't think the docs need to be updated, since the patch is fixing an output that would surprise someone expecting JSON, which we already claim to return.

Do you agree with that assessment?

**Comment by bobvawter** [comment]
@rmloveland Yes, this was just a tweak to bring the output into better alignment with PostgreSQL.
