### ISSUE TITLE
Performance partitioning

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4386]
Exalate commented:

## Title

https://www.cockroachlabs.com/docs/v2.1/partitioning.html#why-use-table-partitioning has `archival partitioning` aimed at reducing cost.  Calling this `Performance partitioning` to be the 3rd use case.

## Description

The inverse of this aimed at providing better service and meeting customer SLA of hot service is to move the partition to faster and ore VMs.

## Outline

Show examples of moving partition to faster VMs improving performance.

## Expected Audience

DBA ans Developers.

**Comment by jseldess** [comment]
@johnrk, @taroface, this is an old doc request for better docs on archival partitioning. Beyond renaming it "performance partitioning", we need to determine if this is a vetted and fully functional feature of our product. I am trying to understand if archival partitioning is a skill that we want to teach operators as part of the [CockroachDB operator certification program](https://docs.google.com/document/d/1WMPG_2C28-Xq3BgH2NSy-gGLaD86n08tQGYZCzEQ_Iw/edit#). Here's a note from @irfansharif on that point:

> We haven't done any serious testing on this sort of thing. We don't typically run CRDB on heterogenous storage devices (relying instead on mostly SSDs, which is to say we probably should soon). We don't measure/track access/storage costs to have ballpark numbers in the way a potential customer would want to understand. I'm confident that some of it might just work "out of the box" with the appropriate zone configs/labels, but we haven't done so ourselves.

@bdarnell, looping you in as well because I remember discussing this topic with you a long while back but can't remember your perspective.

**Comment by johnrk** [comment]
This looks like a SQL issue, as it involves a developer making table partitions. cc @awoods187
