### ISSUE TITLE
Try-Us-Out instructions should not use Docker, but binaries

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/docs#44]
You can't access `http:\\<docker ip>:26527` because docker ports/networking something something. I think we need more to the docker invocation than what's documented here. I think @tschottdorf would know.

Also we need to figure out the relationship between the installation instructions we have in the README.md and the docs site.

**Comment by tschottdorf** [comment]
I think we should start exposing our linux nightlies and the brew formula (assuming it works fairly reliably). We can keep the Docker stuff around somewhere, but maybe not at the top.

I'll fix up the README invocation. Should be passing a flag or two, but on OSX there's always some loss of simplicity because of the VM.

**Comment by jseldess** [comment]
Fixed with readme updates: https://github.com/cockroachdb/cockroach/pull/5511. We're now just linking to our install page in the docs.
