### ISSUE TITLE
Google search for "cockroachdb performance" does not yield our perf best practices docs

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#4557]
A Google search for ["cockroachdb performance"](https://www.google.com/search?q=cockroachdb+performance&oq=cockroachdb+performance&aqs=chrome..69i57j0l5.2823j0j7&sourceid=chrome&ie=UTF-8) does not show our [SQL performance best practices](https://www.cockroachlabs.com/docs/dev/performance-best-practices-overview.html), at least for the first 7 pages of results (as of the date of this issue creation, when logged in as me, at least)

**Comment by rmloveland** [comment]
cc @jseldess since we discussed this in another medium

**Comment by jseldess** [comment]
@maria-toft, Kurt mentioned you might be able to help us with this?

**Comment by maria-toft** [comment]
@jseldess @rmloveland @oenoke, It's difficult to control the organic ranking of content on Google in general, and in this case, it would be difficult to rank that specific docs page high on Google on the keyword "cockroachdb performance" when we have a few other content pieces that speak more generally to CockroachDB performance and therefore more relevant to the keyword -- which is part of the algorithm that decides which content rank highly. We are also competing with other websites that have content on this content and with our own Github posts. 

If it's important for a general audience who is searching "Cockroachdb performance" to see this doc page there are a few tactics we can consider. For example, to link to it the other pages, so that if they go to the first page results, they can easily navigate to that docs link.

**Comment by jseldess** [comment]
Thanks, @maria-toft. I don't know if it's important to return this page for exactly this search. It'd be nice, but probably not crucial. As soon as the search is a bit more granular, the docs are in the results, for example:

<img width="826" alt="Screen Shot 2019-03-21 at 1 05 31 PM" src="https://user-images.githubusercontent.com/15893490/54770794-573bc780-4bda-11e9-8564-22253aa0802f.png">

**Comment by jseldess** [comment]
Just spoke to Kurt about this, too. Post-19.1, we will create a `cockroachdb-performance.md` docs page that serves as an index for all of our performance-related content. Here's the issue for that: https://github.com/cockroachdb/docs/issues/4558.

**Comment by jseldess** [comment]
We added a performance page, which returns high in results, though we need to make adjustments as described in https://github.com/cockroachdb/docs/issues/5920.
