### ISSUE TITLE
deploy: Using Prometheus to monitor CockroachDB

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#469]
See PR https://github.com/cockroachdb/cockroach/pull/7895

@mjibson, I'll need your help to understand what's involved here.

**Comment by mberhault** [comment]
I'm currently adding basic configs and probably rules/simply dashboard for prometheus. Those will be checked into the production repo (eg: https://github.com/cockroachlabs/production/pull/20).

**Comment by jseldess** [comment]
Great, @mberhault. Welcome back!

**Comment by jseldess** [comment]
Sample config: https://github.com/cockroachlabs/production/blob/master/monitoring/prometheus.yml

**Comment by jseldess** [comment]
Question about this in Gitter, 9/11/16:

> hey. any tips on how to monitor CDB with prometheus? Is there a common code somewhere that transforms /_status/metrics into the simpler key/value pair expected by prom?
maybe a special parameter that changes the output format?

**Comment by mberhault** [comment]
Ok, we should document this soon.
The first step is to move the monitoring/alerting configs to the public org so we can link to them and have people easily use them.
@bdarnell: since these are just config files, I was thinking of having a `monitoring` directory in the main repo (much like we have the `cloud`) directory. Any objections?

**Comment by bdarnell** [comment]
No objections for now since we already have the cloud stuff there, but longer term we should probably think about a new home for both of these things (since we don't want users of our binary distributions to also have to download our source for a few small config files). Maybe that means a separate repo, maybe it means embedding them in the binary (like the man pages and other stuff behind the `gen` command).

**Comment by mberhault** [comment]
Ok. I'll put it in the main repo for now and keep in mind that we may want to move it.

@jseldess: I'm going to put a few config files and some explanations about what they do and how to use them. After that, we can integrate that into the docs.

**Comment by jseldess** [comment]
Great, @mberhault. Just let me know when that's ready and I'll get the docs started.

**Comment by sploiselle** [comment]
@mberhault Have you had a chance to prep these config files yet?

**Comment by dianasaur323** [comment]
We just had a request from a user on being able to pull metrics to monitor CockroachDB through an API. I'm assuming this relates to this issue.

**Comment by mberhault** [comment]
I haven't gotten around to it yet. I'll try and get a sample config file
this week-end (well, two: one for insecure, one for secure, but not much
difference)

**Comment by jseldess** [comment]
Hey @mberhault, any updates? Just got another question about this in Gitter.

**Comment by mberhault** [comment]
I've just sent a PR for a basic working prometheus config against a single local node in insecure mode. Secure mode involves just changing one line: https://github.com/cockroachdb/cockroach/pull/12288

We can iterate over how to document the process (with a lot of linking to prometheus docs), but I still have at least the following to take care of:
* alertmanager config (prometheus crafts the alerts, but the alertmanager is responsible for sending them to email/slack/etc...)
* grafana dashboards

**Comment by jseldess** [comment]
Thanks, @mberhault. Once I'm back in the office, I'll start taking a look.
