### ISSUE TITLE
End-to-end developer tutorial

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4693]
We have minimal "build an app" tutorials. We need a more robust, realistic, end-to-end tutorial for developers featuring topics like concurrency, contention, retries, pagination, and troubleshooting.

This involves building a full application, or leveraging/extending what we already have. We should start with one of the most popular languages, probably Java, Go, Python, or Node.

**Comment by jseldess** [comment]
See https://github.com/cockroachdb/docs/issues/3584 for relevant details.

**Comment by jseldess** [comment]
@rmloveland, @ericharmeling, in our discussion of dev docs next steps, we should consider this issue, or something similar, and weigh it against other options. I would love an end-to-end developer tutorial for 20.1 if not for 19.2.

**Comment by rmloveland** [comment]
Jesse Seldess <notifications@github.com> writes:

> @rmloveland, @ericharmeling, in our discussion of dev docs next steps,
> we should consider this issue, or something similar, and weigh it
> against other options. I would love an end-to-end developer tutorial
> for 20.1 if not for 19.2.

I would also love to have this!

I also think we need to be clear that doing this would be a major
project that would be all someone could work on for <insert longer
period of time than we might consider comfortable here>.  @Amruta-Ranade
shared a link recently to [this talk "Content is King and other
Cliches"](https://www.heavybit.com/library/video/content-is-king-and-other-cliches/)
where the speaker says:

> Why does good content matter? Why do we even care about good content?
> It's a huge, huge time sink. How many people have spent 30 hours
> writing a blog? It takes me 40 to 60 hours to write a good conference
> talk.

If it takes 30 hours to write a good blog post, how long would it take
to write a realistic-ish example application and then the "blog post" /
doc writeup?  My wild-assed guess is 200+ hours (bare minimum, probably
more like 300), which would be ~5-8 work weeks if one did nothing else
(which is of course not how work happens!  :-} ).  The review process
post-PR would also be very lengthy, probably on the order of weeks or
possibly a month to get the code and prose into shape if the reviewers
had significant feedback.

So we would need to get super clear on that being absolutely OK for us
to invest time in, and we'd need to design the project in phases so the
person doing it didn't fall victim to the "omg i haven't moved this
issue in weeks, what is happening to my productivity" issue.

We also probably need to do #182, #3203, #3943, #4705 et al as
prerequisites to realistically delivering something like this.
Otherwise the resulting app would be incredibly unwieldy to deliver into
our existing site structure, which only pulls in complete code files and
not snippets, and has no automated code testing to make sure stuff
works.

Even though I still think this is important I might have convinced
myself now that we may not want to do this yet (ha!).

Def looking forward to discussing this more.

**Comment by jseldess** [comment]
It sounds like we might wan to scope this down and *plan* this project thoroughly in the 19.1 timeframe. Executing clearly seems out of scope. But perhaps even the planning should be punted. @awoods187?

**Comment by awoods187** [comment]
I'm fine with punting this completely for now--we clearly have higher priority work to do

**Comment by jseldess** [comment]
Closing in favor of https://github.com/cockroachdb/docs/issues/5243.
