### ISSUE TITLE
Atomic replication: Allocator changes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4722]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/reckezB9xNbQbj8hi?blocks=hide
PM: @awoods187 
Eng: @bdarnell, @andreimatei

**Comment by rmloveland** [comment]
@tbg I have questions (asking because you are the author of https://github.com/cockroachdb/cockroach/pull/39936 and https://github.com/cockroachdb/cockroach/pull/40234).

Based on my reading of our replication layer docs (especially the [Membership changes: rebalance / repair](https://www.cockroachlabs.com/docs/dev/architecture/replication-layer.html#membership-changes-rebalance-repair) section) we simply refer to this activity as "rebalancing" without defining whether it is atomic or not.  A reasonable person could assume that our rebalancing is already atomic.

Therefore I'm inclined to think that there is no need to update the replication layer docs based on this code change since it is addressing a limitation.  Do you agree with that assessment?

Related: @jseldess is this known limitation about rebalances not being atomic documented anywhere?  I was thinking I'd need to remove a known limitation entry about this but I'm not seeing anything obvious on our [known limitations page](https://www.cockroachlabs.com/docs/dev/known-limitations.html).  At least my searches for "rebalancing" and related terms on that page are not returning results that I think are related to this.  But maybe I'm missing it?

**Comment by tbg** [comment]
Yep Rich that sounds right.

**Comment by rmloveland** [comment]
Awesome.  In that case I will close this issue.
