### ISSUE TITLE
Changefeeds Dashboard Doc Update 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/docs#4785]
Re: [Changefeeds Dashboard](https://cockroachlabs.com/docs//v19.1/admin-ui-cdc-dashboard.html)

## Issue Description

The graph shows as 29.4 seconds, but the text below has nanoseconds.  

In the node view, the graph shows the maximum latency (in nanoseconds) of any running changefeed for the node.

## Suggested Resolution 

is the time in nano or seconds?

**Comment by rolandcrosby** [comment]
I see what happened here -- the metric itself is measured is in nanoseconds, but the UI automatically converts this to appropriate units depending on the scale of the number. We can just remove "(in nanoseconds)" from the doc page since the UI always shows the units it uses.

We should also add more detail to the explanation of the "Max Changefeed Latency" graph. It always shows the max latency for resolved timestamps, which, while an important metric to monitor, is distinct from (and much slower than) typical commit-to-emit latency for individual change messages.
