### ISSUE TITLE
Expand docs sidenav by default

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4852]
This would make our categorizations a lot more intuitive.

**Comment by jseldess** [comment]
This should probably wait until we kickoff our broader docs refresh with design.

**Comment by luciaaaaaaa** [comment]
hey, following up on this as part of the redesign. 

Does this refer to the navigation sidenav? would like to explore alternative navigation patterns instead of expanding by default. 

One question I have around the sidenav is whether we think there is value in removing the automatic collapse that happens as I navigate through different sections. That way a user could expand all sections and Ctrl+F. Thoughts?

cc @lnhsingh

**Comment by jseldess** [comment]
Yes, this is about the sidenav. Excited to get your input here. I don't want this issue to dictate our solution, especially if we change our navigation in more substantial ways.

**Comment by luciaaaaaaa** [comment]
sounds good. thinking it would be helpful if we could change this issue into a descriptor of what the challenges you experience with the current navigation is. otherwise perhaps we should just close out?

**Comment by jseldess** [comment]
Let's just close. I think the motive here is to give users a more intuitive sense of what's available. Our categories are collapsed by default, in contrast to a lot of other docs. So there are clicks involved in discovering content or verifying instincts. I know some users prefer the docs landing page, for example, since it lists a lot more topics.
