### ISSUE TITLE
distsql: remove legacy batched-write index dist-backfiller

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4888]
PR: https://github.com/cockroachdb/cockroach/pull/37213

From release notes:
> Removed the legacy batch-by-batch index backfiller, as well as the `schemachanger.bulk_index_backfill.enabled` [cluster setting](../v19.2/cluster-settings.html) that could be disabled to activate it. [#37213][#37213] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@dt I have questions:

1. Is this change being back ported to 19.1?  If so it would mean that docs issue #4466 could be closed, since there would be no way to turn on the old batch index backfill to catch the uniqueness errors.  Or perhaps such errors are caught by the new system now?

2. Related to 1: If this change is not  being back ported, do you think #4466 is still in need of documenting?

3. At first glance this change does not seem to affect the user-facing docs for 19.2 _except_ that we need to delete the cluster setting from the docs.  There is no mention of specific mechanisms in the [Online Schema Changes](https://www.cockroachlabs.com/docs/v19.1/online-schema-changes.html) doc around batch-based vs. streaming vs. X.  It uses pretty generic language like

> During the backfilling process, the schema change engine updates the underlying table data to make sure all instances of the table are stored according to the requirements of the new schema.

Therefore I'm inclined to think the only doc update needed here is to delete the setting.  Do you agree with that assessment?

(I will of course take another pass through the docs to confirm as well, just want a sense)

**Comment by jseldess** [comment]
I think you're right, @rmloveland, and the setting is already gone from the docs, so closing.
