### ISSUE TITLE
Update guidance for running CockroachDB on Windows

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#4935]
Since the binary is experimental, we should probably remove it from all release note pages, where it seems to be on equal footing with linux/mac/source.

We might also want to emphasize running the Linux binary in a [Windows subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) as the primary method, with the Windows binary, Docker, and Kubernetes as other options.

**Comment by kenliu** [comment]
@jseldess -- wondering where the recommendation to run on WSL came from. WSL offers linux compatibility but one of its key problems is slow IO performance -- I don't have data to show it, but running a DB on it would probably be super slow for all but the most trivial things. (latest version of WSL is supposed to be improved)

**Comment by jseldess** [comment]
@kenliu, good question. I'm not sure WSL is actually the right approach, but I've heard the option to run in a Linux virtual environment on Windows a few times. Would a different tool be better (VirtualBox)? This is all in the context of local testing of CockroachDB, not real production deployment, remember.

**Comment by bdarnell** [comment]
WSL 1.0 is known to be problematic: https://github.com/cockroachdb/cockroach/issues/24344

WSL 2.0 is a proper VM so it is probably better, but we haven't tested it. 

Whatever we recommend here, we have to test it - we can't just assume that something like WSL will work (virtualbox is more likely to work, but virtualbox shared folders have proven problematic for other projects). If we have to test something, I'd rather just test the windows binary. 

We've listed the binary even in its experimental state so that the community will try it - have we gotten enough feedback to know how/if it works?

**Comment by jseldess** [comment]
@bdarnell, good question. I'm not sure. I've asked the Support team to chime in.

**Comment by ricardocrdb** [comment]
A couple of issues from different users came up where customers are running Windows and the process is crashing. I have taken steps to reproduce some of them using a VirtualBox VM of Windows on my lappy, and so far I have reproduced some of the issues, and finding a few more in additional tests, which I will gladly create issues for if needed.

I had worked with a couple of Core members in getting some builds for test executables built and passed the results along to them, which I can also provide in a separate issue as well.

Let me know if anything else is needed.
