### ISSUE TITLE
sql: Document modern vs. traditional SQL syntax

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#513]
- Sets at session
- Modern must be explicitly set

**Comment by mjibson** [comment]
Modern is used during lexing: https://github.com/cockroachdb/cockroach/blob/develop/sql/parser/scan.go

Modern appears to support (not exhaustive):

- placeholders can be names instead of just numbers
- raw bytes, something like ﻿⁠⁠⁠⁠br'blah'﻿⁠⁠⁠⁠
- raw strings: ﻿⁠⁠⁠⁠r'blah'﻿⁠⁠⁠⁠
- ﻿⁠⁠⁠⁠#﻿⁠⁠⁠⁠ for comments
- newlines in triple quoted strings

Need to figure out about string and ident handling, which have differing quote rules.

**Comment by jseldess** [comment]
We removed the `modern` syntax: https://github.com/cockroachdb/cockroach/pull/15064

Closing this issue.
