### ISSUE TITLE
Improve setting locality

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5142]
Background: https://airtable.com/tblD3oZPLJgGhCmch/viwchkdQkRUw6hZ3z/rec5VGO7Lbcu06Knb?blocks=hide
PM: @awoods187 
Eng: @andy-kimball

**Comment by rmloveland** [comment]
@awoods187 (or @johnrk since this is Core) looking at the Github issues linked from AirTable, it doesn't look like there is any engineering work ongoing on this (status: "Investigation", and all linked issues still open), and thus nothing to document at this time.

Do you agree with that assessment?  If so I'd like to close this.

**Comment by johnrk** [comment]
@knz , was there anything merged or being actively worked on here?

**Comment by knz** [comment]
No there hasn't
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
