### ISSUE TITLE
workload: support loading initial data using IMPORT in `run` and `init`

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5308]
PR: https://github.com/cockroachdb/cockroach/pull/35312

From release notes:
> [`cockroach workload run`](../v19.2/cockroach-workload.html) and `cockroach workload init` now support loading initial table data using [`IMPORT`](../v19.2/import.html). [#35312][#35312] {% comment %}doc{% endcomment %}

**Comment by danhhz** [comment]
Hey jesse. Looks like there are two separate issues.

The first is that ycsb apparently doesn't work with this because uses more than one column family. That obviously shoudn't crash, it should either work or return error about ycsb not being supported. I'll have to do some digging to figure out whether making it work is mergable this late in the release

The tpcc one is actually it working, for some definition of working. We have some memory limits to prevent OOMs and I'm told that we recently changed IMPORT to respect them. If you manually specify `--max-sql-memory=1G` on your `start-single-node` (which is what the error message suggests), the import finishes.

It's possible that IMPORT should be better about working in low memory environments, but this is almost certainly not going to be fixed in time for 19.2. Given that "inserts" is the default, I'm okay with "import" returning an error telling you exactly what to do. It's definitely worth getting this documented because it's incredibly useful for POCs. I definitely wouldn't start updating all our docs to point you at --data-loader though.

**Comment by danhhz** [comment]
Fix for ycsb is https://github.com/cockroachdb/cockroach/pull/41071

**Comment by jseldess** [comment]
Thank you, @danhhz! I think I can update the docs now.

**Comment by danhhz** [comment]
Hey @jseldess, just an update that the ycsb fix is approved and merging for 19.2 as soon as it gets past bors. This ended up being a larger bug where any IMPORT into a table with multiple column families would panic(!) so thanks for pushing on it : - D.

Mind filing an issue for the bulkio team about making IMPORT work better when `--max-sql-memory` is set to a small number? Given that our default for that flag is a small number, it seems like a pretty bad user experience that IMPORT doesn't work out of the box

**Comment by johnrk** [comment]
cc @mwang1026

**Comment by mwang1026** [comment]
I'm not sure what's going on here...?

**Comment by jseldess** [comment]
I'm not sure. It's been a while. Let me take this back and do some testing and then I'll update this thread.

**Comment by mwang1026** [comment]
I would hope the IMPORT bug is fixed by now :)

I'll treat this as a "doc that certain workloads can use the import data load option" and prioritize accordingly

**Comment by jseldess** [comment]
OK, sounds good. Happy to leave it to you and @lnhsingh to test and verify the workloads then.

**Comment by jseldess** [comment]
Just getting back to this. Our docs on `cockroach workload` are pretty far behind when it comes to importing. There's a distinct `cockroach workload fixtures import` command that is preferable to `cockroach workload init tpcc --data-loader=import`, I think. @mwang1026, @awoods187, who owns `cockroach workload`? I think there's some UX cleanup we might need to do and definitely some documenting.

**Comment by jseldess** [comment]
@mwang1026, @awoods187, ping.

**Comment by awoods187** [comment]
We don't have clear ownership of Cockroach Workload right now. It's one of the items that we are working through--for now, I'd defer to Michael on the import decision and you can route other questions about workload to me and I'll either take them or route them to the correct person.

**Comment by jseldess** [comment]
The original point of this issue has been resolved; we document `--data-loader=import`. `cockroach workload fixtures import` remains undocumented, but the `fixtures` subcommand is also hidden the CLI help. If we need to document that, I trust that it will come up again.
