### ISSUE TITLE
Update Contributing Guide with command to build MacOS binary

### ISSUE THREAD

**Issue by timveil** [cockroachdb/docs#5347]
I think we need to update `CONTRIBUTING.md` to specify how to build a mac executable.  The instructions discuss how to build the binary using the docker builder image (`build/builder.sh make build`) but fail to mention that by default this will build a linux binary only.  The command as i understand to build a mac binary is the following:

```
build/builder.sh mkrelease amd64-darwin
```

**Comment by bdarnell** [comment]
The usual way to build a mac executable is `make build` (assuming you're building on a mac). `build/builder.sh mkrelease amd64-darwin` is an alternative if you don't want to install our build prerequisites (but do have docker), although it's *much* slower than a native build. 

`build/builder.sh make build` is a bad idea even for linux - it produces non-portable binaries that will run inside the builder image but may not work outside it. If you're using the builder image you should probably always use `mkrelease` instead of `make` to produce portable binaries.

**Comment by timveil** [comment]
good to know.  i do favor the builder image so i don't have to hassle with installing local dependencies.  would be good to spell out these differences, particularly between `make` and `mkrelease`, in the docs or contributor guide.  I was not clear on the differences.

**Comment by jseldess** [comment]
The build instructions have moved to the wiki and include MacOS-specific guidance now: https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/73204103/Building+from+source+on+macOS
