### ISSUE TITLE
Correct core changefeed examples

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5440]
Based on feedback from a user, the examples on https://www.cockroachlabs.com/docs/stable/changefeed-for.html are incomplete. We need to show the full process of starting the sql shell **with the `--format=csv`** flag, setting the cluster setting, and then creating the changefeed. The `--format` flag in particular is easy to missing. 

This is spurred by feedback from a users.

**Comment by jseldess** [comment]
<img width="560" alt="Screen Shot 2019-09-16 at 9 53 52 PM" src="https://user-images.githubusercontent.com/15893490/65005037-83f04380-d8cc-11e9-9f94-0e01dcdd4af4.png">

Looks like `--format=csv` is a requirement that we should call out clearly.

**Comment by rolandcrosby** [comment]
We should put a note on the page explaining that you need to say `\set display_format=csv` when consuming a core changefeed in the `cockroach sql` shell, or specify the `--format` CLI option. This is necessary because core changefeeds never finish returning data - they just stream results to the client, which means that display formats (or drivers) that buffer data will appear to never complete.
