### ISSUE TITLE
parser: handle FOR UPDATE [ OF tables ]

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#5516]
PR: https://github.com/cockroachdb/cockroach/pull/40962

From release notes:
> Added parsing for `FOR UPDATE [ OF tables ]` form. [#40962][#40962] {% comment %}doc{% endcomment %}

**Comment by ericharmeling** [comment]
@jordanlewis I'm seeing this labeled as a "no-op", but I don't have a formal definition for that term, and I'm not sure what that means in terms of documentation. Please advise. Thanks!

**Comment by jordanlewis** [comment]
I think that we should probably document this stuff, as people might wonder what it does at the moment since we do support the syntax.

Have a look at this answer: https://stackoverflow.com/questions/10935850/when-to-use-select-for-update

We'd fall under the bucket: "However in some systems locking is a side effect of concurrency control, and you achieve the same results without specifying FOR UPDATE explicitly."

But, we've added support for the syntax to make it easier for people to port their applications. People just need to be aware that the syntax doesn't change our behavior at the moment, but that's subject to change going forward. cc @knz

**Comment by knz** [comment]
FYI @andy-kimball and I agreed to talk about this work along the following lines:

> we're aiming to implement a variant of pg's SFU  functionality, which merely places advisory pessimistic locks to enable performance optimization. Note that this work item will not provide compatibility with pg's stronger locking guarantees and all non-performance uses of locking may not be satisifed by the proposed functionality. In particular, apps that require locks to protect data from any concurrent access altogether will not be enabled by this work.
