### ISSUE TITLE
release: add docker image to release table

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#5792]
In the [main docs page on releases](https://www.cockroachlabs.com/docs/releases/#testing-releases) users cannot tell that we have docker images available. At least one user didn't want to use a beta because they thought we didn't offer docker images for our alphas/betas.
![image](https://user-images.githubusercontent.com/22278911/68313200-326d6500-0082-11ea-8737-8e5657514695.png)

This information is available on individual [release pages](https://www.cockroachlabs.com/docs/releases/v19.2.0-rc.3.html):
![image](https://user-images.githubusercontent.com/22278911/68313291-4f099d00-0082-11ea-8254-f46f5c772adc.png)

We should add a docker image link to the main page. 

@bdarnell also notes that our windows binaries have fallen off the main page. 

There are also some ideas in [this thread](https://cockroachlabs.slack.com/archives/C4A9ALLRL/p1573000844273400) about how to avoid cluttering this main page.

**Comment by awoods187** [comment]
Users could also find https://hub.docker.com/r/cockroachdb/cockroach-unstable/tags

**Comment by bdarnell** [comment]
In addition, since helm is our most popular installation method (and is attractive for short-term testing usage even if your production installation is orchestrated differently), we should have instructions somewhere of how to run the beta with helm (i.e. edit the Image and ImageTag lines in values.yaml).

**Comment by jseldess** [comment]
Great feedback. I'll prioritize this, but it might follow the release.

**Comment by jseldess** [comment]
@bdarnell, we intentionally removed Windows from release notes pages in https://github.com/cockroachdb/docs/pull/4987 because we were getting too many incorrect assumptions about windows support, from what I remember. I believe you were involved in that decision: https://github.com/cockroachdb/docs/issues/4935. Have we changed our thinking in the meantime?

**Comment by bdarnell** [comment]
The state of the windows binaries was pretty bad in 19.1. We put some work into this in 19.2 so newer releases are in better shape and we should be linking to the windows versions of 19.2+.

However, we should double-check and make sure that the binaries actually work when downloaded on to a regular windows machine. @aaron-crl mentioned that there might be issues related to the fact that we don't sign our binaries (as far as i know).

**Comment by aaron-crl** [comment]
It seems like Windows really only gets grumpy when you are trying to run unsigned **drivers**. I think we should still prioritize signed releases but lack of signature shouldn't be a blocker.
