### ISSUE TITLE
add guidance for CPU requirements on single-cluster k8s deployment

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#5922]
Our single-cluster Kubernetes deployment tutorials have guidance on defining memory requests and limits. We need to provide similar guidance on defining CPU resources. The following points (paraphrased from @ajwerner) need to be conveyed and summarized with production recommendations:

- ~The CPU resources specified for a pod may not necessarily match the number of physical cores on the Kubernetes VMs being used.~ 
- ~When fewer cores are requested for CRDB than the total available, you must also specify a GOMAXPROCS value other than the total. Otherwise the go runtime will still use the total number of cores.~
- ~The requested CPU resources and GOMAXPROCS value may not necessarily match. It's possible that different values are required for optimal performance.~
- ~It may be preferable not to specify CPU requests:~ https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#if-you-do-not-specify-a-cpu-limit
- It is possible (per above link) to set default limits for the cluster

Questions:

- Should users specify a CPU request/limit for Kubernetes pods?
  - If yes, how should they determine the CPU request ~and GOMAXPROCS values? Also, how do they set GOMAXPROCS?~
  - ~If no, should they set a default CPU limit for the cluster?~

Relates to #5931

EDIT: Removed incorrect line that stated a certain GOMAXPROCS value causes issues.

**Comment by DuskEagle** [comment]
> Should users specify a CPU request/limit for Kubernetes pods? 

That ultimately depends on the environment. It's simpler if they don't, but that's not going to be an option for everyone.

> If yes, how should they determine the CPU request and GOMAXPROCS values?

I don't know the answer to this, other than setting CPU requests as high as possible. For GOMAXPROCS, as I understand it that should be set to the same amount as the number of CPU units you're requesting for the pod. I don't know what it should be if you request a non-integer amount of CPU units.

>Also, how do they set GOMAXPROCS?

Add this stanza to the [CockroachDB container spec's env](https://github.com/cockroachdb/cockroach/blob/fdffc5fee97476b2ff4bc2efba159f6f2ea235f7/cloud/kubernetes/cockroachdb-statefulset.yaml#L138):
```
- name: GOMAXPROCS
   value: 4
```

>If no, should they set a default CPU limit for the cluster?

That sounds like something only a Kubernetes cluster administrator would be able to do. If a user is going to set a resource limit, setting it on the statefulset spec is the place to put it.

**Comment by taroface** [comment]
@DuskEagle What would be the process of setting GOMAXPROCS when using Helm?

**Comment by DuskEagle** [comment]
I would recommend setting `limits` to be the same as `requests`. `requests` is used for scheduling a pod onto a node, while `limits` is passed to the container runtime. The Linux scheduler may also restrict a container based on the `limit` value.

Our Helm chart has [recently been updated](https://github.com/helm/charts/pull/18993) so that the parameter names conform to the Helm standard, so `Resources.requests.cpu` is now `statefulset.resources.requests.cpu`, and `ExtraEnvArgs` is now `statefulset.env`: see [values.yaml](https://github.com/helm/charts/blob/f4fcf44ce4969cd0cedaf84d06abc274d4f68e18/stable/cockroachdb/values.yaml#L138). I would recommend against setting these values with `helm install --set` - it's complicated to set array values, used by `statefulset.env`, using that syntax. Instead, I would recommend customers modify their `values.yaml` file, setting GOMAXPROCS and CPU resource requests as shown below within the `statefulset` stanza:
<img width="442" alt="Screen Shot 2019-12-03 at 1 35 06 PM" src="https://user-images.githubusercontent.com/7644598/70082078-a7778000-15d7-11ea-964e-7e57fbe4cad9.png">
<img width="504" alt="Screen Shot 2019-12-03 at 1 50 23 PM" src="https://user-images.githubusercontent.com/7644598/70082081-a9414380-15d7-11ea-89c8-287bf410d6c0.png">

**Comment by taroface** [comment]
@DuskEagle Should the maximum CPU request generally be one less than the available cores? When I created a Kubernetes cluster with `--machine-type n1-standard-4` and requested 4 CPUs, I got the below:

```
Warning  FailedScheduling   10s (x12 over 31s)  default-scheduler   0/9 nodes are available: 9 Insufficient cpu.
```

It worked when I decreased to 3.

**Comment by taroface** [comment]
Belated note to record that I drafted and then removed this update, per the warning box here: https://www.cockroachlabs.com/docs/stable/kubernetes-performance.html#resource-limits

Will investigate whether the existing warning against setting CPU limits still holds.

**Comment by bdarnell** [comment]
> Certain GOMAXPROCS values (2) can cause additional performance issues.

I just asked @ajwerner about this and we're not sure where exactly this came from. Neither of us is aware of any reason that `GOMAXPROCS=2` would be particularly problematic (aside from the general fact that an under-provisioned service is more easily overloaded)

**Comment by taroface** [comment]
I probably misunderstood @ajwerner's initial [thread](https://cockroachlabs.slack.com/archives/C9C1Z1LLV/p1573837541097200?thread_ts=1573837314.096800&cid=C9C1Z1LLV) about this, which was specifically about setting GOMAXPROCS to 2 on a 4-core machine, resulting in "2 concurrent bcrypt password verifications" leading to slowness. I'll remove that line from the description here.

**Comment by bdarnell** [comment]
Yeah, I suspect that's just an anecdote that could apply at any size. You could easily end up with 4 concurrent bcrypt verifications with GOMAXPROCS=4 (we should probably put some limiters in place so that bcrypt can't take up all your cpus)

**Comment by taroface** [comment]
Hi @bobvawter, do your changes in https://github.com/cockroachdb/cockroach/pull/51471 resolve the bullets in this issue description, or at least the first three?

Also would welcome your thoughts on the questions about CPU limits!

**Comment by bobvawter** [comment]
> The CPU resources specified for a pod may not necessarily match the number of physical cores on the Kubernetes VMs being used.
> When fewer cores are requested for CRDB than the total available, you must also specify a GOMAXPROCS value other than the total. Otherwise the go runtime will still use the total number of cores.
> The requested CPU resources and GOMAXPROCS value may not necessarily match. It's possible that different values are required for optimal performance.,

These have been resolved.

> It may be preferable not to specify CPU requests: https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#if-you-do-not-specify-a-cpu-limit

Users should always run in the k8s "guaranteed" quality-of-service mode in which the requests and the limits are the equal.  This will avoid cockroach pods getting placed on over-provisioned nodes.

https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/#create-a-pod-that-gets-assigned-a-qos-class-of-guaranteed

> It is possible (per above link) to set default limits for the cluster

We can specify some reasonable defaults that match our production checklist.  Something like 4 cores and 16 gb of ram.  If someone has created a k8s cluster that's silly-small, then the pods just won't schedule.  That may or may not be preferable to the case where cockroach will run, but with really poor performance.

Questions:
> Should users specify a CPU request/limit for Kubernetes pods?

They should always specify both, and they should be equal in order to get guaranteed QoS.

> If yes, how should they determine the CPU request and GOMAXPROCS values? Also, how do they set GOMAXPROCS?
> If no, should they set a default CPU limit for the cluster?

GOMAXPROCS is set with the referenced changes.  The actual values that they specify for their cockroach pods are going to depend on the underlying host machines and workload.

**Comment by taroface** [comment]
Thanks @bobvawter. Tangential to this issue, in https://github.com/cockroachdb/cockroach/pull/51471 you stated:

> If no limits are specified, you get the maximum number of cores and amount of memory that the particular kubelet is configured to provide.

Our docs presently state that without specifying `resources.limits.memory`, there is a risk of going OOM when CRDB is not the only pod on an instance, since CRDB doesn't detect the amount of memory allocated to its K8s pod. Is this still or no longer a risk with your update?

**Comment by bobvawter** [comment]
The OOM risk is mitigated in that the K8s scheduler will inject the maximum amount of memory that the pod may use into the config, and the math still works out.

However, running with no limits and having other workloads on the same underlying host presents a risk of overallocation if there's another memory-intensive workload on the same machine.

**Comment by taroface** [comment]
I believe this is now adequately covered in our [docs](https://www.cockroachlabs.com/docs/stable/operate-cockroachdb-kubernetes.html#allocate-resources). Closing this issue.
