### ISSUE TITLE
Expand SERIAL documentation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#612]
Excerpts from Gitter:

Adam @apinckard 09:39
Hi all. Quick question is the SERIAL data type guaranteed to be monotonically increasing as well as globally unique? (understand that is not always sequential)

... So we are intending to use it for very high frequency. If two transactions occur concurrently can we guarantee monotonically increasing e.g. first to commit < second to commit?

kena @knz 09:50
right now the SERIAL values are based off the current time up to microsecond precision. You always get different values on different nodes, but if you have 2 concurrent transactions on the same node asking for SERIAL values at the same time, one could get a value and another the same value or just below (or above) it with no guarantee on ordering.
no the ordering is not related to commit order.
...
**the nearest we have to what you want/need is another function called cluster_logical_timestamp() which returns a DECIMAL value. It's heavier than a simple int**

Adam @apinckard 09:56
...
One follow up: within a single transaction is the output of serial guaranteed to be monotonically increasing?

kena @knz 10:43
within a single transaction, the output of serial is currently guaranteed to be monotonically increasing as long as your system clock does not jump backwards
if it does (which seems to happen in cloud servers, where VMs are migrated live), all bets are off
feel free to summarize the current situation and what you'd like to see instead in our github issue tracker.

**Comment by petermattis** [comment]
> If two transactions occur concurrently can we guarantee monotonically increasing e.g. first to commit < second to commit.

The short answer is no. This is very expensive to guarantee. MySQL `AUTO_INCREMENT` and Postgres `SERIAL` and sequences do not provide this guarantee either. I believe I've provided simple examples demonstrating this before.

**Comment by knz** [comment]
@petermattis yes you have so that's why this doc issue now exists so we can propagate your examples to the docs :)

**Comment by jseldess** [comment]
In the [SERIAL](https://www.cockroachlabs.com/docs/serial.html#auto-incrementing-is-not-always-sequential) docs, we have an example of how the `SERIAL` type in PostgreSQL and CockroachDB, and the `AUTO_INCREMENT` type in MySQL, all behave the same in that they do not create strict sequences. But I don't think that example covers the above. Can someone either point me to the examples @petermattis has provided before or add them here?

**Comment by knz** [comment]
Scenario 1:

- at time 3 txn T1 BEGINs
- at time 4 txn T2 BEGINs on the same node (from a different client)
- at time 5 txn T1 creates a SERIAL value, x
- at time 5 + 2 microseconds txn T2 creates a SERIAL value, y
- at time 6 txn T1 COMMITs
- at time 7 txn T2 COMMITs

If this happens we cannot guarantee whether x < y or x > y, despite the fact T1 and T2 began / committed in different times. In this particular example it's even likely that x = y because there is less than a 10-microsecond difference and the SERIAL values are constructed from the number of microseconds in the current time.

Scenario 2:

- at time 3 txn T1 BEGINs
- at time 3 txn T2 BEGINs somewhere else, on a different node
- at time 5 txn T1 creates a SERIAL value, x
- at time 6 txn T2 creates a SERIAL value, y
- at time 8 txn T1 COMMITs
- at time 8 txn T2 COMMITs

If this happens we cannot guarantee whether x < y or x > y. Both can happen, even though the transactions began and committed at the same time. However it's sure that x != y because the values were generated on different nodes.

Scenario 3:

- at time 3 txn T1 BEGINs
- at time 4 txn T1 creates a SERIAL value, x
- a time 5 txn T1 COMMITs
- at time 6 txn T2 BEGINs somewhere else, on a different node
- at time 7 txn T2 creates a SERIAL value, y
- at time 8 txn T2 COMMITs
- there is less than 250ms difference between the system clocks of the two nodes.

If this happens we cannot again guarantee whether x < y or x > y. Even though the transactions "clearly" occurred one "after" the other, perhaps there was a clock skew between the two nodes and the system time of the 2nd node is set earlier than the 1st node. 

The latter scenario is arguably particularly jarring. People may be OK with a SERIAL type that is not strictly sequential, but they are likely not OK with a type that is not *monotonic*. 

FWIW @petermattis has a TODO in the code (https://github.com/cockroachdb/cockroach/blob/97fdeca9bd63ed906849805199efcc03a4a8fcd3/sql/parser/builtins.go#L1509-L1511) to look into this. My personal opinion is that we should change that code to at least use the cluster logical time instead of the system time, so that we restore monotonicity. Peter what do you think?
