### ISSUE TITLE
sql: SPLIT AT statement

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#616]
PR: https://github.com/cockroachdb/cockroach/pull/8938

**Comment by nvanbenschoten** [comment]
@jseldess pre-splitting tables is something we're going to want to recommend to users as a performance/stability best practice. Is documenting this functionality something we could fit into the 2.0 timeframe?

**Comment by jseldess** [comment]
@nvanbenschoten, I wasn't planning on this for 2.0, but if it's important, and you or someone else can help draft the scenarios when you'd want to do this and why, we could make it a priority.

**Comment by nvanbenschoten** [comment]
The primary scenario where you'd want to do this is when creating a new table that will immediately receive a lot of load. Instead of letting the table's single range split on its own, which can result in reduced workload performance, it's often preferable to preemptively split the table's single range up into multiple ranges before applying any load, based on the expected distribution of writes.
