### ISSUE TITLE
CC: password reset - user doesn't exist email

### ISSUE THREAD

**Issue by laurenbarker** [cockroachdb/docs#6167]
Copy for email when the user doesn't exist. See https://github.com/cockroachlabs/managed-service/issues/1869 for details. cc @Amruta-Ranade 

**MainText:**     "",

**Subtext:**      "Someone tried to reset the password for your account, which doesn't exist, click the link below to create it or ignore this message if this wasn't you.",

**CallToAction:** "Sign Up",

**AcceptURL:**    "/signup",

**Comment by kscurtis** [comment]
cc @rolandcrosby

**Comment by laurenbarker** [comment]
@rolandcrosby did you have copy for this email? I just went straight to Amruta 😅No rush, just wanted to check.

**Comment by rolandcrosby** [comment]
@laurenbarker Basing this on [the existing SendSignUpExistingUser text](https://github.com/cockroachlabs/managed-service/blob/25549bace509490148bb9b66eadbbd110e73de51/console/mailers/senders.go#L128-L135), let's go with something like:

subject: "Security alert: Password reset"
main text: "Someone tried to reset your password",
subtext: "Someone tried to reset the CockroachCloud password associated with this email, but the request was denied since no account with this email exists. If that was you, try another email address or contact support."

**Comment by laurenbarker** [comment]
Thanks! Should there be a sign up call to action still or do we want to remove that?

**Comment by rolandcrosby** [comment]
If the user is really trying to reset their password, their next step is to figure out which email address they actually used and go try that on the sign-in page. For that reason, I think it's fine to keep the "sign in" CTA.
