### ISSUE TITLE
Data Definitions page not accessible through nav

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/docs#622]
The Data Definitions stem article page no longer surfaces in the docs navigation bar and must be browsed to directly:

https://www.cockroachlabs.com/docs/data-definition.html

**Comment by jseldess** [comment]
As just discussed offline, in the absence of a better solution, we'll move constraints up one level as well as indexes. The rest of the topics will stay under Data Definitions for now.

**Comment by jseldess** [comment]
We have an issue to break constraints into separate pages. And we could still consider moving Constraints, Indexes, and maybe other topics out from this section. But in any case, the `data-definitions.md` stub no longer adds any value, since it just replicates what's shown in the sidenav, so I'll remove it.
