### ISSUE TITLE
Draft Chapter 1 of Developer Fundamentals (lesson plan)

### ISSUE THREAD

**Issue by thatnerd** [cockroachdb/docs#6295]
DoD
- Review current state of Movr v2
- Identify 3-5 movr "features" that align with LO's for the course
- Draft 10 lessons' worth of learning objectives
- Submit to Crossman for review

**Comment by jseldess** [comment]
@thatnerd, my main concern with using Movr v2 is that it's multi-region-centric, and I don't know that you want your course to have that focus... Maybe talk to @ericharmeling more about this?

**Comment by ericharmeling** [comment]
I agree with Jesse. The MovR-Flask application isn't a good "fundamentals" example. It's meant to demonstrate multi-region with CRDB and requires a pretty involved, manual application deployment and a multi-region CRDB cluster. 

The app dev team has plans to develop a more simplified, single-region example in the near future. Otherwise, we can leverage our current "Hello World" examples (i.e. those used in the ["Build an App" docs](https://www.cockroachlabs.com/docs/stable/build-an-app-with-cockroachdb.html)).
