### ISSUE TITLE
Update tpc-c docs to use fixtures import 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/docs#6325]
@keith-mcclellan noticed that a few tpc-c docs still don't use fixtures import. Fixtures import is significantly faster and we should consider updating the remaining docs to use it.

10 warehouses doesn't use it while 1000 and up do here:
https://www.cockroachlabs.com/docs/v19.2/performance-benchmarking-with-tpc-c-10-warehouses.html

The performance benchmarking page also doesn't use it.

https://www.cockroachlabs.com/docs/v19.2/training/performance-benchmarking.html#main-content

**Comment by keith-mcclellan** [comment]
Here were the places I found:

these use tpcc init 

https://www.cockroachlabs.com/docs/v19.2/training/performance-benchmarking.html#main-content
https://www.cockroachlabs.com/docs/v19.2/performance-benchmarking-with-tpc-c-10-warehouses.html

this uses workload instead of cockroach workload
https://www.cockroachlabs.com/docs/v19.2/performance-benchmarking-with-tpc-c-1k-warehouses.html#main-content

Also, fixtures isn't documented in the cockroach workload reference
https://www.cockroachlabs.com/docs/stable/cockroach-workload.html
