### ISSUE TITLE
Improve Django ORM docs (limitations/bugs/workarounds)

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/docs#6367]
Follow-up to #6359 and #6365.

We still need improved guidance on limitations/bugs/workarounds, from https://github.com/cockroachdb/django-cockroachdb#known-issues-and-limitations-as-of-cockroachdb-1922.

**Comment by timgraham** [comment]
There are corresponding tickets in the CockroachDB tracker to address these bugs and unsupported features. Many have been fixed since 19.2.2 (when you created this issue) and removed from the README. More issues are fixed in 20.1 and the README will be updated upon its release. I'm not sure what else there is to document.

**Comment by ericharmeling** [comment]
@timgraham Thanks for the update! I'm going to close this issue for now.
