### ISSUE TITLE
Update SQLAlchemy docs to remove incorrect info that SAVEPOINT is faster

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/docs#6390]
In the [Build a Python app with SQLAlchemy](https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb-sqlalchemy.html) docs we say re: the `run_transaction()` wrapper method that:

> It will run your transactions to completion much faster than a naive implementation that created a fresh transaction after every retry error. Because of the way the CockroachDB dialect's driver structures the transaction attempts (using a [`SAVEPOINT`](savepoint.html) statement under the hood, which has a slightly different meaning in CockroachDB than in some other databases), the server is able to preserve some information about the previously attempted transactions to allow subsequent retries to complete more easily.

This is not actually correct.  Using an application-level retry loop that does not use `SAVEPOINT` is basically fine most of the time, and performs well if you add exponential backoff.

For context see the discussion in [this mailing list thread](https://groups.google.com/a/cockroachlabs.com/d/msg/eng/sej4jIqGAwo/0sEUSC06AwAJ), and also https://github.com/cockroachdb/cockroach/issues/5935

**Comment by vy-ton** [comment]
@ericharmeling @vy-ton Note that we should update this before the SQLAlchemy relaunch

**Comment by vy-ton** [comment]
> This is not actually correct. Using an application-level retry loop that does not use SAVEPOINT is basically fine most of the time, and performs well if you add exponential backoff.

Not sure I understand the desired outcome of this issue. My understanding of the current docs is that we do *not* recommend that `SAVEPOINT` is faster and encourage everyone to use the `run_transaction()` wrapper provided in CRDB's dialect. 

Are we saying that users should use an `application-level retry loop that does not use SAVEPOINT with exponential backoff` instead?

**Comment by rafiss** [comment]
> Not sure I understand the desired outcome of this issue. 

It seems that the desired outcome is to remove this paragraph from the docs. We can keep recommending use of `run_transaction`, but we might as well remove this paragraph if it's something that is still up for debate.
"It will run your transactions to completion much faster than a naive implementation that created a fresh transaction after every retry error. Because of the way the CockroachDB dialect's driver structures the transaction attempts (using a SAVEPOINT statement under the hood, which has a slightly different meaning in CockroachDB than in some other databases), the server is able to preserve some information about the previously attempted transactions to allow subsequent retries to complete more easily."

> My understanding of the current docs is that we do not recommend that SAVEPOINT is faster and encourage everyone to use the run_transaction() wrapper provided in CRDB's dialect.

One point of clarification perhaps: the `run_transaction()` wrapper in the dialect _does_ use `SAVEPOINT`.

> Are we saying that users should use an application-level retry loop that does not use SAVEPOINT with exponential backoff instead?

No, I think we should keep recommending the `run_transaction()` wrapper.

---

I'm not familiar with this earlier discussion about`SAVEPOINT` performance. To get an idea of the current state of things, I think we should check with people who worked on it in the 20.1 release. If we do need an answer about the current state of the world with SAVEPOINT performance, then we could ask Andrei
