### ISSUE TITLE
Improve description of write amplification

### ISSUE THREAD

**Issue by dbist** [cockroachdb/docs#6433]
Artem Ervits (dbist) commented:

Re: [JSONB](https://cockroachlabs.com/docs//v19.2/jsonb.html)

## Issue Description
Write amplification in the jsonb performance limitation should link https://tikv.github.io/deep-dive-tikv/key-value-engine/B-Tree-vs-Log-Structured-Merge-Tree.html#write-amplification
The one from Wikipedia talks about different type of amplification. As per @ajwerner 
## Suggested Resolution 
Change url

Jira Issue: DOC-420

**Comment by ajwerner** [comment]
I'm very :man_shrugging: on adding a like to tidb docs here. Maybe we could reference a paper on LSMs? Or have a footnote that says `Write amplification is the ratio of the amount of data written to the storage device versus the amount of data written to the database.` and then say that LSMs incur some background write amplification? 

Maybe somebody from the storage team wants to chime in on the exact language of why we want to avoid large values.

**Comment by ajwerner** [comment]
I think the point about write amplification is just that our storage engine uses LSMs which incur background write amplification. I don’t have much to say about the docs other than that they link to a Wikipedia article that is about a specific type of write amplification problem related to the internals of SSDs that is orthogonal to the write amplification we’re mentioning. 

When we write a value to CockroachDB we end up writing it to the disk multiple times. That’s what we mean by write amplification here. When values are smaller this work is better amortized over time. When values are large I suppose we have to do this we have to do this work more rapidly. When performing many small writes we get to batch the work up making the io sequential and cheaper per write which is a nice property of the storage engine. When performing large write the work was going to be sequential anyway because the value is large but because of the design of our storage engine we have to rewrite that large value numerous times.

**Comment by rmloveland** [comment]
@dbist thanks for filing, this should be fixed in https://github.com/cockroachdb/docs/pull/13666

which adds links to our own new write amp description in the context of Pebble / LSMs added in  https://github.com/cockroachdb/docs/pull/13141

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [DOC-420](https://cockroachlabs.atlassian.net/browse/DOC-420) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/docs-6433`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:

**Comment by rmloveland** [comment]
Fixed in #13666
