### ISSUE TITLE
Clojure example for transaction execution is outdated

### ISSUE THREAD

**Issue by kosii** [cockroachdb/docs#646]
The [example](https://www.cockroachlabs.com/docs/build-a-test-app.html#step-4-execute-transactions-from-a-client) tries to match on the error string whether it contains "restart transaction", instead of checking if the error code is 40001 or not

ping @knz

**Comment by knz** [comment]
Ok there are two issues here:

1. the doc is wrong: at https://www.cockroachlabs.com/docs/transactions.html#transaction-retries the error code is indeed 40001 (Serialization Failure) but the error message should be either `restart transaction` or `retry txn`. There is no message `retry transaction`. We really recommend checking if the message *begins* with "restart transaction:". For example a full message would be: `ERROR: restart transaction: retry txn "sql/executor.go:465 sql txn" id=93a60bd3 ...`

2. the Clojure example is using the error message (correctly) instead of the error code (which could be faster). Also it doesn't retry in the way recommended by the doc. So clearly the Clojure example can be improved.

I'll have a look at the Clojure code but in the meantime @kosii you can assume it's not completely wrong (it will actually do 80% of the right thing), and you can also compare with the other examples which are also OK.

**Comment by kosii** [comment]
My problem then is that my error message starts with `restart transaction`, but `PSQLException.getErrorCode` returns 0. The error message has the priority in such cases?

**Comment by knz** [comment]
I am surprised the error code is 0. Would you be ok with sharing a small example that demonstrates this?

**Comment by kosii** [comment]
totally, but I need to reduce first the code needed to reproduce it to a manageable size

**Comment by kosii** [comment]
@knz I created a [project](https://github.com/kosii/reprod-errorcode-problem) to reproduce the exception with error code 0. To run type `./sbt run`. 

On the other hand in a real project it makes no sense to wrap the query in a `Try`, because it will just make impossible for `DB.localTx` to detect if a rollback is necessary by hiding the throw from the statement.

**Comment by knz** [comment]
Thanks! We'll have a look.
I've logged https://github.com/cockroachdb/cockroach/issues/9317 to look into this as this is not strictly a Clojure issue any more.

**Comment by kosii** [comment]
thanks, I subscribed to the other issue too to be notified if more information is necessary

**Comment by jseldess** [comment]
@knz, any updates here?

**Comment by knz** [comment]
No update yet, but it's rather high on my to-do list still.

**Comment by knz** [comment]
Update on the Clojure code: I wrote a piece of code which successfully uses the retry protocol but is actually detrimental to performance, see https://github.com/cockroachdb/cockroach/issues/5935.
Until the performance issue is investigated I'd recommend not advertising this method for Clojure yet.

**Comment by spencerkimball** [comment]
@knz we do expect worse performance with the retries, although it shouldn't be too significant. The point of the retries isn't higher performance, it's to prevent starvation. Let's get these issues closed.
