### ISSUE TITLE
List regions CockroachCloud is available in our docs

### ISSUE THREAD

**Issue by kannanlakshmi** [cockroachdb/docs#6483]
Today, we talk about why certain regions aren't available in our Cloud docs. But if someone wants to see what regions we do support, they have to create an account and go into the console. We should list regions we support directly in docs, so a potential user can see that instead of having to sign into the console.

**Comment by Amruta-Ranade** [comment]
We already point them to https://cloud.google.com/about/locations/ and https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/

I don't think we want to have a list of their regions in our docs since they might update the list without us knowing. Thoughts?

**Comment by kannanlakshmi** [comment]
So the original intent to write this issue was because there can be regions such as eu-west-3 that we support if the customer opens a ticket but not directly on the console due to resource constraints. 
In such scenarios, I thought it would be helpful for a customer to see the original source of regions, then also see the console which might be a subset of the original source. 

Re: `I don't think we want to have a list of their regions in our docs since they might update the list without us knowing` we should be on top of this. At least the SRE team is usually. So I don't think this is a huge risk.

**Comment by Amruta-Ranade** [comment]
We do have a "Known issue" for regions with constraints:

~~~
Known issue: In addition to the non-GKE regions, we had to temporarily disable the following 4 GCP regions due to technical limitations that we are actively trying to resolve:

asia-northeast2
europe-north1
europe-west3
europe-west6
~~~

I am a bit hesitant to add the list of regions to our docs because the lists are very, very long :) Would it be better to include them as part of the product page instead of docs?

**Comment by kannanlakshmi** [comment]
Yeah I forgot about the known issue page when I opened the issue to be honest. Okay, you're right, its a very long list and we don't need to regurgitate it back. I am convinced, sorry for the hassle.

**Comment by Amruta-Ranade** [comment]
No worries! Closing the issue for now.
