### ISSUE TITLE
allocator: increase rebalance threshold 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6591]
PR: https://github.com/cockroachdb/cockroach/pull/44247

From release notes:
> The `kv.allocator.range_rebalance_threshold` [cluster setting](../v20.1/cluster-settings.html), which controls how far away from the mean a store's range count must be before it is considered for rebalance, is now subject to a 2-replica minimum. If, for example, the mean number of replicas per store is 5.6 and the setting is 5%, the store won't be considered for rebalance unless the number of replicas is lesser than 3 or greater than 8. Previously, the bounds would have been 5 and 6. [#44247][#44247] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
@darinpp I'd like to close this (automatically generated) docs issue, since:

1. We already have [cluster settings docs](https://www.cockroachlabs.com/docs/stable/cluster-settings.html) for this variable, as well as the note about the new heuristic in the [20.1-beta.1 release notes](https://www.cockroachlabs.com/docs/releases/v20.1.0-beta.1.html#general-changes)

2. Adding more info about this internal heuristic seems like excessive detail for a setting most users shouldn't change.

Therefore I'd like to close this.  Do you disagree?

**Comment by darinpp** [comment]
Yes, I agree that we should close it.
