### ISSUE TITLE
sql: fix locality information in show ranges

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6603]
PR: https://github.com/cockroachdb/cockroach/pull/43807

From release notes:
> [`SHOW RANGES`](../v20.1/show-ranges.html) now shows locality information consistent with the range descriptor when node ID and store ID don't match. [#43807][#43807] {% comment %}doc{% endcomment %}

**Comment by awoods187** [comment]
Show locality https://airtable.com/tblD3oZPLJgGhCmch/viwOj1Qb7D4gjtemc/reczIfEquEoXkFc6A

**Comment by jseldess** [comment]
I think this is the 20.1 AT epic, @awoods187, no? https://airtable.com/tblD3oZPLJgGhCmch/viwfjhxZjwRzBXeag/recoqxtzH1FW7DfGu?blocks=hide

**Comment by rmloveland** [comment]
@darinpp based on reading your commit message for cockroachdb/cockroach#43807 this appears to be a bug fix for how the output of `replica_localities` for a range is calculated.

From the user's perspective it does not look like our [docs for `SHOW RANGES`](https://www.cockroachlabs.com/docs/v20.1/show-ranges.html) need to be updated, since we don't document *how* the output of `replica_localities` is calculated.  We only document that the output exists, and what it means.

Therefore I propose that this docs issue can be closed.

Do you agree with that assessment?

**Comment by rmloveland** [comment]
@darinpp I'm closing this issue since I don't believe there is any docs work needed here.  Please feel free to re-open if you disagree.
