### ISSUE TITLE
cli/zip: make `cockroach zip` more resilient

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6739]
PR: https://github.com/cockroachdb/cockroach/pull/44342

From release notes:
> Previously, `cockroach debug zip` would only print an informational message about a piece of data it was retrieving *after* the data was retrieved (or an error was observed). This patch changes it to print a message beforehand as well. This enables better troubleshooting of hanging queries. [#44342][#44342] {% comment %}doc{% endcomment %}
>
> `cockroach debug zip` now properly supports special characters in database and table names. [#44342][#44342]
>
> `cockroach debug zip` will now apply [the `--timeout` parameter](../cockroach-node.html) to the SQL queries it performs (there was no timeout previously, causing `cockroach debug zip` to potentially hang). [#44342][#44342]
>
> `cockroach debug zip` is now able to tolerate more forms of cluster unavailability. Nonetheless, in case system ranges are unavailable, it is recommended to run `cockroach debug zip` towards each node address in turn to maximize the amount of useful data collected. [#44342][#44342]

**Comment by jseldess** [comment]
Also backported, at least in part, to 19.2: https://github.com/cockroachdb/docs/issues/6964

**Comment by taroface** [comment]
@knz Question about the last release note item above. Is the guidance that `cockroach debug zip` should always be run with the `--host` flag specifying a node address? Also, when you say "maximize the amount of useful data collected", can you clarify what this means?

**Comment by knz** [comment]
>  Is the guidance that cockroach debug zip should always be run with the --host flag specifying a node address?  

1) That is already the case (or should have been since inception) -- it's unlikely that the command would be run on the same machine as one of the cockroachdb nodes, so there's no way other than specifying `--host` to point the utility at a cluster.

2) what the release note is saying is that IF the command fails to collect data for _all_ nodes automatically  when pointed to _one_ of them, THEN you should retry the command pointing it at every remaining node in turn, until it successfully collects data for all nodes. 

For context: `debug zip` *tries* do auto-discover nodes an gather data automatically, but this discovery can fail e.g. when there is a network partition or some other sort of network hiccup. In that case, it may be sufficient to point the tool just once at each "side" of the network problem. In other cases, it may be necessary to try every node individually. The guidance should be "point to individual nodes *until data has been gathered for the entire cluster* (which can happen before every node has been tried)"

> Also, when you say "maximize the amount of useful data collected", can you clarify what this means?

If the user does not do what is explained above, they will only have data for part of the cluster. By running the command again to point at all the missing parts, they will gather more. So trying more nodes maximizes the amount of data collected.
