### ISSUE TITLE
kv: document GC TTL strict mode

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/docs#6817]
In https://github.com/cockroachdb/cockroach/pull/45826 we introduced strict enforcement of the GC TTL. It can be disabled with a cluster setting. This change and specifically its associated cluster setting likely deserves a mention somewhere in the docs. Most users most of the time are unlikely to bump up against this given the default 25h TTL. Furthermore, I suspect many users will find this new behavior of actually enforcing the TTL to be easily understandable. 

Confusion had occurred in the past where users became accustomed to the TTL not being enforced (in fact that user didn't even know it existed). 

cc @rmloveland

**Comment by rmloveland** [comment]
Thanks @ajwerner !

**Comment by rmloveland** [comment]
After talking with Andrew about this during work on #6003, we decided not to document this.  Turns out it's more of a UX improvement, in that it makes GC behave as one might think it should. 

Further evidence in favor of not documenting: it's also a non-public cluster setting (not visible when you run `SHOW CLUSTER settings`).
