### ISSUE TITLE
storage: enforce gc ttl strictly

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#6969]
PR: https://github.com/cockroachdb/cockroach/pull/45826

From release notes:
> The timing of garbage collection for historical data is defined by the `gc.ttlseconds` variable in the applicable [zone configuration](../v20.1/configure-replication-zones.html#replication-zone-variables). However, in practice, data is not garbage collected immediately after the TTL passes. The new `kv.gc_ttl.strict_enforcement` [cluster setting](../v20.1/cluster-settings.html) makes sure that `AS OF SYSTEM TIME` queries older than the TTL, but before GC has happened, return an error. [#45826][#45826] {% comment %}doc{% endcomment %}

**Comment by jseldess** [comment]
@rmloveland, I worked with @ajwerner to rewrite this release note, so I'm happy to take the docs work as well, if you like. Your call.

**Comment by rmloveland** [comment]
Thanks @jseldess I'll take it - need to stay up on developments in this area.

**Comment by rmloveland** [comment]
After talking with Andrew Werner about this during work on #6003, we decided not to document this.  Turns out it's more of a UX improvement, in that it makes GC behave as one might think it should. 

Further evidence in favor of not documenting: it's also a non-public cluster setting (not visible when you run `SHOW CLUSTER settings`).
