### ISSUE TITLE
ALTER PRIMARY KEY Doc Update - automatic unique index?

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/docs#7076]
Re: [ALTER PRIMARY KEY](https://cockroachlabs.com/docs//v20.1/alter-primary-key.html)

## Issue Description

When talking about altering primary keys to support geo partitioning we say 

> Note that the old primary key index on id is now the secondary index users_id_key.

Do we want that? If we do this, how will we be able to geo-partition the index (that doesn't have a city prefix) that is created when we try to partition the table?

cc @awoods187

**Comment by awoods187** [comment]
We do want this because developers may not realize that the primary key is also an index in CockroachDB. This can prevent performance regressions in the wild. We don't create this index  for other cases (like hash sharding indexes) where it wouldn't be helpful. We should explain that this index exists and that for partitioning use cases you will need to drop it or partition it according to your workload needs.

**Comment by ericharmeling** [comment]
Great catch. We should definitely point out that secondary indexes created by `ALTER PRIMARY KEY` are not partitioned, even if the original primary key index was. I'll open a docs PR.

@rohany Do we plan on propagating the partitions of primary key indexes to secondary indexes created by `ALTER PRIMARY KEY`?

**Comment by rohany** [comment]
We don't automatically apply any partitioning on the old primary index onto the new secondary index that is created (not sure we have plans to do this either).
