### ISSUE TITLE
Document time for leader election and lease acquisition

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#7360]
From @nvanbenschoten:

> Leases expire in a maximum of 9 seconds, with an average expected time of 4.5 seconds. I’d round up to 10 seconds to give time for the actual leader election and lease acquisition. This does seem like something we should document.

Need to find the right place(s):
- https://www.cockroachlabs.com/docs/v20.1/architecture/replication-layer.html#raft
- https://www.cockroachlabs.com/docs/v20.1/architecture/replication-layer.html#leases

**Comment by jseldess** [comment]
Question on this from our community slack:

> One more question. Knowing that CRDB uses Raft for replication, when a CRDB instance is killed, a new leader should be elected really fast (probably udner a second), but what i'm observing is that it takes around 10-15 seconds for the cluster to go back to working well. Is that normal and what are the reasons for such a time needed for the cluster to go back to normal state?
>
> Can the Raft elect time be configured?

**Comment by bdarnell** [comment]
Leases expire in 9s, but raft elections use a randomized timeout of up to double that, so there's a worst case of 18s before we start the election. And then the leader election itself takes (i think) 4-5 network round trips on top of that, but I'd call that out separately instead of just "rounding" to give a worst-case time to recovery of 20s.

**Comment by rmloveland** [comment]
Fixed by #10917
