### ISSUE TITLE
sql: how to set SNAPSHOT isolation level for a transaction through JDBC

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/docs#753]
Some drivers, like JDBC, allow you to set the transaction isolation level with pre-defined constants. Since there's no `SNAPSHOT ISOLATION` constant defined for JDBC, does CockroachDB automatically assign `SNAPSHOT ISOLATION` if the client sets `READ COMMITTED`? If you set `READ COMMITTED`, does it always use `SERIALIZABLE SNAPSHOT` in CockroachDB?

The answer to this question is not in the docs.

+cc @andreimatei @kainkain

**Comment by bdarnell** [comment]
Yes, if you ask for `READ COMMITTED`, we'll give you snapshot. The mapping in code is [here](https://github.com/cockroachdb/cockroach/blob/73b645860073a2c26a1b0336d590b55db5c3c285/sql/parser/sql.y#L1330-L1350). I think you could also execute a `SET TRANSACTION ISOLATION LEVEL SNAPSHOT` statement just by executing a string query instead of using the `setTransactionIsolation()` method.

**Comment by tschottdorf** [comment]
@jseldess a paragraph added about this in https://www.cockroachlabs.com/docs/transactions.html#comparison-to-ansi-sql-isolation-levelshttpsenwikipediaorgwikiisolationdatabasesystemsisolationlevels would help.

**Comment by tschottdorf** [comment]
(Also, I'm not sure why the anchor in the link above is so awkwardly named).

**Comment by jseldess** [comment]
@sploiselle has an open PR to improve our transaction overview doc and complete our transaction-specific SQL statement docs: https://github.com/cockroachdb/docs/pull/672

@sploiselle, can you factor the above into that work?

**Comment by sploiselle** [comment]
Will do

**Comment by jseldess** [comment]
@sploiselle, did this get included in https://github.com/cockroachdb/docs/pull/672?

**Comment by sploiselle** [comment]
@jseldess This equivalence is surfaced in the [transaction doc](https://www.cockroachlabs.com/docs/transactions.html#comparison-to-ansi-sql-isolation-levels). I added a small amount of detail to the doc around these, but nothing drastic. This might be good forum fodder since it's nested in the docs.

Not closing issue until we determine a better solution for surfacing answers like these.

**Comment by debraj-manna** [comment]
@bdarnell @jseldess I have added `conn.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);` but as per this [discussion](https://forum.cockroachlabs.com/t/what-does-the-transaction-retry-error-retry-delete-range-mean/1089/2) it looks like it is still acting like `SERIALIZABLE`.  The logs are attached in the discussion.

**Comment by jseldess** [comment]
`SNAPSHOT` was deprecated in 2.0 and will be removed in 2.1, so closing this issue.
