### ISSUE TITLE
Wrong link in Java/Hibernate hello work example

### ISSUE THREAD

**Issue by vy-ton** [cockroachdb/docs#8006]
The link to "Install Client Drivers: Hibernate" [here](https://www.cockroachlabs.com/docs/v20.1/build-a-java-app-with-cockroachdb-hibernate), should point to https://www.cockroachlabs.com/docs/v20.1/install-client-drivers#hibernate

**Comment by jseldess** [comment]
That is the current link, but it's not working properly. @yingzhuchin, perhaps you can help figure out why.

**Comment by yingzhuchin** [comment]
That's because the "Hibernate" section is itself on a page identified via a URL fragment, namely https://www.cockroachlabs.com/docs/v20.1/install-client-drivers#java. So to link to Hibernate, you'd have to do https://www.cockroachlabs.com/docs/v20.1/install-client-drivers#java#hibernate, which is not supported. There can be only one anchor link per URL.

**Comment by yingzhuchin** [comment]
If we want to be able to link to "Hibernate," then we should consider making the "Java," "Go," "Ruby" etc. options their own pages with distinct URLs, the way options are done here: https://www.cockroachlabs.com/docs/v20.1/cockroach-cert

**Comment by jseldess** [comment]
Thanks for looking into this, @yingzhuchin. Instead of breaking this page into many pages, perhaps we can just link to https://www.cockroachlabs.com/docs/v20.1/install-client-drivers.html#java, which filters the page to show just Java options. @ericharmeling, @vy-ton, would you be ok with that?
