### ISSUE TITLE
Guidance on ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8026]
From @robert-s-lee:

https://www.cockroachlabs.com/docs/v20.2/transaction-retry-error-reference.html#abort_reason_timestamp_cache_rejected has "This can happen due to a range merge happening in the background, or because the timestamp cache is an in-memory cache, and has outgrown its memory limit (about 64 MB)."

- What are the settings that should be changed increase so that timestamp cache is an in-memory cache is beyond the 64MB

- Under what edge condition in Range Merge does this error manifests? (ie: Merge is happening while the insert is going on the left side of the merge range?)

gz#6100

gz#6482

**Comment by jseldess** [comment]
@awoods187, @rmloveland, @ericharmeling, not sure who should be taking transaction retry work going forward, so pinging you all. This issue is derived from https://github.com/cockroachlabs/support/issues/572.

**Comment by awoods187** [comment]
This seems like a reasonable request and enhancement over the initial docs. Rich do you have the time to address this in the next quarter or so? It probably makes sense for you to be the one to extend this but i don't think its so urgent it should block spatial work.

**Comment by rmloveland** [comment]
Sure I'll grab it!

**Comment by BramGruneir** [comment]
Hi, has there been any movement on this issue?  We've got it linked directly to a customer request. https://cockroachdb.zendesk.com/agent/tickets/6100

**Comment by jseldess** [comment]
@rmloveland, would it make sense to hand this off to @ericharmeling or @ianjevans at this point?

**Comment by rmloveland** [comment]
> @rmloveland, would it make sense to hand this off to @ericharmeling or @ianjevans at this point?

I'm not sure.  At least this seems more KV than SQL tbh.  Although it ended up in the SQL docs backlog, so maybe.

Sorry for the delay, this has been sitting as a low priority issue.  Is it now a high priority issue?

Linked support ticket lists priority as "low".

**Comment by BramGruneir** [comment]
Not high priority, but it was requested by a customer is all.

**Comment by jseldess** [comment]
OK, sorry for the confusion. @rmloveland, feel free to keep the issue if you've already prioritized it with PMs.

**Comment by rmloveland** [comment]
Bram Gruneir ***@***.***> writes:

> Not high priority, but it was requested by a customer is all.

Makes sense!  Thanks for bumping Bram!  Just wanted to get a sense of
priority.  If a customer needs this I would def like to move it up.

I'm going to add this to the KV docs queue and discuss with @mwang1026
re: prio

**Comment by BramGruneir** [comment]
@rmloveland Any movement on this?

**Comment by rmloveland** [comment]
No but I'm going to start working on it now!  Thanks for the bump Bram!

@andreimatei looking at [58d618](https://github.com/cockroachdb/cockroach/commit/58d618) and have a few questions - lemme know if you are the wrong victim:

1. It looks like you renamed the error code from `ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY` to the shorter `ABORT_REASON_TIMESTAMP_CACHE_REJECTED` in the above commit, is that correct?

2. Aside from the name, it looks like the error is about "the same" as it was before, and the docs for [`ABORT_REASON_TIMESTAMP_CACHE_REJECTED`](https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_timestamp_cache_rejected) that we have should apply? tl;dr: "just retry"

3. (Via Robert's original post above) Is there a user-visible setting that can be changed so that the timestamp cache size in memory is beyond the 64MB default value? (I looked at the [cluster settings](https://www.cockroachlabs.com/docs/stable/cluster-settings.html) and did not see anything obvious).  If such a setting does exist, would changing that setting (1) help this problem and/or (2) have any potential negative consequences the user should be aware of before changing it?

4. (Also via Robert above) "Under what edge condition in Range Merge does this error manifests? (ie: Merge is happening while the insert is going on the left side of the merge range?)". TBH I'm skeptical that going into this level of detail w.r.t range merge operation vs. transactions will actually be helpful to most users since there isn't much they can do about it b/c merges are automatic - right?.  AFAICT the real thing to do about this is not to suss out the arcane interaction of range merges and transactions but rather to "retry the transaction".  But that is just my hallucination. What do you think?

**Comment by pxlogan** [comment]
@rmloveland @BramGruneir Any update on this?

**Comment by rmloveland** [comment]
@pxlogan unfortunately not yet

@andreimatei do you have answers for [the questions above](https://github.com/cockroachdb/docs/issues/8026#issuecomment-926146175)?  or alternatively, is there someone else I should ask?

**Comment by andreimatei** [comment]
> It looks like you renamed the error code from ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY to the shorter ABORT_REASON_TIMESTAMP_CACHE_REJECTED in the above commit, is that correct?

That commit split `ABORT_REASON_TIMESTAMP_CACHE_REJECTED_POSSIBLE_REPLAY` into two - ` ABORT_REASON_NEW_LEASE_PREVENTS_TXN` and `ABORT_REASON_TIMESTAMP_CACHE_REJECTED`. The `LEASE_PREVENTS_TXN` is a common case where a lease has been transferred after a transaction has started. Unfortunately we don't yet handle these well, and the transaction has to retry. The vanilla `ABORT_REASON_TIMESTAMP_CACHE_REJECTED` remains as a catch all for other things that might have happened, and the transaction also needs to be retried.

> Aside from the name, it looks like the error is about "the same" as it was before, and the docs for ABORT_REASON_TIMESTAMP_CACHE_REJECTED that we have should apply? tl;dr: "just retry"

Right.

> (Via Robert's original post above) Is there a user-visible setting that can be changed so that the timestamp cache size in memory is beyond the 64MB default value? (I looked at the cluster settings and did not see anything obvious). If such a setting does exist, would changing that setting (1) help this problem and/or (2) have any potential negative consequences the user should be aware of before changing it?

No, it doesn't seem like we allow any customization of the size. And it also seems that we don't control the size very well. I think the cache grows enough to hold at least 10 seconds worth of reads. Beyond that, I think it has a minimum size of 32MB. I don't know how to think about the maximum size (apart from the 10s memory).

> (Also via Robert above) "Under what edge condition in Range Merge does this error manifests? (ie: Merge is happening while the insert is going on the left side of the merge range?)". TBH I'm skeptical that going into this level of detail w.r.t range merge operation vs. transactions will actually be helpful to most users since there isn't much they can do about it b/c merges are automatic - right?. AFAICT the real thing to do about this is not to suss out the arcane interaction of range merges and transactions but rather to "retry the transaction". But that is just my hallucination. What do you think?

On a range merge, the cache covering the right-hand-side of the merge is lost, unless the leases for the left and the right ranges happen to be collocated.
Robert's question talks about an "insert" but, fwiw, the errors we're discussing here technically only happen on commits.
I would not going into too many details in the documentation, other than perhaps mentioning that range merges are one of the reasons why this error can be produced. Range merges sound like data movement, so they might elicit sympathy from readers.

**Comment by rmloveland** [comment]
Thanks @andreimatei 

@pxlogan , @BramGruneir : based on the above what I plan to PR into docs is basically:

1. add the new error code
2. the guidance will still be "retry it"
3. as Andrei says we will mention that [range merges](https://www.cockroachlabs.com/docs/stable/architecture/distribution-layer.html#range-merges) are one of the reasons this can happen

should be able to post a docs PR sometime today or tomorrow

**Comment by andreimatei** [comment]
> add the new error code

I'm confused because [the docs](https://www.cockroachlabs.com/docs/v21.1/transaction-retry-error-reference.html#abort_reason_timestamp_cache_rejected) seem to have the new code already,

**Comment by rmloveland** [comment]
> I'm confused because the docs seem to have the new code already,

Ah.  Sorry, this is old, I lost all the context.

In that case I think this can be closed?  I don't really know what this issue is asking for then.  Seems like it just wanted answers to Robert's questions?  Which you answered above as "nope, no customization" and "what's in the docs is probably enough detail about range merges".

In that case I'm inclined to close this since the docs already have the code and description.

Any objections @pxlogan or @BramGruneir ? is there something additional we need to do here?

**Comment by rmloveland** [comment]
Hey all, since it appears there is nothing left to do here I'm gonna close this.  

Specifically:

- The questions Robert initially asked were answered by Andrei AFAICT and the answers aren't really something that will make sense to go into the docs
- The docs have the retry error code and some info about range merges already

If there is a specific additional ask, please re-open and explain my misunderstanding of the above.  Thanks!
