### ISSUE TITLE
Re-org Backup / Restore / CDC docs in side nav

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8050]
Currently, our docs for BACKUP/RESTORE and CDC are hidden in our side nav / hard to find:
- BACKUP/RESTORE docs are smushed into two docs with non-descriptive titles under Maintain ("Backup and Restore Overview" and "Backup and Restore - Advanced Options")
- CDC is under Deploy > Enterprise Features

Proposed changes:

Guides > Deploy
- Back up and Restore Data
    - Default Behavior
    - Revision History and Point-in-time Restore
    - Encrypted Backup and Restore
    - Locality-aware Backup and Restore
    - Scheduled Backups (new in 20.2)
- File Storage
    - Overview
    - External Storage
    - Nodelocal Storage (new in 20.2)
    - Userlocal Storage (new in 20.2)
    - Local File Server
- Streaming Data Out (CDC)

Overview of changes:
- I suggest moving Backup/Restore docs under Deploy, since this is something the user would do during set up (and probably not configure frequently once it's set) instead of something they do as maintenance (like rotating certs).
- "File storage" becomes its own subheading-- currently, it's included in BACKUP/RESTORE/IMPORT/EXPORT and makes those pages long and convoluted. Might be easier to parse, and also allows for the addition of nodelocal storage (without trying to shoehard it in to the BACKUP/RESTORE/etc. pages).
- Rename "Change Data Capture" to "Streaming Data out". Move out from under Enterprise Features (Enterprise Features also has Table Partitioning nested under it, which should also probably be moved but not sure if that should be included in this re-organization. Once the Partitioning / CDC pages are moved, Enterprise Features can just be one landing page with the list).

@mwang1026 and @jseldess do you have any feedback on the above? I'd like to make these changes in the next couple of weeks, before I add docs on scheduled backups and nodelocal storage.

**Comment by mwang1026** [comment]
Love it -- how it emphasizes Backup/Restore as deploy setup, makes the docs easier to read, etc. A few minor notes:
- We should have nodelocal and userlocal as different "file" storages. Nodelocal is storing on the node, is admin only, can be turned off with a cluster setting. Userlocal is loading data into tables as blobs, and permission control is controlled by grants to the tables that the data is loaded into -- also that it's not true "file storage" in the literal sense
- Technically it's streaming data out -- not sure if that clarification is required (since some people do also want to stream data in, although it's less common)
- I like the restructuring of CDC docs, especiallty since it's unclear what data should live where and we have the overall Change Data Capture doc which has some info that should be in the Changefeed doc and vice versa

Thanks so much for spearheading this!

**Comment by jseldess** [comment]
I love this direction as well. I like "Backup and Restore Data" and "File Storage" as categories under deployment, and I think we will end up moving more stuff under deployment eventually. Would "File Storage for Bulk Operations" be more precise, or is that not accurate?

I'm not sure about the naming of pages under the new categories. I don't think we should name a page "Default Behavior" or "Overview". I imagine the proposal is to just show that language in the sidenav and have more specific filenames? IN that case, I'd like to know the proposed filenames. Generally, I'd prefer for us to start naming pages so that it's clear what *type* of content they're getting. If it's guidance on doing something (i.e., a how-to), we should try to lead with an active verb. Would you take a shot at that? I know the rest of the Deploy section doesn't follow this pattern, but Ryan and I have plans to change that in the not distant future. We really need the docs to reflect important tasks/actions (Start a Cluster, Scale a Cluster, Decommission a Node, Upgrade a Cluster, etc.). 

Also, to date, we're avoiding gerunds, so I'd change "Streaming Data Out (CDC)" to "Stream Data Out (CDC)" as well. I'm open to revisiting gerunds, but we should be consistent for now. I wonder if a more explicit title like "Stream Data Out of CockroachDB" would be even better?

**Comment by lnhsingh** [comment]
Thanks for the feedback! Yes, this is the proposed language for the sidenav. With that in mind, I've added the proposed full page titles in the parentheticals. Let me know what you think:

Guides > Deploy
- Back up and Restore Data
    - Full and Incremental Backups (Take Full and Incremental Backups)
    - Backups with Revision History and Point-in-time Restore (Take Backups with Revision History and Restore from a Point-in-time)
    - Encrypted Backup and Restore (Take and Restore Encrypted Backups)
    - Locality-aware Backup and Restore (Take and Restore Locality-aware Backups)
    - Scheduled Backups (Take and Restore Schedule Backups)
- File Storage for Bulk Operations
    - Overview (Supported Storage Options for Bulk Operations)
    - External Storage (Use External Storage for Bulk Operations)
    - Nodelocal Storage (Use Nodelocal Storage for Bulk Operations)
    - Userlocal Storage (Use Userlocal Storage for Bulk Operations)
    - Local File Server (Use a Local File Server for Bulk Operations)
- Stream Data Out of CockroachDB (Stream Data Out of CockroachDB with Change Data Capture)

**Comment by mwang1026** [comment]
`Scheduled Backups (Take and Restore Schedule Backups)` -- you're technically creating a schedule, and the schedule does the taking of backups. Restore is also not really related to schedules directly.

`Stream Data Out of CockroachDB (Stream Data Out of CockroachDB with Change Data Capture)` My vote is for `with Changefeeds` since Changefeeds are the actual feature -- Change Data Capture is a concept.

**Comment by lnhsingh** [comment]
Thanks @mwang1026. Changed to `Schedule a backup` and `Stream Data Out of CockroachDB Using Changefeeds`

**Comment by mwang1026** [comment]
Another nit :D Technically we only allow creation of recurring schedule of backups, rather than scheduling a *single* backup to run some time in the future. So maybe `Set up a backup schedule`?

**Comment by lnhsingh** [comment]
Ah yeah, that makes more sense! Changed

**Comment by jseldess** [comment]
This SGTM. I wonder if we eventually would want Backup and Restore to be its own section following "Deploy", similar to "Migrate". For now, this is good. 

Few nits:

- There's still a Filestorage link in the Maintain section of the sidenav:
    <img width="497" alt="Screen Shot 2020-08-31 at 4 37 13 PM" src="https://user-images.githubusercontent.com/15893490/91766253-4a314f00-eba8-11ea-8b77-9e751eb1c589.png">
- These changes need to be ported to 20.1 docs as well. We don't need to go further back than that. 
- What are we doing about the CDC doc?

**Comment by lnhsingh** [comment]
> There's still a Filestorage link in the Maintain section of the sidenav:
This is moved under `File Storage for Bulk Operations` (it's the `Local File Server` doc)
> These changes need to be ported to 20.1 docs as well. We don't need to go further back than that.
Is there a reason why this should be ported to 20.1? I view this as a necessary change due to the IO features being added in 20.2 (i.e., Schedule backups, nodelocal storage, userlocal storage). It's a time consuming change and making the updates to 20.1 would add another couple days of work. If you think it's required, I might tackle the 20.1 updates in a separate PR (possibly after the release or at least until I've done most of my 20.2 roadmap work).
> What are we doing about the CDC doc?
The current `Change Data Capture` doc will be renamed `Stream Data Out of CockroachDB Using Changefeeds` (`Stream Data Out of CockroachDB` in the sidenav) and moved into the Deploy section
