### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by yzdocs** [cockroachdb/docs#8081]
Exalate commented:

Pages that currently break breadcrumbs:
- https://www.cockroachlabs.com/docs/stable/migration-overview.html
- https://www.cockroachlabs.com/docs/stable/migrate-from-oracle.html
- https://www.cockroachlabs.com/docs/stable/migrate-from-postgres.html
- https://www.cockroachlabs.com/docs/stable/migrate-from-mysql.html
- https://www.cockroachlabs.com/docs/stable/migrate-from-csv.html
- https://www.cockroachlabs.com/docs/stable/migrate-from-avro.html
- https://www.cockroachlabs.com/docs/stable/import-performance-best-practices.html

Jira Issue: DOC-653

**Comment by luciaaaaaaa** [comment]
Hi @jseldess I started a Figma project where I'm going to keep putting files for the design work on the github issues. 

Here are wireframes for the breadcrumbs https://www.figma.com/file/gUgY9eSxcWpLENJHLS5FZv/GitHub-Issues?node-id=301%3A2754 

Could you provide more details why https://www.cockroachlabs.com/docs/stable/third-party-database-tools.html would break the breadcrumbs? Right now, I find the difference between the side-nav title and the article title confussing. If we renamed the page Overview - Third-Party Database Tools Would that fix it?

**Comment by jseldess** [comment]
I'm not sure why that page would break breadcrumbs. Previously, that page was displayed when clicking "Third-Party Database Tools" directly. Now, we display the page when "Overview" is clicked. We made that change due to https://github.com/cockroachdb/docs/issues/9826, I think. 

@yingzhuchin, do you remember why the third-party database tools page was breaking breadcrumbs?

**Comment by yingzhuchin** [comment]
Yes, here's the Slack conversation about: https://cockroachlabs.slack.com/archives/C019NHZ819S/p1598388635008000

Essentially that page was listed in the sidebar twice, under both TUTORIALS and REFERENCE. I'm guessing we've made changes since that avoid the behavior, so the issue can't be seen anymore.

Here's another example that still demonstrates the issue: https://www.cockroachlabs.com/docs/stable/migration-overview.html

This page shows up on the sidenav twice, once under CockroachCloud and once under CockroachDB.

**Comment by luciaaaaaaa** [comment]
If we implement breadcrumbs ideally we should also show them as tags in the search results like this: 

![image](https://user-images.githubusercontent.com/48258790/113020801-f3e1ba00-9150-11eb-836a-e83de387f884.png)
