### ISSUE TITLE
Add Restore Table/Database module guidance to CockroachCloud docs

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#8483]
Recovery Information link (table/database):
- Link opens modal with information for push-button RESTORE
- User pushes button to RESTORE
- User checks status on the CC Ops List Page (and is kicked there once job starts)

**Comment by jseldess** [comment]
@lnhsingh, is this issue the same as https://cockroachlabs.atlassian.net/browse/CC-1772?src=confmacro? Do we expect to have these docs in place for the 20.2 release, or will it come later since CC isn't on the same cadence. Trying to figure out if we should call this out in the 20.2 release notes. 

cc @mwang1026, @kannanlakshmi

**Comment by mwang1026** [comment]
It's possible but I would say don't plan on the RESTORE changes being ready for marketing release.

**Comment by lnhsingh** [comment]
Likely we'll release RESTORE to GCP before AWS, with AWS coming later.
