### ISSUE TITLE
logging: clarify how to send logs to stdout

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/docs#8654]
At the page https://www.cockroachlabs.com/docs/v20.1/debug-and-error-logs.html#output-locations
it discusses the various output locations for the logs including sending the logs to stderr. However, when logs are sent to stderr via the `--logtostderr` in systems like k8s they are categorized as error messages - even the routine stats messages in the logs.

In the slack discussion: https://cockroachlabs.slack.com/archives/CHVV403F0/p1602627306071000

@dbist suggested setting the flag `--log-dir=''` to disable file-based logging. My testing observed that doing this does send the logs to stdout assuming the flag `--logtostderr` is not present.

Suggest consider adding "Prints to stdout" as another option to that docs page, and explain the above.

**Comment by knz** [comment]
Logs are _never_ sent to stdout.
You can quickly check this with the following command

```
$ cockroach start ... --log-dir='' >/dev/null  # this redirect kills stdout, not stderr
```

Which will reveal the logs go on stderr.

What you are observing is that k8s/docker merge stderr and stdout together. 

This sentence:

> However, when logs are sent to stderr via the --logtostderr in systems like k8s they are categorized as error messages

The best practice is to **not use --logtostderr in production**.  Let the logs go to files, and collect these files for retention out of the pod.

Something to keep in mind is that `--log-dir=''` also removes log file redactibility (big feature ask from our larger  accounts), and also prevents the splitting of different logging outputs to different files (another big feature ask, so that logs can be analyzed more easily).

**Comment by sheaffej** [comment]
Thanks @knz for the clarification. Given this, I will close this issue to take it off the queue. The docs do cover the set of recommended configurations.
