### ISSUE TITLE
release-20.2: docker: Base the docker image on RedHat UBI

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#8685]
Jesse Seldess (jseldess) commented:

PR: https://github.com/cockroachdb/cockroach/pull/55130

From release notes:
> <a name="new-docker-image"></a>CockroachDB Docker images are now based on the RedHat UBI 8 base image instead of Debian 9.12 slim. This will help on-premise customers from a security and compliance perspective. [#55130][#55130] {% comment %}doc{% endcomment %}

Jira Issue: DOC-805

**Comment by taroface** [comment]
@jseldess This sounds relevant to operators, but I also can't figure out where & how it would be documented. @jlinder Could you comment on what, if any, information we should communicate about this change for deployment scenarios? Maybe it merits a callout in the [Production Checklist](https://www.cockroachlabs.com/docs/dev/recommended-production-settings.html)? 

Otherwise this change is already noted in previous release notes.

**Comment by jlinder** [comment]
Hi. I'm not sure where this might get documented in addition to existing release notes, though I don't think the Production Checklist is the place. Here is how existing customers may be affected.

- If a customer uses our docker image and build on top of the image (like adding their own programs or install additional programs using the built-in system package manager), then they will likely need to modify their build scripts.
- If they expect certain programs other than cockroach to exist on the image, they may not exist (ex: we had one program that we needed to install because it was missing in the new OS base image that our CC + k8s deployment scripts depended on, which prompted a subsequent fix).

For new customers, it would only affect them as they figure things out. Do we state anywhere in our docs what OS we base our docker images on? Those would be places to update. 

Also, the change https://github.com/cockroachdb/cockroach/pull/55467 was also made, which was a follow-on to the change related to this issue. If you end up adding notes on these changes to the documentation, I recommend specifically mentioning we use the `RedHat ubi8/ubi-minimal` image since it uses a different package manager than the other RedHat images.
