### ISSUE TITLE
CircleCI: Automated push to prod

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/docs#87]
We need a way that anyone in our org can use to push docs to the production server. Need to consider that master might be used as a testing branch, so it may not always be suitable for pushing. We could instead use a `prod` branch or something that is auto-pushed, and we manually push to that when we're ready to deploy stuff. I'm not thrilled by that, but it works. Better ideas?

**Comment by mjibson** [comment]
Other ideas discussed with @jseldess: use `docs.cockroachlabs.com` and have github pages build it. This would require using CloudFlare because that's the only way (that I'm aware of) to have HTTPS on github pages with a CNAME. @mberhault thoughts? Doesn't have to be for the entire domain (although we may want to do that anyway for the CDN benefits).

**Comment by jseldess** [comment]
So just to make sure we're all clear, currently, we use github to manage our doc files, and I manually sync Jekyll output from my machine to dreamhost. So github and our live docs are completely separate right now. 

Matt's suggestion would be to treat our gh-pages branch (the master branch) as our live content, cutting out the need to sync to some other server. Github Pages already uses Jekyll to serves it up at http://cockroachdb.github.io/docs/. We would need to:

- Add a CNAME for docs.cockroachlabs.com
- Use cloudflare as our cdn, since they'd provide https
- Redirect from cockroachlabs.como/docs to docs.cockroachlabs.com

I think this sounds good but am interesting in thoughts from @mberhault, @bdarnell, @spencerkimball. The only downside here is that someone may merge with master and break the live site, not having built with Jekyll locally to validate that the html is fine. This isn't a big danger, though, since others are likely to be working on actual content, not Jekyll stuff.

**Comment by bdarnell** [comment]
Github pages places some restrictions on the URL scheme we can use (i.e. it must be a subdomain docs.cockroachlabs.com rather than our current planned URL of cockroachlabs.com/docs). Can we add a cron job on the machine that's serving `www` to run `git pull` and rebuild? Or we could set up circleci to build and push (as long as we're comfortable giving CI machines the necessary credentials)

**Comment by jseldess** [comment]
@bdarnell, do you prefer that approach over just going with docs.cockroachlabs.com and using Github? That url is fine, too, but if we change, we'll definitely want to change before beta.

**Comment by bdarnell** [comment]
I don't feel strongly about the URL, but I do think that we'll eventually want more flexibility than GH Pages gives us and so we'll need one of the other solutions anyway. I'm fine with doing whatever's easiest for now.

**Comment by mberhault** [comment]
I'm not so sure we need to have an automated pipeline for docs.
Granted, they're changing a lot right now, and having anyone able to push them is nice. However, once we hit beta, I expect docs will be much more strictly versioned, possibly from separate branches that turn into versioned pages on docs.cockroachlabs.com

Now, it would still be nice to push them automatically. We do need to make sure they're not broken though. Does Jekyll catch errors? is it worth putting in circle-ci to validate the generated pages?
Either way, we can end up with a branch that's either pushed to from circle-ci, or manually. From there, we can either have circle-ci generate the pages and copy them over to docs.cockroachlabs.com (would require an ssh key), or have a cron job in docs.cockroachlabs.com pull down the docs and place them in the right directory (would require jekyll and dependencies)

**Comment by jseldess** [comment]
@mberhault, Jekyll doesn't catch errors in the generated html, no, but I've been meaning to look into this html proofer: https://github.com/gjtorikian/html-proofer. Could we run that type of thing with circle ci? Would we want to trigger that whenever a PR is merged with master, or should we use a different branch?

**Comment by jseldess** [comment]
We now use Circle CI to check the html for each docs PR and push the site to aws for review. 

Now that that's in place, it'd be interesting to think through a prod deployment step, though I don't think we want to push to the live site on merge given the eventual need to version the docs.

**Comment by mberhault** [comment]
We can easily add a deployment step to circleci for green `gh-pages` merges. This would just rerun `jekyll` with `baseurl: /docs` and rsync to the web server. circleci has a section for ssh keys.

The only question is whether we really want to do this. Let me know.

**Comment by jseldess** [comment]
Good to know, @mberhault. I'm hesitant to do this right now because there might be PRs we want merged but not published. Let's hold off until we know how and when we'll version the docs.

**Comment by jseldess** [comment]
We have a 1-click push to dreamhost via teamcity, thanks to @mjibson.
