### ISSUE TITLE
clarify node drain vs. quit

### ISSUE THREAD

**Issue by taroface** [cockroachdb/docs#9009]
Ryan Kuo (taroface) commented:

EDIT: Remove {{cockroach quit}} doc and steps from relevant tutorials ([example](https://www.cockroachlabs.com/docs/v21.2/secure-a-cluster.html)).

The difference between `cockroach quit` (deprecated) and `cockroach node drain` can be clarified in both docs and [Decommission Nodes](https://www.cockroachlabs.com/docs/stable/remove-nodes.html), as well as the reason the former was deprecated.

* Add information from [this PR](https://github.com/cockroachdb/cockroach/pull/45149) regarding the shutdown sequence. 
* Note that both `cockroach quit` and `cockroach node drain` iterate the shutdown sequence until there is no load left on the server
* Link to the relevant cluster settings from the documentation.
* Reiterate that SIGTERM can be used to end the process rather than either command.

Thread: [https://cockroachlabs.slack.com/archives/C013VDTRA30/p1605559409025600](https://cockroachlabs.slack.com/archives/C013VDTRA30/p1605559409025600)

Jira Issue: DOC-837

**Comment by rmloveland** [comment]
Getting feedback in internal chat today (2021-07-21) that we should really rewrite the `cockroach quit` page to point users to `cockroach node drain` docs instead.  

FWIW I think the fact that (a) the `cockroach quit` page still exists, and (b) tries to explain stuff in place rather than saying "don't use this, go to the other doc instead" makes things more confusing, not less

Capturing some of the chat since it may be clearer than what is in our doc tbh

> Q: In what situations do we expect someone to drain a node? I think the answer is when they want a less impactful shutdown and can afford the time?
> A: any shutdown without a drain will have an impact on foreground traffic
> i.e. if you just kill -9 a node, then all the leases on that node are gone, so now the system has to wait out all the timeouts to move the leases to healthy nodes
> the drain process avoids that and moves leases gracefully
> the typical operqting procedure for cycling a node is
> 1. Drain
> 2. Wait x seconds
> 3. If the drain fails to complete, kill -9

FWIW I have a docs PR in progress explaining the process for lease acquisition (step involving "wait out all the timeouts") when a node is killed abruptly that might be useful to link to once it's merged: #10917

**Comment by taroface** [comment]
> Getting feedback in internal chat today (2021-07-21) that we should really rewrite the `cockroach quit` page to point users to `cockroach node drain` docs instead.
> 
> FWIW I think the fact that (a) the `cockroach quit` page still exists, and (b) tries to explain stuff in place rather than saying "don't use this, go to the other doc instead" makes things more confusing, not less

I'm in agreement! Thanks, and will look forward to your PR too.

**Comment by taroface** [comment]
Related: https://github.com/cockroachdb/cockroach/pull/68652
