### ISSUE TITLE
sql: create region type enums for multiregion databases 

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9123]
PR: https://github.com/cockroachdb/cockroach/pull/56628

From release notes:
> When creating a database with the regions clause specified, CockroachDB now creates a `regions` enum type automatically. [#56628][#56628] {% comment %}doc{% endcomment %}

**Comment by rmloveland** [comment]
Closing since we have docs for the `crdb_region` region enum column on the [`SET LOCALITY`](https://www.cockroachlabs.com/docs/v21.1/set-locality.html#set-the-table-locality-to-regional-by-row) page.  We also mention the column on the [multi-region overview page](https://www.cockroachlabs.com/docs/v21.1/multiregion-overview#indexes-on-regional-by-row-tables)
