### ISSUE TITLE
Update roles for IMPORT INTO

### ISSUE THREAD

**Issue by shermanCRL** [cockroachdb/docs#9179]
It appears that the [IMPORT INTO docs for 20.2](https://www.cockroachlabs.com/docs/v20.2/import-into) do not accurately reflect the required permissions. It’s currently documented as admin-only, but looking at tests, it appears that INSERT/CREATE/DROP have rights?

@adityamaru @pbardea Would you explain the rights in a comment here? I am happy to update the docs. Or, you can update directly. Thanks.

**Comment by adityamaru** [comment]
@shermanCRL I've listed out the required privileges for each of the bulk jobs below. The umbrella admin check was removed from IMPORT, BACKUP, and RESTORE, and so the docs for all three might need to be updated. They all share the same admin/non-admin requirements based on the URI they're writing/reading from and so I shall flesh that out first:

The URI **does not require** `admin` for the following constructs:
- For s3 and gs the credentials are `SPECIFIED` (and not `IMPLICIT`). Azure is always `SPECIFIED` by default.
- In the case of S3 there is no custom endpoint.
- Userfile

`nodelocal`, `http` and `https` require admin privileges.

Job-specific privileges:

`IMPORT INTO`:
- `INSERT` and `DROP` privileges. `DROP` is required because we need to take the table offline during the IMPORT INTO.

`IMPORT`:
- `CREATE` is required.

`BACKUP`:
- Full cluster backups require admin role.
- DB and table backups require `SELECT`
- If the backups also contain UDS and UDT then one needs `USAGE` as well.

`RESTORE`:
- Full cluster restore requires admin role.
- DB restores require the `CREATEDB` role.
- `CREATE` privileges in the parent DB being restored into is required by all restores.

I'm also going to rope in @lnhsingh in case there is a draft for this in cold storage as there have been previous discussions on Slack about adding this documentation. 😃

**Comment by shermanCRL** [comment]
@adityamaru What is a custom endpoint for S3? Custom domain?

**Comment by shermanCRL** [comment]
@adityamaru And, inferring from above, `IMPLICIT` credentials for S3 and GS _do_ require `ADMIN`, yes?

**Comment by adityamaru** [comment]
> @adityamaru What is a custom endpoint for S3? Custom domain?
If a customer wants to override the default service API endpoint with a custom endpoint they can specify this param - https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/

> @adityamaru And, inferring from above, IMPLICIT credentials for S3 and GS do require ADMIN, yes?
Yup, cause then we are relying on the machine we are running on to authenticate us, and only ADMIN should be allowed to rely on this.

**Comment by lnhsingh** [comment]
Related to https://github.com/cockroachdb/docs/issues/8432 (will close that issue in favor of this one).

Thanks for starting this! I don't have a draft other than the hodgepodge of notes that are included in that other issue.

**Comment by shermanCRL** [comment]
@adityamaru What does it mean to ‘invalidate’ foreign key constraints? Does it mean they are simply not enforced during IMPORT INTO? ‘Invalidate’ sounds like we remove them or disable them or something.

**Comment by adityamaru** [comment]
After we have imported into a table we do not vouch for the foreign key constraints which previously existed on the target table to still be valid. They will continue to be enforced for subsequent updates. This is why at the end of the import we actively set all the FKs to an invalidated state. This does not mean that we remove them, just that they might not hold for all the data ingested into the table. To enforce them one must use https://www.cockroachlabs.com/docs/stable/validate-constraint.html

pg docs have a nice explanation:
```Normally, this form will cause a scan of the table to verify that all existing rows in the table satisfy the new constraint. But if the NOT VALID option is used, this potentially-lengthy scan is skipped. The constraint will still be enforced against subsequent inserts or updates (that is, they'll fail unless there is a matching row in the referenced table, in the case of foreign keys, or they'll fail unless the new row matches the specified check condition). But the database will not assume that the constraint holds for all rows in the table, until it is validated by using the VALIDATE CONSTRAINT option.```

**Comment by lnhsingh** [comment]
Closing this, as Matt's PR in December closed this.
