### ISSUE TITLE
Missing style for table headers

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/docs#9376]
In tables, the header rows is bolded, but there's no other visual indication that it's a header. Shouldn't we have some shading, @luciaaaaaaa?

Example: https://deploy-preview-8489--cockroachdb-docs.netlify.app/docs/v20.2/cockroach-start.html#general

**Comment by lnhsingh** [comment]
Table header rows are displaying as mocked: https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=3254%3A8174

However, we didn't prioritize adding the filters to tables (which would add the arrows in the header). Since we don't have the filters, it might be good to add a grey background to the table headers

**Comment by luciaaaaaaa** [comment]
This issue willl require design work

**Comment by jseldess** [comment]
@luciaaaaaaa, do you feel tables are fine as-is, or do you think header rows should have a different background shading? If the former, let's just close this.

**Comment by luciaaaaaaa** [comment]
I think this is okay as is. The bolded table headers match the Design System. This issue can be closed
