### ISSUE TITLE
Font spacing is tight 

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/docs#9430]
Spacing between text in list items feels tight (screenshot 1) 
Spacing between body copy and code snippits feels tight (screenshot 2)

<img width="788" alt="Screen Shot 2021-01-21 at 11 33 10 AM" src="https://user-images.githubusercontent.com/51920721/105381092-a12dd400-5bdc-11eb-8e66-b5b5e2a1ef36.png">

<img width="960" alt="Screen Shot 2021-01-21 at 11 14 29 AM" src="https://user-images.githubusercontent.com/51920721/105380740-3ed4d380-5bdc-11eb-90a8-15990dacb61a.png">

**Comment by luciaaaaaaa** [comment]
Design fix: 

**For 1.** "Spacing between text in list items feels tight (screenshot 1)" Vertical spacing in numbered lists should match spacing in bullet lists and should be concistent accross all lists. 
See bullet vs. numbered lists spacing in this link for reference: https://600fd229b7cea40008a185f2--cockroachdb-docs.netlify.app/docs/cockroachcloud/create-your-cluster.html 


**For 2.** "Spacing between body copy and code snippits feels tight (screenshot 2)" This might be related to #1 because it is also a numbered list. It also looks like the tabs are pushing all the code-box down, making it look like the code relates to the description that is below it rather than on top. 
Here is a wireframe that shows spacing with code-box in context https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=2228%3A12437
