### ISSUE TITLE
Decrease whitespace between search result items and docs landing page areas

### ISSUE THREAD

**Issue by luciaaaaaaa** [cockroachdb/docs#9445]
Issue: there is a lot of space between lines. 

For example in the search results page: 
![image](https://user-images.githubusercontent.com/48258790/105387354-7135ff00-5be3-11eb-8dc3-fe2c0fd69550.png)

Another example is between the cards, button and recommended articles in the landing pages. 
![image](https://user-images.githubusercontent.com/48258790/105387480-975b9f00-5be3-11eb-9598-4ba495ed9622.png)

Fix: We could decrease spacing to 30px between search results page so more results fit in a page. In landing pages, make sure padding is equal on top and bottom of the button (70px).

**Comment by jseldess** [comment]
@luciaaaaaaa, for search result items, the top margin is currently 30px, which is what you've asked for. Do you want it to be less, or has this been fixed in the meantime and you're good with it? 

<img width="1249" alt="Screen Shot 2021-03-09 at 1 18 17 PM" src="https://user-images.githubusercontent.com/15893490/110518285-ed27d000-80d9-11eb-92bf-47015819d013.png">

**Comment by jseldess** [comment]
Lucia, for the button, can you give guidance for all of the landing pages, including the main one?

![Screen Shot 2021-03-11 at 12 50 54 PM](https://user-images.githubusercontent.com/15893490/110831977-ce0b7880-8268-11eb-87f0-066f25b3f058.png)

**Comment by luciaaaaaaa** [comment]
Buttons and Search Results page look good to me.
