### ISSUE TITLE
IMPORT: PGDUMP Compatibility Improvements

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9494]
Jira: https://cockroachlabs.atlassian.net/browse/CRDB-30

**Comment by mwang1026** [comment]
There are two new options for `IMPORT PGDUMP` and two new cli options for `cockroach import pgdump`

`IMPORT PGDUMP` options are (and only for PGDUMP imports):
* `ignore_unsupported_statements`
* `log_ignored_statements = 'filelocation`

`cockroach import pgdump` options are:
* `--ignore-unsupported-statements=true`
* `--log-ignored-statements="'filelocation'"`

^Note the weird quoting on that last one. It's being looked at https://github.com/cockroachdb/cockroach/issues/62464

File location can be any of the storage locations we support (userfile, s3, gcs, etc.)

----

The files that are written for logging the ignored statements are structured as listed here https://github.com/cockroachdb/cockroach/pull/62228

We separate schema statements and data statements (in part because they're processed separately, but we don't need to get into that detail)

----

Separately, and maybe it's a separate project, I do feel like we need to have a list of "known ignored statements in PGDUMP and what to do about them". Not knowing this causes pain for customers who don't know beforehand.

For example, if there is a column type that we don't support (e.g. `tsvector`) the `CREATE TABLE` statement will fail and what will be logged in the ignored statement log is `tsvector: could not be parsed`

We also know for example that we ignore all `SET` statements
Anything relating to grants and roles and permissions, because we don't want to accidentally grant permissions to a user in the destination cluster who happens to have the same username as someone from the previous cluster

As a part of this project, I want us to at least think through the structuring of such documents.

**Comment by lnhsingh** [comment]
Related slack convo: https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1616625574115500

**Comment by ianjevans** [comment]
Related #10147.

**Comment by lnhsingh** [comment]
Follow up work (i.e, documenting the list of known ignored statements in PGDUMP) tracked here: https://github.com/cockroachdb/docs/issues/10218
