### ISSUE TITLE
Add a way to navigate back to the general landing page

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9655]
Feedback from @nstewart: how do I get back to this screen after clicking any of the left hand navigation links? I can press the back button a lot, but I would have expected some direct home link. I kept clicking “quickstart” thinking I would go back to the docs home

**Comment by jseldess** [comment]
@luciaaaaaaa, do we already have designs or thoughts about how to do this? This has been nagging at me as well when I use the docs. I also looked at pageviews, and the new main landing page isn't getting as much traffic as we might expect because one they're in other parts of the docs, users don't go back there until next time they enter the docs from the topnav.

**Comment by luciaaaaaaa** [comment]
**Pain point:** The current way to navigate back to the Docs Home page is through the primary nav ... Resources > Technical Resources > Docs. This is a UX pain point because we expect a lot of people to want to navigate back to the 'Docs' Home page, but once you are in the Docs site, the link is not visible at a glance. 

**Potential Solutions:**
- Proposal 1: Link to navigate to the Docs Home from the Docs side-nav 
- Proposal 2: Docs Home link surfaced as a top level nav item on primary nav, rather then as a sub-link of 'Resources'

**Wireframes:**  https://www.figma.com/file/6XcxaUdad2RkjpEqnVHKAG/Education-docs-redesign?node-id=4018%3A8689 

**Open questions:**
- What was the marketing decision making around Docs presented in the ‘Resources’ tab rather than as a top-level nav item? 
- How many people access 'Docs' from the Primary Nav? 
- Is 'Home' well understood to users as the label for our Docs home page? 
- If we adopt option 1, should the page title match the side-nav label?
