### ISSUE TITLE
Create standards for warnings on release pages re. technical advisories, including use of includes

### ISSUE THREAD

**Issue by mikeCRL** [cockroachdb/docs#9789]
Mike Lewis (mikeCRL) commented:

This is a follow up from https://github.com/cockroachdb/docs/pull/9728 where I created one includes for each major version affected by a TA, and then used them across all affected version pages. I got feedback from `@knz` on how we might streamline/standardize this. Let's consider these recommendations as we decide how to handle these going forward.

> 1. keep the include but without the alert box in every release page, i.e. replace
>   `{{site.data.alerts.callout_danger}}{% include ... %}{{site.data.alerts.end}}`
>   with
>   `{% include ... %}`
> 2. make the include reference a _generic_ TA-related include page, e.g. replace
>   `{% include /v19.2/alerts/warning-a58932.md %}`
>   with
>   `{% include /v19.2/alerts/ta-callouts.md %}`
> 3. change the release note generation script to add this include in every new and future release note page, so that it gets linked automatically.
> 4. make the page `ta-callouts.md` use the `{{site.data.alerts...}}` enclosure, one per relevant TA

Note: I had made a conscious choise not to do `#1` when I was authoring, because I wanted it to be apparent to those editing the markdown in the future that we already have a warning, so not to accidentally include an adjacent warning, but perhaps a second bullet in the same warning. Not sure if this is important or what our style should be for including multiple warnings. As it is, there are now pages that have two: This one, and an existing one about the end of support for the release. However, I never included this one adjacent to that one. E.g. on the page for [v19.2.0.](https://www.cockroachlabs.com/docs/releases/v19.2.0)

If we do set any new standards, we should decide whether to update prior markup including https://github.com/cockroachdb/docs/pull/9728.

Jira Issue: DOC-1652

**Comment by KapedRebooster** [comment]
- [ ]  @mikeCRL mikeCRL commented 10 hours ago • 
This is a follow up from #9728 where I created one includes for each major version affected by a TA, and then used them across all affected version pages. I got feedback from @knz on how we might streamline/standardize this. Let's consider these recommendations as we decide how to handle these going forward.

keep the include but without the alert box in every release page, i.e. replace
{{site.data.alerts.callout_danger}}{% include ... %}{{site.data.alerts.end}}
with
{% include ... %}
make the include reference a generic TA-related include page, e.g. replace
{% include /v19.2/alerts/warning-a58932.md %}
with
{% include /v19.2/alerts/ta-callouts.md %}
change the release note generation script to add this include in every new and future release note page, so that it gets linked automatically.
make the page ta-callouts.md use the {{site.data.alerts...}} enclosure, one per relevant TA
Note: I had made a conscious choise not to do #1 when I was authoring, because I wanted it to be apparent to those editing the markdown in the future that we already have a warning, so not to accidentally include an adjacent warning, but perhaps a second bullet in the same warning. Not sure if this is important or what our style should be for including multiple warnings. As it is, there are now pages that have two: This one, and an existing one about the end of support for the release. However, I never included this one adjacent to that one. E.g. on the page for v19.2.0.

If we do set any new standards, we should decide whether to update prior markup including #9728.


Thanks for the input I completely overlooked it and will make a note of it.

**Comment by jseldess** [comment]
@mikeCRL, how do you think we should label and route this one?

**Comment by jseldess** [comment]
@mikeCRL, assigning to you since you have the most context. Please update this issue when you have a chance.

**Comment by mikeCRL** [comment]
A new internal epic for this issue now exists at https://cockroachlabs.atlassian.net/browse/DOC-3363.

**Comment by mari-crl** [comment]
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [DOC-1652](https://cockroachlabs.atlassian.net/browse/DOC-1652) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/docs-9789`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
