### ISSUE TITLE
VPC Peering / AWS PrivateLink tabs are misaligned

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/docs#9918]
Observed on https://www.cockroachlabs.com/docs/cockroachcloud/connect-to-your-cluster.html#establish-vpc-peering-or-aws-privatelink 

![Screen Recording 2021-03-02 at 07 00 PM](https://user-images.githubusercontent.com/1474303/109731669-b1e14a80-7b89-11eb-805e-6846ba81819a.gif)

cc @gemma-shay IIRC you made an adjustment to smooth that out. Looks like it's back - could we tee up a fix here?

**Comment by thtruo** [comment]
Heads up @mikeCRL I preemptively assigned this to you as you're the owner for security specific items. 

Just a friendly ping on this - this misalignment is really noticeable when reading on typical browser widths (FWIW I'm on a Macbook Pro 13' and browser width is < 1200px).

**Comment by gemma-shay** [comment]
Sorry, I totally missed this before. IIRC the fix was just adding a line break above the tab text, but that might not have been as effective as I thought it was in a smaller window.

**Comment by mikeCRL** [comment]
Looks like dropping the line break before VPC Peering will help here, but there are other site-wide style issues to consider:

- Tab labels from multiple tabs wrapping at different viewport widths, causing some to appear to hover too far above the content area.
- Tab labels appearing somewhere between left-aligned and centered.
- Tab labels getting clipped when the viewport gets too small, rather than, say, stacking.

Here are GIFs after removing the line break locally. (Please ignore my color scheme.)

![2021-03-22 10 54 28 3](https://user-images.githubusercontent.com/76072290/112013641-928e6b00-8b00-11eb-975d-f47dbb9f8128.gif)

![2021-03-22 10 55 35](https://user-images.githubusercontent.com/76072290/112010581-d0d65b00-8afd-11eb-9acc-2a65ad0a6a38.gif)

We'll still need a PR to drop that line break. I can do that later today.

@yingzhuchin should we be creating a new issue for those style considerations?

**Comment by yingzhuchin** [comment]
Hi @mikeCRL, sounds good, and could you add the `A-docs-ux` label when you create the issue? Thanks!

**Comment by mikeCRL** [comment]
Here it is https://github.com/cockroachdb/docs/issues/10033. @yingzhuchin: I assigned you, because of the above thread, but please do let me know if it's better in the future to leave you unassigned and if the label is enough.

**Comment by yingzhuchin** [comment]
Thanks, @mikeCRL! Unassigned and label is good.
