### ISSUE TITLE
Clean up Algolia indices

### ISSUE THREAD

**Issue by lnhsingh** [cockroachdb/docs#9920]
To cut down on the number of records we have in Algolia (since that's one of the metrics we're billed on), we should clean up the indices that are no longer in use. It seems like we can get rid of `staging_cockroachcloud_docs`, `TESTING`, `staging_cockroachcloud_docs_object_ids`, and `WP_BLOG_tmp....`. 

We would have to investigate to see if `WP_BLOG` and `cockroachlabs` are actually in use.

**Comment by yingzhuchin** [comment]
`cockroachcloud_docs` usage stats:

`curl -X GET -H "X-Algolia-API-Key: <>" -H "X-Algolia-Application-Id: <>" --compressed "https://usage.algolia.com/1/usage/total_search_operations/cockroachcloud_docs?startDate=2021-01-02T00:00:00Z&endDate=2021-04-01T00:00:00Z&granularity=daily"
{"total_search_operations":[{"t":1609545600000,"v":57},{"t":1609632000000,"v":101},{"t":1609718400000,"v":225},{"t":1609804800000,"v":294},{"t":1609891200000,"v":226},{"t":1609977600000,"v":239},{"t":1610064000000,"v":235},{"t":1610150400000,"v":106},{"t":1610236800000,"v":59},{"t":1610323200000,"v":216},{"t":1610409600000,"v":286},{"t":1610496000000,"v":270},{"t":1610582400000,"v":260},{"t":1610668800000,"v":292},{"t":1610755200000,"v":117},{"t":1610841600000,"v":49},{"t":1610928000000,"v":176},{"t":1611014400000,"v":460},{"t":1611100800000,"v":269},{"t":1611187200000,"v":319},{"t":1611273600000,"v":288},{"t":1611360000000,"v":77},{"t":1611446400000,"v":77},{"t":1611532800000,"v":279},{"t":1611619200000,"v":316},{"t":1611705600000,"v":295},{"t":1611792000000,"v":361},{"t":1611878400000,"v":264},{"t":1611964800000,"v":54},{"t":1612051200000,"v":73},{"t":1612137600000,"v":222},{"t":1612224000000,"v":236},{"t":1612310400000,"v":147},{"t":1612396800000,"v":198},{"t":1612483200000,"v":198},{"t":1612569600000,"v":98},{"t":1612656000000,"v":61},{"t":1612742400000,"v":144},{"t":1612828800000,"v":160},{"t":1612915200000,"v":137},{"t":1613001600000,"v":170},{"t":1613088000000,"v":195},{"t":1613174400000,"v":81},{"t":1613260800000,"v":72},{"t":1613347200000,"v":180},{"t":1613433600000,"v":312},{"t":1613520000000,"v":186},{"t":1613606400000,"v":242},{"t":1613692800000,"v":275},{"t":1613779200000,"v":106},{"t":1613865600000,"v":71},{"t":1613952000000,"v":204},{"t":1614038400000,"v":279},{"t":1614124800000,"v":321},{"t":1614211200000,"v":270},{"t":1614297600000,"v":216},{"t":1614384000000,"v":62},{"t":1614470400000,"v":93},{"t":1614556800000,"v":235},{"t":1614643200000,"v":317},{"t":1614729600000,"v":288},{"t":1614816000000,"v":317},{"t":1614902400000,"v":234},{"t":1614988800000,"v":56},{"t":1615075200000,"v":55},{"t":1615161600000,"v":232},{"t":1615248000000,"v":328},{"t":1615334400000,"v":298},{"t":1615420800000,"v":305},{"t":1615507200000,"v":322},{"t":1615593600000,"v":120},{"t":1615680000000,"v":93},{"t":1615766400000,"v":295},{"t":1615852800000,"v":371},{"t":1615939200000,"v":302},{"t":1616025600000,"v":224},{"t":1616112000000,"v":199},{"t":1616198400000,"v":89},{"t":1616284800000,"v":70},{"t":1616371200000,"v":286},{"t":1616457600000,"v":286},{"t":1616544000000,"v":239},{"t":1616630400000,"v":248},{"t":1616716800000,"v":265},{"t":1616803200000,"v":102},{"t":1616889600000,"v":54},{"t":1616976000000,"v":239},{"t":1617062400000,"v":281},{"t":1617148800000,"v":279}]}`

Looks like `WP_BLOG` gets scattered hits from time to time:

`curl -X GET -H "X-Algolia-API-Key: <>" -H "X-Algolia-Application-Id: <>" --compressed "https://usage.algolia.com/1/usage/total_search_operations/WP_BLOG?startDate=2021-01-02T00:00:00Z&endDate=2021-04-01T00:00:00Z&granularity=daily"
{"total_search_operations":[{"t":1609545600000,"v":1},{"t":1609632000000,"v":3},{"t":1609718400000,"v":14},{"t":1609804800000,"v":19},{"t":1609891200000,"v":24},{"t":1609977600000,"v":12},{"t":1610064000000,"v":8},{"t":1610150400000,"v":0},{"t":1610236800000,"v":0},{"t":1610323200000,"v":8},{"t":1610409600000,"v":11},{"t":1610496000000,"v":10},{"t":1610582400000,"v":12},{"t":1610668800000,"v":30},{"t":1610755200000,"v":4},{"t":1610841600000,"v":4},{"t":1610928000000,"v":3},{"t":1611014400000,"v":7},{"t":1611100800000,"v":14},{"t":1611187200000,"v":9},{"t":1611273600000,"v":15},{"t":1611360000000,"v":2},{"t":1611446400000,"v":7},{"t":1611532800000,"v":8},{"t":1611619200000,"v":24},{"t":1611705600000,"v":12},{"t":1611792000000,"v":13},{"t":1611878400000,"v":13},{"t":1611964800000,"v":2},{"t":1612051200000,"v":13},{"t":1612137600000,"v":12},{"t":1612224000000,"v":14},{"t":1612310400000,"v":16},{"t":1612396800000,"v":10},{"t":1612483200000,"v":28},{"t":1612569600000,"v":6},{"t":1612656000000,"v":5},{"t":1612742400000,"v":22},{"t":1612828800000,"v":8},{"t":1612915200000,"v":6},{"t":1613001600000,"v":11},{"t":1613088000000,"v":13},{"t":1613174400000,"v":4},{"t":1613260800000,"v":2},{"t":1613347200000,"v":3},{"t":1613433600000,"v":9},{"t":1613520000000,"v":10},{"t":1613606400000,"v":9},{"t":1613692800000,"v":17},{"t":1613779200000,"v":0},{"t":1613865600000,"v":18},{"t":1613952000000,"v":6},{"t":1614038400000,"v":24},{"t":1614124800000,"v":16},{"t":1614211200000,"v":33},{"t":1614297600000,"v":10},{"t":1614384000000,"v":5},{"t":1614470400000,"v":5},{"t":1614556800000,"v":15},{"t":1614643200000,"v":15},{"t":1614729600000,"v":28},{"t":1614816000000,"v":15},{"t":1614902400000,"v":10},{"t":1614988800000,"v":15},{"t":1615075200000,"v":0},{"t":1615161600000,"v":13},{"t":1615248000000,"v":85},{"t":1615334400000,"v":12},{"t":1615420800000,"v":32},{"t":1615507200000,"v":17},{"t":1615593600000,"v":6},{"t":1615680000000,"v":8},{"t":1615766400000,"v":43},{"t":1615852800000,"v":0},{"t":1615939200000,"v":0},{"t":1616025600000,"v":0},{"t":1616112000000,"v":0},{"t":1616198400000,"v":0},{"t":1616284800000,"v":0},{"t":1616371200000,"v":0},{"t":1616457600000,"v":0},{"t":1616544000000,"v":0},{"t":1616630400000,"v":0},{"t":1616716800000,"v":0},{"t":1616803200000,"v":0},{"t":1616889600000,"v":0},{"t":1616976000000,"v":0},{"t":1617062400000,"v":0},{"t":1617148800000,"v":0}]}`

`cockroachlabs` has had no hits this year:

`curl -X GET -H "X-Algolia-API-Key: <>" -H "X-Algolia-Application-Id: <>" --compressed "https://usage.algolia.com/1/usage/total_search_operations/cockroachlabs?startDate=2021-01-02T00:00:00Z&endDate=2021-04-01T00:00:00Z&granularity=daily"
{"total_search_operations":[{"t":1609545600000,"v":0},{"t":1609632000000,"v":0},{"t":1609718400000,"v":0},{"t":1609804800000,"v":0},{"t":1609891200000,"v":0},{"t":1609977600000,"v":0},{"t":1610064000000,"v":0},{"t":1610150400000,"v":0},{"t":1610236800000,"v":0},{"t":1610323200000,"v":0},{"t":1610409600000,"v":0},{"t":1610496000000,"v":0},{"t":1610582400000,"v":0},{"t":1610668800000,"v":0},{"t":1610755200000,"v":0},{"t":1610841600000,"v":0},{"t":1610928000000,"v":0},{"t":1611014400000,"v":0},{"t":1611100800000,"v":0},{"t":1611187200000,"v":0},{"t":1611273600000,"v":0},{"t":1611360000000,"v":0},{"t":1611446400000,"v":0},{"t":1611532800000,"v":0},{"t":1611619200000,"v":0},{"t":1611705600000,"v":0},{"t":1611792000000,"v":0},{"t":1611878400000,"v":0},{"t":1611964800000,"v":0},{"t":1612051200000,"v":0},{"t":1612137600000,"v":0},{"t":1612224000000,"v":0},{"t":1612310400000,"v":0},{"t":1612396800000,"v":0},{"t":1612483200000,"v":0},{"t":1612569600000,"v":0},{"t":1612656000000,"v":0},{"t":1612742400000,"v":0},{"t":1612828800000,"v":0},{"t":1612915200000,"v":0},{"t":1613001600000,"v":0},{"t":1613088000000,"v":0},{"t":1613174400000,"v":0},{"t":1613260800000,"v":0},{"t":1613347200000,"v":0},{"t":1613433600000,"v":0},{"t":1613520000000,"v":0},{"t":1613606400000,"v":0},{"t":1613692800000,"v":0},{"t":1613779200000,"v":0},{"t":1613865600000,"v":0},{"t":1613952000000,"v":0},{"t":1614038400000,"v":0},{"t":1614124800000,"v":0},{"t":1614211200000,"v":0},{"t":1614297600000,"v":0},{"t":1614384000000,"v":0},{"t":1614470400000,"v":0},{"t":1614556800000,"v":0},{"t":1614643200000,"v":5},{"t":1614729600000,"v":0},{"t":1614816000000,"v":3},{"t":1614902400000,"v":0},{"t":1614988800000,"v":0},{"t":1615075200000,"v":0},{"t":1615161600000,"v":0},{"t":1615248000000,"v":0},{"t":1615334400000,"v":0},{"t":1615420800000,"v":0},{"t":1615507200000,"v":0},{"t":1615593600000,"v":0},{"t":1615680000000,"v":0},{"t":1615766400000,"v":0},{"t":1615852800000,"v":6},{"t":1615939200000,"v":2},{"t":1616025600000,"v":3},{"t":1616112000000,"v":0},{"t":1616198400000,"v":0},{"t":1616284800000,"v":0},{"t":1616371200000,"v":0},{"t":1616457600000,"v":0},{"t":1616544000000,"v":0},{"t":1616630400000,"v":0},{"t":1616716800000,"v":0},{"t":1616803200000,"v":0},{"t":1616889600000,"v":0},{"t":1616976000000,"v":0},{"t":1617062400000,"v":0},{"t":1617148800000,"v":0}]}`

I will follow the above pattern and delete indices without search activity since this January.

**Comment by yingzhuchin** [comment]
Done.
